/*****************************************************************************
* Model: pasm.qm
* File:  ./pasm.h
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
/* @(/1/0) .................................................................*/
typedef struct PaTag {
/* protected: */
    QActive super;

/* private: */
    uint8_t op_status;
    uint8_t band;
    uint8_t ctrlr;
} Pa;

/* protected: */
QState Pa_initial(Pa *me);
QState Pa_powerOff(Pa *me);
QState Pa_powerOn(Pa *me);
QState Pa_warmup(Pa *me);
QState Pa_operational(Pa *me);
QState Pa_transmitting(Pa *me);
QState Pa_unused(Pa *me);
QState Pa_ready(Pa *me);
QState Pa_cooldown(Pa *me);

