front_panel/antenna_ctrl.c File Reference
Antenna control functions.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <string.h>
#include `antenna_ctrl.h`
#include `main.h`
#include `eeprom.h`
#include `led_control.h`
#include `band_ctrl.h`
#include `event_handler.h`
#include `../global.h`
#include `../wmv_bus/bus.h`
#include `../wmv_bus/bus_rx_queue.h`
#include `../wmv_bus/bus_tx_queue.h`
#include `../wmv_bus/bus_commands.h`
Functions
unsigned char antenna_ctrl_get_comb_value (unsigned char antenna_comb)
unsigned char antenna_ctrl_comb_allowed (unsigned char antenna_comb)
Retrieve if a certain antenna combination is allowed.
void antenna_ctrl_deactivate_outputs (unsigned char *addresses, unsigned char length, unsigned char cmd)
This function will go through a parameter with addresses and send a command to it.
unsigned char antenna_ctrl_antenna_selected (void)
This function returns the selected antenna combination.
void antenna_ctrl_send_ant_data_to_bus (void)
Send the output string for the current antenna to the bus.
void antenna_ctrl_send_rx_ant_data_to_bus (unsigned char antenna_index)
Send the output string for the rx antenna to the bus.
void antenna_ctrl_send_rx_ant_band_data_to_bus (char index)
Send the output string for the rx antenna to the bus.
void antenna_ctrl_rotate (unsigned char ant_index, unsigned int heading)
void antenna_ctrl_change_rx_ant (unsigned char ant_index)
Function used to change an rx antenna.
unsigned char antenna_ctrl_get_rotatable (void)
Get which antennas can be rotated.
void antenna_ctrl_deactivate_all (void)
Function which will deactivate all activated antenna ctrl outputs, using type BUS_CMD_DRIVER_DEACTIVATE_ALL_ANT_OUTPUTS.
void antenna_ctrl_deactivate_all_rx_band (void)
Function which will deactivate all activated rx antenna ctrl band outputs, using type BUS_CMD_DRIVER_DEACTIVATE_ALL_RX_BAND_OUTPUTS.
void antenna_ctrl_set_antenna_text (char *str, unsigned char index)
Set the antenna text.
char * antenna_ctrl_get_antenna_text (unsigned char index)
unsigned char antenna_ctrl_get_antenna_text_length (unsigned char index)
Get the antenna text length.
void antenna_ctrl_set_output_comb (unsigned char *data, unsigned char index, unsigned char length)
Set the output combination string.
unsigned char * antenna_ctrl_get_output_comb (unsigned char index)
Retrieve the output combination string.
unsigned char antenna_ctrl_get_output_comb_length (unsigned char index)
Retrieve the length of the output combination string.
void antenna_ctrl_set_direction (unsigned int dir, unsigned char index)
Set the direction of a specific antenna.
unsigned int antenna_ctrl_get_direction (unsigned char index)
Get the direction of a specific antenna.
unsigned char antenna_ctrl_get_rotator_addr (unsigned char ant_index)
Get the address of the rotator at a certain antenna index.
void antenna_ctrl_set_flags (unsigned char flags, unsigned char index)
Set the antenna flags.
unsigned char antenna_ctrl_get_flags (unsigned char index)
Get the antenna flags.
void antenna_ctrl_set_comb_allowed (unsigned int comb)
Set the value of combination allowed.
void antenna_ctrl_set_rotator_flags (unsigned char ant_index, unsigned char flags)
Set the flags of the rotator, see antenna_ctrl.h for defines.
unsigned char antenna_ctrl_get_rotator_flags (unsigned char ant_index)
Get the flags of the rotator, see antenna_ctrl.h for defines.
unsigned int antenna_ctrl_get_comb_allowed (void)
Get the value of combination allowed.
void antenna_ctrl_set_antenna_data (struct_antenna *data)
Set the antenna data.
void antenna_ctrl_set_rx_antenna_data (struct_rx_antennas *data)
Set the antenna rx data.
unsigned char antenna_ctrl_get_rx_antenna_count (void)
Retrieve the number of rx antennas.
char * antenna_ctrl_get_rx_antenna_name (unsigned char ant_index)
Retrieve the rx antenna name.
char * antenna_ctrl_get_rx_antenna_output_str (unsigned char ant_index)
Retrieve the rx antenna output str.
void antenna_ctrl_select_default_ant (void)
Function which will select the default antenna for this band if it is configured.
void antenna_ctrl_ant_read_eeprom (unsigned char band_index)
Read the eeprom for the antenna settings.
void antenna_ctrl_rx_ant_read_eeprom (void)
Read the eeprom for the rx antenna settings.
unsigned int antenna_ctrl_get_start_heading (unsigned char ant_index)
Function returns the start heading for a certain antenna.
unsigned int antenna_ctrl_get_max_rotation (unsigned char ant_index)
Function returns the maximal number of degrees we can rotate an antenna.
unsigned char antenna_ctrl_get_sub_menu_type (unsigned char ant_index)
Get which kind of sub meny type an antenna has got.
Variables
struct_antenna current_antennas
Contains the current antenna information.
struct_rx_antennas rx_antennas
Contains the rx antenna information.
unsigned int main_flags
Different flags, description is found in main.h.
unsigned char current_activated_ant_outputs [ANTENNA_OUTPUT_COMB_SIZE]
Array which we store the current devices which we have activated antenna outputs on.
unsigned char current_activated_ant_outputs_length = 0
How many devices we have activated antenna outputs on.
unsigned char current_activated_rx_ant_outputs [RX_ANTENNA_OUTPUT_STR_LENGTH]
Array which we store the current devices which we have rx antenna activated outputs on.
unsigned char current_activated_rx_ant_outputs_length = 0
How many devices we have activated rx antenna outputs on.
unsigned char current_band_activated_outputs_rx [RX_ANTENNA_BAND_OUTPUT_STR_LENGTH]
Array which we store the current devices which we have activated rx antenna band outputs on.
unsigned char current_band_activated_outputs_rx_length = 0
How many devices we have activated rx antenna band outputs on.
Detailed Description
Antenna control functions.
Antenna control functions
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/antenna_ctrl.c" 
Definition in file antenna_ctrl.c.
Function Documentation
void antenna_ctrl_ant_read_eeprom (unsigned char band_index)
Read the eeprom for the antenna settings.
Parameters:
band_index The band index
Definition at line 493 of file antenna_ctrl.c.
References eeprom_get_antenna_data().
Referenced by band_ctrl_load_band().
unsigned char antenna_ctrl_antenna_selected (void)
This function returns the selected antenna combination.
Returns: The selected antenna combination, for example 1 means antenna 1, 3 means antenna 1 and 2 (binary representation)
Definition at line 134 of file antenna_ctrl.c.
References struct_status::selected_ant, and status.
void antenna_ctrl_change_rx_ant (unsigned char ant_index)
Function used to change an rx antenna.
Parameters:
ant_index Which RX antenna we wish to chose. If ant_index = 0 the rx antenna outputs are disabled
Definition at line 294 of file antenna_ctrl.c.
References antenna_ctrl_deactivate_outputs(), antenna_ctrl_send_rx_ant_data_to_bus(), BUS_CMD_DRIVER_DEACTIVATE_ALL_RX_ANTENNA_OUTPUTS, current_activated_rx_ant_outputs, and current_activated_rx_ant_outputs_length.
Referenced by band_ctrl_change_band(), event_rxant_button_pressed(), event_set_rx_antenna(), and main().
unsigned char antenna_ctrl_comb_allowed (unsigned char antenna_comb)
Retrieve if a certain antenna combination is allowed.
Parameters:
antenna_comb The antenna configuration you wish to check
Returns: 1 if the combination is allowed, 0 if it is not allowed
Definition at line 107 of file antenna_ctrl.c.
References struct_antenna::antenna_comb_allowed.
Referenced by event_tx_button1_pressed(), event_tx_button2_pressed(), event_tx_button3_pressed(), and event_tx_button4_pressed().
void antenna_ctrl_deactivate_outputs (unsigned char * addresses, unsigned char length, unsigned char cmd)
This function will go through a parameter with addresses and send a command to it.
Parameters:
addresses The list of addresses to send CMD to
length The length of the address list
cmd The command we wish to send to the boards in the address list
Definition at line 121 of file antenna_ctrl.c.
References bus_add_tx_message(), bus_get_address(), BUS_MESSAGE_FLAGS_NEED_ACK, and internal_comm_add_tx_message().
Referenced by antenna_ctrl_change_rx_ant(), antenna_ctrl_deactivate_all(), antenna_ctrl_deactivate_all_rx_band(), antenna_ctrl_send_ant_data_to_bus(), antenna_ctrl_send_rx_ant_band_data_to_bus(), antenna_ctrl_send_rx_ant_data_to_bus(), band_ctrl_deactivate_all(), sub_menu_deactivate_all(), and sub_menu_send_data_to_bus().
char* antenna_ctrl_get_antenna_text (unsigned char index)
Get the antenna text
Parameters:
index The index of the antenna
Returns: A pointer to the string
Definition at line 342 of file antenna_ctrl.c.
References struct_antenna::antenna_text.
Referenced by display_antennas(), and display_show_sub_menu().
unsigned char antenna_ctrl_get_antenna_text_length (unsigned char index)
Get the antenna text length.
Parameters:
index The index of the antenna
Returns: the length of the text
Definition at line 349 of file antenna_ctrl.c.
References struct_antenna::antenna_text_length.
Referenced by display_antennas(), and display_invert_antenna().
unsigned int antenna_ctrl_get_comb_allowed (void)
Get the value of combination allowed.
Returns: The combination allowed value
Definition at line 437 of file antenna_ctrl.c.
References struct_antenna::antenna_comb_allowed.
unsigned int antenna_ctrl_get_direction (unsigned char index)
Get the direction of a specific antenna.
Parameters:
index The index of the antenna
Returns: The direction of the antenna
Definition at line 388 of file antenna_ctrl.c.
References struct_antenna::antenna_direction.
Referenced by display_rotator_directions(), event_rotate_button_pressed(), event_tx_button1_pressed(), event_tx_button2_pressed(), event_tx_button3_pressed(), and event_tx_button4_pressed().
unsigned char antenna_ctrl_get_flags (unsigned char index)
Get the antenna flags.
Parameters:
index The index of which antenna you wish to get the flag content from
Returns: The flags
Definition at line 411 of file antenna_ctrl.c.
References struct_antenna::antenna_flag.
Referenced by display_antennas(), display_invert_antenna(), display_rotator_directions(), event_rotate_button_pressed(), event_tx_button1_pressed(), event_tx_button2_pressed(), event_tx_button3_pressed(), event_tx_button4_pressed(), and main_update_ptt_status().
unsigned int antenna_ctrl_get_max_rotation (unsigned char ant_index)
Function returns the maximal number of degrees we can rotate an antenna.
Parameters:
ant_index The antenna index we wish to retrieve the information from
Returns: The number of degrees the antenna can be rotated
Definition at line 512 of file antenna_ctrl.c.
References struct_antenna::rotator_max_rotation.
Referenced by event_pulse_sensor_down(), and event_pulse_sensor_up().
unsigned char* antenna_ctrl_get_output_comb (unsigned char index)
Retrieve the output combination string.
Parameters:
index Which of the bands you wish to get the output string for
Returns: pointer to the string beginning
Definition at line 367 of file antenna_ctrl.c.
References struct_antenna::antenna_comb_output_str.
unsigned char antenna_ctrl_get_output_comb_length (unsigned char index)
Retrieve the length of the output combination string.
Parameters:
index Which of the combinations you wish to retrieve the length of
Returns: The length of the output string
Definition at line 374 of file antenna_ctrl.c.
References struct_antenna::antenna_output_length.
unsigned char antenna_ctrl_get_rotatable (void)
Get which antennas can be rotated.
Returns: Which antennas can be rotated, in binary form starting with ant 0 from byte 0
Definition at line 306 of file antenna_ctrl.c.
References struct_antenna::antenna_flag, and ANTENNA_ROTATOR_FLAG.
Referenced by ISR().
unsigned char antenna_ctrl_get_rotator_addr (unsigned char ant_index)
Get the address of the rotator at a certain antenna index.
Parameters:
ant_index The index of the antenna
Returns: The address of the rotator
Definition at line 395 of file antenna_ctrl.c.
References struct_antenna::rotator_addr.
unsigned char antenna_ctrl_get_rotator_flags (unsigned char ant_index)
Get the flags of the rotator, see antenna_ctrl.h for defines.
Returns: The rotator flags of the antenna
Definition at line 430 of file antenna_ctrl.c.
References struct_antenna::rotator_flags.
Referenced by ISR().
unsigned char antenna_ctrl_get_rx_antenna_count (void)
Retrieve the number of rx antennas.
Returns: The number of rx antenna count
Definition at line 455 of file antenna_ctrl.c.
References struct_rx_antennas::name.
Referenced by display_show_rx_ant(), event_pulse_sensor_down(), event_pulse_sensor_up(), and event_rxant_button_pressed().
char* antenna_ctrl_get_rx_antenna_name (unsigned char ant_index)
Retrieve the rx antenna name.
Parameters:
ant_index The index of the antenna
Returns: The name of the RX antenna
Definition at line 468 of file antenna_ctrl.c.
References struct_rx_antennas::name.
Referenced by display_show_rx_ant().
char* antenna_ctrl_get_rx_antenna_output_str (unsigned char ant_index)
Retrieve the rx antenna output str.
Parameters:
ant_index The index of the antenna
Returns: The output str of the rx antenna sent in
Definition at line 475 of file antenna_ctrl.c.
References struct_rx_antennas::output_str.
unsigned int antenna_ctrl_get_start_heading (unsigned char ant_index)
Function returns the start heading for a certain antenna.
Parameters:
ant_index The index of the antenna we wish to retrieve the heading from
Returns: The start heading of this antenna
Definition at line 505 of file antenna_ctrl.c.
References struct_antenna::rotator_min_heading.
Referenced by event_pulse_sensor_down(), and event_pulse_sensor_up().
unsigned char antenna_ctrl_get_sub_menu_type (unsigned char ant_index)
Get which kind of sub meny type an antenna has got.
Parameters:
ant_index Which antenna index we wish to show the sub menu type for
Returns: The sub meny type
Definition at line 519 of file antenna_ctrl.c.
References struct_antenna::sub_menu_type.
Referenced by display_rotator_directions(), event_sub_button_pressed(), sub_menu_activate_all(), sub_menu_get_count(), sub_menu_get_text(), sub_menu_get_type(), and sub_menu_load().
void antenna_ctrl_send_rx_ant_band_data_to_bus (char index)
Send the output string for the rx antenna to the bus.
Parameters:
index The index of the antenna you wish to send the string of
Definition at line 231 of file antenna_ctrl.c.
References antenna_ctrl_deactivate_outputs(), struct_rx_antennas::band_output_length, struct_rx_antennas::band_output_str, bus_add_tx_message(), BUS_CMD_DRIVER_ACTIVATE_RX_BAND_OUTPUT, BUS_CMD_DRIVER_DEACTIVATE_ALL_RX_BAND_OUTPUTS, bus_get_address(), BUS_MESSAGE_FLAGS_NEED_ACK, current_band_activated_outputs_rx, current_band_activated_outputs_rx_length, internal_comm_add_tx_message(), and OUTPUT_ADDR_DELIMITER.
Referenced by band_ctrl_change_band().
void antenna_ctrl_send_rx_ant_data_to_bus (unsigned char antenna_index)
Send the output string for the rx antenna to the bus.
Parameters:
antenna_index The index of the antenna you wish to send the string of
Definition at line 189 of file antenna_ctrl.c.
References antenna_ctrl_deactivate_outputs(), bus_add_tx_message(), BUS_CMD_DRIVER_ACTIVATE_RX_ANT_OUTPUT, BUS_CMD_DRIVER_DEACTIVATE_ALL_RX_ANTENNA_OUTPUTS, bus_get_address(), BUS_MESSAGE_FLAGS_NEED_ACK, current_activated_rx_ant_outputs, current_activated_rx_ant_outputs_length, internal_comm_add_tx_message(), OUTPUT_ADDR_DELIMITER, struct_rx_antennas::output_length, and struct_rx_antennas::output_str.
Referenced by antenna_ctrl_change_rx_ant().
void antenna_ctrl_set_antenna_data (struct_antenna * data)
Set the antenna data.
Parameters:
data The data we wish to use as antenna data
Definition at line 443 of file antenna_ctrl.c.
void antenna_ctrl_set_antenna_text (char * str, unsigned char index)
Set the antenna text.
Parameters:
str Which data should be saved
index The index of the antenna
Definition at line 335 of file antenna_ctrl.c.
References struct_antenna::antenna_text.
void antenna_ctrl_set_comb_allowed (unsigned int comb)
Set the value of combination allowed.
Parameters:
comb The combination that is allowed
Definition at line 417 of file antenna_ctrl.c.
References struct_antenna::antenna_comb_allowed.
void antenna_ctrl_set_direction (unsigned int dir, unsigned char index)
Set the direction of a specific antenna.
Parameters:
dir The direction of the antenna
index The index of the antenna
Definition at line 381 of file antenna_ctrl.c.
References struct_antenna::antenna_direction.
void antenna_ctrl_set_flags (unsigned char flags, unsigned char index)
Set the antenna flags.
Parameters:
flags The flags you wish to be enabled for this antenna
index The index of the antenna which the flags should be set to
Definition at line 403 of file antenna_ctrl.c.
References struct_antenna::antenna_flag.
void antenna_ctrl_set_output_comb (unsigned char * data, unsigned char index, unsigned char length)
Set the output combination string.
Parameters:
data The string you wish to save
index The index of the output combination
length The length of the output string
Definition at line 358 of file antenna_ctrl.c.
References struct_antenna::antenna_comb_output_str, and struct_antenna::antenna_output_length.
void antenna_ctrl_set_rotator_flags (unsigned char ant_index, unsigned char flags)
Set the flags of the rotator, see antenna_ctrl.h for defines.
Parameters:
ant_index The antenna index
flags Flags from the rotator
Definition at line 424 of file antenna_ctrl.c.
References struct_antenna::rotator_flags.
void antenna_ctrl_set_rx_antenna_data (struct_rx_antennas * data)
Set the antenna rx data.
Parameters:
data The data we wish to use as rx antenna data
Definition at line 449 of file antenna_ctrl.c.