front_panel/band_ctrl.h File Reference
Band control functions.
#include `main.h`
Classes
struct struct_band
Struct of band data.
struct struct_band_limits
Struct of the band limits.
Functions
void band_ctrl_load_band_limits (void)
Loads the band limits into the band limits struct.
unsigned int band_ctrl_get_low_portion_low (unsigned char band)
Retrieve the lower frequency limit of the low band limit.
unsigned int band_ctrl_get_low_portion_high (unsigned char band)
Retrieve the higher frequency limit of the low band limit.
unsigned int band_ctrl_get_high_portion_low (unsigned char band)
Retrieve the lower frequency limit of the high band limit.
unsigned int band_ctrl_get_high_portion_high (unsigned char band)
Retrieve the higher frequency limit of the high band limit.
unsigned char * band_ctrl_get_high_output_str (void)
Retrieve the higher frequency output string, of max length BAND_OUTPUT_STR_SIZE.
unsigned char * band_ctrl_get_low_output_str (void)
Retrieve the lower frequency output string, of max length BAND_OUTPUT_STR_SIZE.
void band_ctrl_deactivate_all (void)
Function which will deactiavate all band outptus, BUS_CMD_DRIVER_DEACTIVATE_ALL_BAND_OUTPUTS.
void band_ctrl_change_band_portion (unsigned char band_portion)
Function will send out new band portion settings for the current selected band *.
void band_ctrl_change_band (unsigned char band)
Function used to change band.
Variables
struct_band_limits band_limits [9]
The band limits, an array with size 9.
Detailed Description
Band control functions.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/band_ctrl.h" 
Definition in file band_ctrl.h.
Function Documentation
void band_ctrl_change_band (unsigned char band)
Function used to change band.
Parameters:
band The band we wish to change to
Definition at line 145 of file band_ctrl.c.
References antenna_ctrl_change_rx_ant(), antenna_ctrl_deactivate_all(), antenna_ctrl_deactivate_all_rx_band(), antenna_ctrl_select_default_ant(), antenna_ctrl_send_rx_ant_band_data_to_bus(), band_ctrl_deactivate_all(), band_ctrl_load_band(), band_ctrl_send_band_data_to_bus(), struct_status::current_band_portion, struct_status::current_display, CURRENT_DISPLAY_ANTENNA_INFO, struct_status::current_display_level, CURRENT_DISPLAY_LOGO, CURRENT_DISPLAY_MENU_SYSTEM, CURRENT_DISPLAY_SHUTDOWN_VIEW, DISPLAY_LEVEL_BAND, FUNC_STATUS_RXANT, struct_status::function_status, INHIBIT_NOT_OK_TO_SEND_RADIO_TX, KNOB_FUNCTION_AUTO, led_set_band(), led_set_band_none(), led_set_rx_ant(), led_set_rxant(), led_set_tx_ant(), LED_STATE_OFF, main_get_inhibit_state(), main_update_display(), main_update_ptt_status(), struct_status::new_band, struct_status::selected_ant, struct_status::selected_band, struct_status::selected_rx_antenna, set_knob_function(), and status.
Referenced by event_internal_comm_parse_message(), event_poll_buttons(), and main().
void band_ctrl_change_band_portion (unsigned char band_portion)
Function will send out new band portion settings for the current selected band *.
Parameters:
band_portion The current band portion
Definition at line 139 of file band_ctrl.c.
References band_ctrl_send_band_data_to_bus().
Referenced by event_aux2_button_pressed(), and main().
unsigned char* band_ctrl_get_high_output_str (void)
Retrieve the higher frequency output string, of max length BAND_OUTPUT_STR_SIZE.
Returns: The output string
Definition at line 253 of file band_ctrl.c.
References struct_band::band_high_output_str.
unsigned int band_ctrl_get_high_portion_high (unsigned char band)
Retrieve the higher frequency limit of the high band limit.
Returns: The frequency in kHz
Definition at line 247 of file band_ctrl.c.
References band_limits.
Referenced by radio_freq_to_band(), and radio_get_band_portion().
unsigned int band_ctrl_get_high_portion_low (unsigned char band)
Retrieve the lower frequency limit of the high band limit.
Returns: The frequency in kHz
Definition at line 241 of file band_ctrl.c.
References band_limits.
Referenced by radio_get_band_portion().
unsigned char* band_ctrl_get_low_output_str (void)
Retrieve the lower frequency output string, of max length BAND_OUTPUT_STR_SIZE.
Returns: The output string
Definition at line 259 of file band_ctrl.c.
References struct_band::band_low_output_str.
unsigned int band_ctrl_get_low_portion_high (unsigned char band)
Retrieve the higher frequency limit of the low band limit.
Returns: The frequency in kHz
Definition at line 235 of file band_ctrl.c.
References band_limits.
Referenced by radio_get_band_portion().
unsigned int band_ctrl_get_low_portion_low (unsigned char band)
Retrieve the lower frequency limit of the low band limit.
Returns: The frequency in kHz
Definition at line 229 of file band_ctrl.c.
References band_limits.
Referenced by radio_freq_to_band(), and radio_get_band_portion().