front_panel/band_ctrl.c File Reference
Band control functions.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include `band_ctrl.h`
#include `main.h`
#include `eeprom.h`
#include `led_control.h`
#include `radio_interface.h`
#include `sub_menu.h`
#include `../global.h`
#include `../internal_comm.h`
#include `../wmv_bus/bus.h`
#include `../wmv_bus/bus_rx_queue.h`
#include `../wmv_bus/bus_tx_queue.h`
#include `../wmv_bus/bus_commands.h`
Functions
void band_ctrl_send_band_data_to_bus (unsigned char band_portion)
Send the output string for the current band to the bus.
void band_ctrl_load_band (unsigned char band)
Function will load a band from the EEPROM into the current_band struct.
void band_ctrl_change_band_portion (unsigned char band_portion)
Function will send out new band portion settings for the current selected band *.
void band_ctrl_change_band (unsigned char band)
Function used to change band.
void band_ctrl_deactivate_all (void)
Function which will deactiavate all band outptus, BUS_CMD_DRIVER_DEACTIVATE_ALL_BAND_OUTPUTS.
void band_ctrl_load_band_limits (void)
Loads the band limits into the band limits struct.
unsigned int band_ctrl_get_low_portion_low (unsigned char band)
Retrieve the lower frequency limit of the low band limit.
unsigned int band_ctrl_get_low_portion_high (unsigned char band)
Retrieve the higher frequency limit of the low band limit.
unsigned int band_ctrl_get_high_portion_low (unsigned char band)
Retrieve the lower frequency limit of the high band limit.
unsigned int band_ctrl_get_high_portion_high (unsigned char band)
Retrieve the higher frequency limit of the high band limit.
unsigned char * band_ctrl_get_high_output_str (void)
Retrieve the higher frequency output string, of max length BAND_OUTPUT_STR_SIZE.
unsigned char * band_ctrl_get_low_output_str (void)
Retrieve the lower frequency output string, of max length BAND_OUTPUT_STR_SIZE.
unsigned char band_ctrl_get_portion (void)
Retrieve which band portion we are currently at.
Variables
struct_band current_band
Contains the current band information.
unsigned char current_band_activated_outputs [BAND_OUTPUT_STR_SIZE]
Array which we use to keep track of which devices we have been activating outputs on.
unsigned char current_band_activated_outputs_length = 0
The number of devices we have activated outputs on.
Detailed Description
Band control functions.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/band_ctrl.c" 
Definition in file band_ctrl.c.
Function Documentation
void band_ctrl_change_band (unsigned char band)
Function used to change band.
Parameters:
band The band we wish to change to
Definition at line 145 of file band_ctrl.c.
References antenna_ctrl_change_rx_ant(), antenna_ctrl_deactivate_all(), antenna_ctrl_deactivate_all_rx_band(), antenna_ctrl_select_default_ant(), antenna_ctrl_send_rx_ant_band_data_to_bus(), band_ctrl_deactivate_all(), band_ctrl_load_band(), band_ctrl_send_band_data_to_bus(), struct_status::current_band_portion, struct_status::current_display, CURRENT_DISPLAY_ANTENNA_INFO, struct_status::current_display_level, CURRENT_DISPLAY_LOGO, CURRENT_DISPLAY_MENU_SYSTEM, CURRENT_DISPLAY_SHUTDOWN_VIEW, DISPLAY_LEVEL_BAND, FUNC_STATUS_RXANT, struct_status::function_status, INHIBIT_NOT_OK_TO_SEND_RADIO_TX, KNOB_FUNCTION_AUTO, led_set_band(), led_set_band_none(), led_set_rx_ant(), led_set_rxant(), led_set_tx_ant(), LED_STATE_OFF, main_get_inhibit_state(), main_update_display(), main_update_ptt_status(), struct_status::new_band, struct_status::selected_ant, struct_status::selected_band, struct_status::selected_rx_antenna, set_knob_function(), and status.
Referenced by event_internal_comm_parse_message(), event_poll_buttons(), and main().
void band_ctrl_change_band_portion (unsigned char band_portion)
Function will send out new band portion settings for the current selected band *.
Parameters:
band_portion The current band portion
Definition at line 139 of file band_ctrl.c.
References band_ctrl_send_band_data_to_bus().
Referenced by event_aux2_button_pressed(), and main().
unsigned char* band_ctrl_get_high_output_str (void)
Retrieve the higher frequency output string, of max length BAND_OUTPUT_STR_SIZE.
Returns: The output string
Definition at line 253 of file band_ctrl.c.
References struct_band::band_high_output_str.
unsigned int band_ctrl_get_high_portion_high (unsigned char band)
Retrieve the higher frequency limit of the high band limit.
Returns: The frequency in kHz
Definition at line 247 of file band_ctrl.c.
References band_limits.
Referenced by radio_freq_to_band(), and radio_get_band_portion().
unsigned int band_ctrl_get_high_portion_low (unsigned char band)
Retrieve the lower frequency limit of the high band limit.
Returns: The frequency in kHz
Definition at line 241 of file band_ctrl.c.
References band_limits.
Referenced by radio_get_band_portion().
unsigned char* band_ctrl_get_low_output_str (void)
Retrieve the lower frequency output string, of max length BAND_OUTPUT_STR_SIZE.
Returns: The output string
Definition at line 259 of file band_ctrl.c.
References struct_band::band_low_output_str.
unsigned int band_ctrl_get_low_portion_high (unsigned char band)
Retrieve the higher frequency limit of the low band limit.
Returns: The frequency in kHz
Definition at line 235 of file band_ctrl.c.
References band_limits.
Referenced by radio_get_band_portion().
unsigned int band_ctrl_get_low_portion_low (unsigned char band)
Retrieve the lower frequency limit of the low band limit.
Returns: The frequency in kHz
Definition at line 229 of file band_ctrl.c.
References band_limits.
Referenced by radio_freq_to_band(), and radio_get_band_portion().
unsigned char band_ctrl_get_portion (void)
Retrieve which band portion we are currently at.
Returns: BAND_LOW, BAND_HIGH or BAND_UNDEFINED
Definition at line 265 of file band_ctrl.c.
References struct_runtime_settings::band_change_mode, BAND_CHANGE_MODE_AUTO, BAND_CHANGE_MODE_MANUAL, struct_status::current_band_portion, radio_get_band_portion(), RADIO_INTERFACE_BCD, radio_interface_get_interface(), runtime_settings, and status.
void band_ctrl_load_band (unsigned char band)
Function will load a band from the EEPROM into the current_band struct.
Parameters:
band The index of the band we wish to load from the EEPROM
Definition at line 126 of file band_ctrl.c.
References antenna_ctrl_ant_read_eeprom(), eeprom_get_band_data(), and sub_menu_load().
Referenced by band_ctrl_change_band().