wmv_bus/bus_rx_queue.c File Reference
FIFO queue for the RXed messages.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `bus_rx_queue.h`
#include `bus.h`
Functions
void rx_queue_init (void)
Initialize the RX queue.
void rx_queue_add (BUS_MESSAGE message)
Insert a message into the RX queue (FIFO).
BUS_MESSAGE rx_queue_get ()
Retrieve the first message from the FIFO RX queue.
void rx_queue_drop (void)
void rx_queue_dropall (void)
Erase all content in the RX queue.
unsigned char rx_queue_is_empty (void)
Check if the queue is empty.
unsigned char rx_queue_size (void)
Get how much size of the RX queue is used at the moment.
Variables
unsigned char bus_rx_queue_size
Variable keeps track of how much of the queue that is currently used.
rx_queue_struct rx_queue
The rx queue.
Detailed Description
FIFO queue for the RXed messages.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "bus_rx_queue.c" 
Definition in file bus_rx_queue.c.
Function Documentation
void rx_queue_add (BUS_MESSAGE message)
Insert a message into the RX queue (FIFO).
Parameters:
message - The message that should be inserted to the queue
Definition at line 55 of file bus_rx_queue.c.
References BUS_RX_QUEUE_SIZE, bus_rx_queue_size, ERROR_TYPE_BUS_RX_QUEUE_FULL, event_set_error(), rx_linked_list::first, rx_linked_list::last, led_set_error(), LED_STATE_ON, and rx_linked_list::message.
Referenced by bus_add_new_message(), and bus_add_rx_message().
void rx_queue_drop (void)
Drops the first message in the queue Frees up the memory space aswell.
Definition at line 91 of file bus_rx_queue.c.
References BUS_RX_QUEUE_SIZE, bus_rx_queue_size, and rx_linked_list::first.
Referenced by bus_parse_message(), and event_bus_parse_message().
void rx_queue_dropall (void)
Erase all content in the RX queue.
Returns: The number of items that were cleared
Definition at line 103 of file bus_rx_queue.c.
References bus_rx_queue_size, rx_linked_list::first, and rx_linked_list::last.
BUS_MESSAGE rx_queue_get (void)
Retrieve the first message from the FIFO RX queue.
Returns: The first message in the queue
Definition at line 84 of file bus_rx_queue.c.
References rx_linked_list::first, and rx_linked_list::message.
Referenced by bus_parse_message(), and event_bus_parse_message().
unsigned char rx_queue_is_empty (void)
Check if the queue is empty.
Returns: 1 if the queue is empty and 0 otherwise
Definition at line 112 of file bus_rx_queue.c.
References rx_linked_list::first, and rx_linked_list::last.
Referenced by main().
unsigned char rx_queue_size (void)
Get how much size of the RX queue is used at the moment.
Returns: The size of the queue that is used
Definition at line 121 of file bus_rx_queue.c.
References bus_rx_queue_size.