wmv_bus/bus.c File Reference
The communication bus protocol used in the openASC project.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <avr/wdt.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include `bus.h`
#include `bus_tx_queue.h`
#include `bus_rx_queue.h`
#include `bus_commands.h`
#include `bus_ping.h`
#include `global.h`
#include `bus_usart.h`
Functions
void bus_init (void)
Init the communication bus.
void bus_set_address (unsigned char addr)
Set the address of this device on the bus.
unsigned char bus_allowed_to_send (void)
Returns if you are allowed to transmit data to the bus or not.
unsigned char bus_get_address (void)
Returns the address of this device.
void bus_send_message (void)
Sends the first message in the FIFO TX queue to the communication bus.
void __inline__ bus_reset_tx_status (void)
Function that resets the bus status variables.
void __inline__ bus_reset_rx_status (void)
Function that resets the bus status variables.
unsigned char bus_is_master (void)
Returns if the bus is set to be master.
void bus_set_is_master (unsigned char state, unsigned char count)
Set the status if the device should be master or not.
void bus_send_nack (unsigned char to_addr, unsigned char error_type)
Send an NOT acknowledge.
void bus_send_ack (unsigned char to_addr)
Send an acknowledge.
unsigned char bus_get_device_count (void)
Receive the device count on the bus.
void bus_set_device_count (unsigned char device_count)
Set the number of devices that are on the bus.
void bus_resend_message (void)
Resend the last message.
void bus_check_tx_status (void)
Checks if there is anything that should be sent in the TX queue.
void bus_add_tx_message (unsigned char from_addr, unsigned char to_addr, unsigned char flags, unsigned char cmd, unsigned char length, unsigned char data[])
Adds a message to the TX queue which will be sent as soon as possible.
void bus_add_rx_message (unsigned char from_addr, unsigned char to_addr, unsigned char flags, unsigned char cmd, unsigned char length, unsigned char data[])
Adds a message to the RX queue which will be sent as soon as possible.
void bus_add_new_message (void)
Adds the message bus_new_message into the RX queue.
void bus_message_nacked (unsigned char addr, unsigned char error_type)
The message last sent was NACKED from the receiver.
void bus_message_acked (unsigned char addr)
The message last sent was acknowledged from the receiver.
ISR (ISR_BUS_USART_DATA)
ISR (ISR_BUS_USART_RECV)
ISR (ISR_BUS_USART_TRANS)
ISR (ISR_BUS_TIMER_COMPARE)
Variables
bus_status_struct bus_status
The bus status structure.
unsigned char calc_checksum = 0
Variable used to calculate the checksum when receiving a message.
BUS_MESSAGE bus_new_message
The new message.
unsigned char timer_bus_timeout = 0
Counter that keeps track of how long time ago it was when we received a new character and if it's over the limit we erase all the RX buffer.
unsigned int counter_sync_timeout = 0
Counter that keeps track of how long time ago it was when we received a new SYNC message on the BUS.
unsigned int counter_130us = 0
Counter which keeps track of each time the 130us timer counts up.
Detailed Description
The communication bus protocol used in the openASC project.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "wmv_bus/bus.c" 
Definition in file bus.c.
Function Documentation
void bus_add_rx_message (unsigned char from_addr, unsigned char to_addr, unsigned char flags, unsigned char cmd, unsigned char length, unsigned char data[])
Adds a message to the RX queue which will be sent as soon as possible.
Parameters:
from_addr The address of the sender
to_addr The address to the receiever
flags Different flags, see defines
cmd The command performed
length The length of the data received
data The data receieved
Definition at line 324 of file bus.c.
References BUS_MESSAGE::cmd, BUS_MESSAGE::data, BUS_MESSAGE::flags, BUS_MESSAGE::from_addr, BUS_MESSAGE::length, rx_queue_add(), and BUS_MESSAGE::to_addr.
void bus_add_tx_message (unsigned char from_addr, unsigned char to_addr, unsigned char flags, unsigned char cmd, unsigned char length, unsigned char data[])
Adds a message to the TX queue which will be sent as soon as possible.
Parameters:
from_addr The address of the sender
to_addr The address to the receiever
flags Different flags, see defines
cmd The command wanted to be performed
length The length of the data wanting to be sent
data The data wanted to be transmitted to the receiever
Definition at line 291 of file bus.c.
References bus_allowed_to_send(), BUS_CMD_SYNC, BUS_MESSAGE::checksum, BUS_MESSAGE::cmd, BUS_MESSAGE::data, BUS_MESSAGE::flags, BUS_MESSAGE::from_addr, BUS_MESSAGE::length, BUS_MESSAGE::to_addr, and tx_queue_add().
Referenced by antenna_ctrl_deactivate_outputs(), antenna_ctrl_send_ant_data_to_bus(), antenna_ctrl_send_rx_ant_band_data_to_bus(), antenna_ctrl_send_rx_ant_data_to_bus(), band_ctrl_send_band_data_to_bus(), bus_parse_message(), bus_send_ack(), bus_send_nack(), ISR(), main(), send_ping(), and sub_menu_send_data_to_bus().
unsigned char bus_allowed_to_send (void)
Returns if you are allowed to transmit data to the bus or not.
Returns: 1 if it's allowed to transmit and 0 if not
Definition at line 114 of file bus.c.
References BUS_STATUS_MASTER_SENT_SYNC_BIT, and bus_status_struct::flags.
Referenced by bus_add_tx_message(), ISR(), and main().
unsigned char bus_get_address (void)
Returns the address of this device.
Returns: The address of this device
Definition at line 123 of file bus.c.
References bus_status_struct::ext_addr.
Referenced by antenna_ctrl_deactivate_outputs(), antenna_ctrl_send_ant_data_to_bus(), antenna_ctrl_send_rx_ant_band_data_to_bus(), antenna_ctrl_send_rx_ant_data_to_bus(), band_ctrl_send_band_data_to_bus(), bus_parse_message(), ISR(), main(), send_ping(), and sub_menu_send_data_to_bus().
unsigned char bus_get_device_count (void)
Receive the device count on the bus.
Returns: The number of devices on the bus
Definition at line 235 of file bus.c.
References bus_status_struct::device_count.
Referenced by main().
unsigned char bus_is_master (void)
Returns if the bus is set to be master.
Returns: 1 if it is configured to be master, 0 otherwise
Definition at line 196 of file bus.c.
References BUS_STATUS_DEVICE_IS_MASTER_BIT, and bus_status_struct::flags.
Referenced by ISR(), and main().
void bus_message_nacked (unsigned char addr, unsigned char error_type)
The message last sent was NACKED from the receiver.
Parameters:
addr The address of the device that sent the NACK
error_type Contains information why the message was NACKED
Definition at line 348 of file bus.c.
References bus_resend_message(), BUS_STATUS_MESSAGE_ACK_TIMEOUT, bus_status_struct::flags, BUS_MESSAGE::to_addr, and tx_queue_get().
Referenced by bus_parse_message(), and event_bus_parse_message().
void bus_send_nack (unsigned char to_addr, unsigned char error_type)
Send an NOT acknowledge.
Parameters:
to_addr Which address we wish to send the ping to
error_type Why was the message nacked, see bus.h for more information about BUS errors
Definition at line 223 of file bus.c.
References bus_add_tx_message(), BUS_BROADCAST_ADDR, BUS_CMD_NACK, and bus_status_struct::ext_addr.
Referenced by ISR().
void bus_set_address (unsigned char addr)
Set the address of this device on the bus.
Parameters:
addr The address of this device
Definition at line 108 of file bus.c.
References bus_status_struct::ext_addr.
Referenced by main().
void bus_set_device_count (unsigned char device_count)
Set the number of devices that are on the bus.
Parameters:
device_count The number of devices on the bus, ie the number of time slots
Definition at line 241 of file bus.c.
References BUS_TIME_MULTIPLIER, bus_status_struct::device_count, and bus_status_struct::device_count_mult.
void bus_set_is_master (unsigned char state, unsigned char count)
Set the status if the device should be master or not.
Parameters:
state 1 if you wish the device to be master, 0 if you wish that it should be slave
count The nr of devices
Definition at line 206 of file bus.c.
References BUS_STATUS_ALLOWED_TO_SEND_BIT, BUS_STATUS_DEVICE_IS_MASTER_BIT, BUS_STATUS_FORCE_SYNC, BUS_TIME_MULTIPLIER, bus_status_struct::device_count, bus_status_struct::device_count_mult, and bus_status_struct::flags.
Referenced by main().
ISR (ISR_BUS_TIMER_COMPARE)
Timer interrupt with ~130us intervals
Definition at line 512 of file bus.c.
References BUS_ACK_WRAPAROUND_LIMIT, bus_is_master(), bus_resend_message(), bus_reset_rx_status(), BUS_STATUS_MASTER_SENT_SYNC_BIT, BUS_STATUS_MESSAGE_ACK_TIMEOUT, BUS_STATUS_TIME_SLOT_ACTIVE, BUS_SYNC_TIMEOUT_LIMIT, BUS_TIMEOUT_LIMIT, counter_130us, counter_sync_timeout, bus_status_struct::device_count, bus_status_struct::device_count_mult, ERROR_TYPE_BUS_SYNC, event_set_error(), bus_status_struct::flags, bus_status_struct::frame_counter, led_set_error(), LED_STATE_ON, bus_status_struct::lower_limit, timer_bus_timeout, tx_queue_dropall(), bus_status_struct::upper_limit, and bus_status_struct::wraparounds.
ISR (ISR_BUS_USART_TRANS)
USART data transmit interrupt
Definition at line 506 of file bus.c.
References BUS_STATUS_RECEIVE_ON, BUS_STATUS_SEND_ACTIVE, and bus_status_struct::flags.
ISR (ISR_BUS_USART_RECV)
USART data receive interrupt
Definition at line 386 of file bus.c.
References bus_add_new_message(), BUS_BROADCAST_ADDR, BUS_CHECKSUM_ERROR, BUS_CMD_PING, BUS_CMD_SYNC, BUS_MESSAGE_FLAGS_NEED_ACK, bus_ping_new_stamp(), bus_reset_rx_status(), bus_send_ack(), bus_send_nack(), BUS_STATUS_ALLOWED_TO_SEND_BIT, BUS_STATUS_MASTER_SENT_SYNC_BIT, BUS_STATUS_PREAMBLE_FOUND_BIT, BUS_STATUS_RECEIVE_ON, BUS_TIME_MULTIPLIER, calc_checksum, bus_status_struct::char_count, BUS_MESSAGE::checksum, BUS_MESSAGE::cmd, counter_sync_timeout, BUS_MESSAGE::data, bus_status_struct::device_count, bus_status_struct::device_count_mult, bus_status_struct::ext_addr, BUS_MESSAGE::flags, bus_status_struct::flags, bus_status_struct::frame_counter, BUS_MESSAGE::from_addr, BUS_MESSAGE::length, bus_status_struct::prev_char, timer_bus_timeout, and BUS_MESSAGE::to_addr.
ISR (ISR_BUS_USART_DATA)
USART data interrupt
Definition at line 381 of file bus.c.