wmv_bus/bus.h File Reference
The communication bus protocol used in the openASC project.
Classes
struct BUS_MESSAGE
struct rx_linked_list
The structure of the RX circular buffer.
struct tx_linked_list
The structure of the TX circular buffer.
struct bus_status_struct
Defines
#define DEF_NR_DEVICES 25
Define the proper interrupt routines depending on hardware.
#define DEFAULT_STARTUP_DELAY 90
The startup time for the device. This is so that all units dont send ping at the same time.
#define BUS_MSG_PREAMBLE 0xFE
#define BUS_MSG_POSTAMBLE 0xFD
#define BUS_MSG_ACK 0xFA
#define BUS_MSG_NACK 0xFB
#define BUS_BROADCAST_ADDR 0x00
#define DEVICE_ID_MAINBOX 1
Device ID for the mainbox.
#define DEVICE_ID_DRIVER_POS 2
Device ID for the positive driver module.
#define DEVICE_ID_DRIVER_NEG 3
Device ID for the negative driver module.
#define DEVICE_ID_ROTATOR_UNIT 4
Device ID for the rotator unit.
#define DEVICE_ID_COMPUTER 5
Device ID for a computer.
#define DEVICE_ID_POWERMETER_PICKUP 6
Device ID for a power meter pickup.
#define DEVICE_ID_GENERAL_IO 7
Device ID for the General I/O card.
#define BUS_MAX_RESENDS 10
#define BUS_DEVICE_STATUS_MESSAGE_INTERVAL 1500
#define BUS_MASTER_SYNC_INTERVAL 1000
#define BUS_SYNC_TIMEOUT_LIMIT 3200
#define BUS_ACK_WRAPAROUND_LIMIT 10
#define BUS_TIMEOUT_LIMIT 5
#define BUS_STATUS_DEVICE_IS_MASTER_BIT 0
#define BUS_STATUS_ALLOWED_TO_SEND_BIT 1
#define BUS_STATUS_PREAMBLE_FOUND_BIT 2
#define BUS_STATUS_MASTER_SENT_SYNC_BIT 3
#define BUS_STATUS_TIME_SLOT_ACTIVE 4
#define BUS_STATUS_SEND_MESSAGE 5
#define BUS_STATUS_SEND_ACTIVE 6
#define BUS_STATUS_RECEIVE_ON 7
#define BUS_STATUS_FORCE_SYNC 8
#define BUS_STATUS_MESSAGE_ACK_TIMEOUT 9
#define BUS_TIME_MULTIPLIER 4
#define BUS_TIME_INTERRUPT_INTERVAL 130
#define BUS_TIME_FRAME_LIMIT 520
#define BUS_SLOT_DEAD_TIME 130
#define SERIAL_RX_BUF_LENGTH 20
Length of the RX buffer.
#define BUS_MESSAGE_DATA_SIZE 15
Define the length of the bus message data field length.
#define BUS_MESSAGE_FLAGS_NEED_ACK 0
#define BUS_CHECKSUM_ERROR 0
BUS ERRORs.
Typedefs
typedef struct rx_linked_list rx_queue_struct
The structure of the RX circular buffer.
typedef struct tx_linked_list tx_queue_struct
The structure of the TX circular buffer.
Functions
void bus_add_tx_message (unsigned char from_addr, unsigned char to_addr, unsigned char flags, unsigned char cmd, unsigned char length, unsigned char data[])
Adds a message to the TX queue which will be sent as soon as possible.
void bus_add_rx_message (unsigned char from_addr, unsigned char to_addr, unsigned char flags, unsigned char cmd, unsigned char length, unsigned char data[])
Adds a message to the RX queue which will be sent as soon as possible.
void bus_set_address (unsigned char addr)
Set the address of this device on the bus.
unsigned char bus_get_address (void)
Returns the address of this device.
void bus_init (void)
Init the communication bus.
void bus_resend_message (void)
Resend the last message.
void bus_send_ack (unsigned char to_addr)
Send an acknowledge.
void bus_send_nack (unsigned char to_addr, unsigned char error_type)
Send an NOT acknowledge.
void bus_message_acked (unsigned char addr)
The message last sent was acknowledged from the receiver.
void bus_message_nacked (unsigned char addr, unsigned char error_type)
The message last sent was NACKED from the receiver.
void __inline__ bus_reset_tx_status (void)
Function that resets the bus status variables.
void __inline__ bus_reset_rx_status (void)
Function that resets the bus status variables.
unsigned char bus_is_master (void)
Returns if the bus is set to be master.
void bus_set_is_master (unsigned char state, unsigned char count)
Set the status if the device should be master or not.
unsigned char bus_get_device_count (void)
Receive the device count on the bus.
void bus_set_device_count (unsigned char device_count)
Set the number of devices that are on the bus.
unsigned char bus_allowed_to_send (void)
Returns if you are allowed to transmit data to the bus or not.
void bus_check_tx_status (void)
Checks if there is anything that should be sent in the TX queue.
Detailed Description
The communication bus protocol used in the openASC project.
Definition in file bus.h.
Define Documentation
#define BUS_ACK_WRAPAROUND_LIMIT 10
The timeout limit between a message that was sent to when it will be a resend, this is counted as number of wraparounds on the bus, ie 5 would mean 5 wraparounds
Definition at line 171 of file bus.h.
Referenced by ISR().
#define BUS_BROADCAST_ADDR 0x00
Bus broadcast address - All broadcast messages should contain an ID explaining which kind of device that is sending the message
Definition at line 137 of file bus.h.
Referenced by bus_send_message(), bus_send_nack(), ISR(), main(), and send_ping().
#define BUS_DEVICE_STATUS_MESSAGE_INTERVAL 1500
The interval between each status message (time is in ms)
Definition at line 158 of file bus.h.
Referenced by ISR(), and main().
#define BUS_MASTER_SYNC_INTERVAL 1000
The interval which the SYNC command is sent out from the master (time in ms) This value is not allowed to be over 5000 ms since that will make it too big for the timer controlling the SYNC timeout on all the devices.
Definition at line 163 of file bus.h.
Referenced by main().
#define BUS_MAX_RESENDS 10
The number of times a message is resent before it's dropped and an error flag is set
Definition at line 155 of file bus.h.
Referenced by bus_resend_message().
#define BUS_MESSAGE_FLAGS_NEED_ACK 0
BUS MESSAGE flags The message should be ACKED
Definition at line 218 of file bus.h.
Referenced by antenna_ctrl_deactivate_outputs(), antenna_ctrl_send_ant_data_to_bus(), antenna_ctrl_send_rx_ant_band_data_to_bus(), antenna_ctrl_send_rx_ant_data_to_bus(), band_ctrl_send_band_data_to_bus(), ISR(), and sub_menu_send_data_to_bus().
#define BUS_MSG_ACK 0xFA
The acknowledge command of the bus
Definition at line 131 of file bus.h.
#define BUS_MSG_NACK 0xFB
The NOT acknowledge command of the bus
Definition at line 133 of file bus.h.
#define BUS_MSG_POSTAMBLE 0xFD
The postamble of the BUS message
Definition at line 129 of file bus.h.
Referenced by bus_send_message().
#define BUS_MSG_PREAMBLE 0xFE
The preamble of the BUS message
Definition at line 127 of file bus.h.
Referenced by bus_send_message().
#define BUS_SLOT_DEAD_TIME 130
The dead time of the time slot, in us. This should be set pretty high to accept rather high clock drift There is a dead period both before and after our slot, so total dead time is BUS_SLOT_DEAD_TIME * 2
Definition at line 208 of file bus.h.
Referenced by bus_init().
#define BUS_STATUS_ALLOWED_TO_SEND_BIT 1
This bit shows if it's allowed to send messages on the bus, ie first sync has been received
Definition at line 181 of file bus.h.
#define BUS_STATUS_DEVICE_IS_MASTER_BIT 0
This bit is to set if the device is MASTER in the bus_status.flags variable
Definition at line 179 of file bus.h.
Referenced by bus_is_master(), and bus_set_is_master().
#define BUS_STATUS_FORCE_SYNC 8
This bit is to force a SYNC message to be sent
Definition at line 195 of file bus.h.
Referenced by bus_check_tx_status(), and bus_set_is_master().
#define BUS_STATUS_MASTER_SENT_SYNC_BIT 3
This bit is to set if the MASTER has sent a SYNC message so we are allowed to start sending
Definition at line 185 of file bus.h.
Referenced by bus_allowed_to_send(), and ISR().
#define BUS_STATUS_MESSAGE_ACK_TIMEOUT 9
This bit is to see if a message should be acked or not, used for the timeout of an acknowledge
Definition at line 197 of file bus.h.
Referenced by bus_message_acked(), bus_message_nacked(), bus_send_message(), and ISR().
#define BUS_STATUS_PREAMBLE_FOUND_BIT 2
This bit is set if the preamble is found in the bus_status.flags variable
Definition at line 183 of file bus.h.
#define BUS_STATUS_RECEIVE_ON 7
This bit is to indicate that we are CURRENTLY receiving a message
Definition at line 193 of file bus.h.
Referenced by bus_init(), bus_send_message(), and ISR().
#define BUS_STATUS_SEND_ACTIVE 6
This bit is to indicate that we are CURRENTLY sending a message
Definition at line 191 of file bus.h.
Referenced by bus_send_message(), and ISR().
#define BUS_STATUS_SEND_MESSAGE 5
This bit is to indicate that we should try to send the message currently in the TX queue
Definition at line 189 of file bus.h.
Referenced by bus_check_tx_status(), bus_resend_message(), and bus_reset_tx_status().
#define BUS_STATUS_TIME_SLOT_ACTIVE 4
This bit is to set if the device own time slot is currently active, ie it is possibly allowed to send
Definition at line 187 of file bus.h.
Referenced by bus_check_tx_status(), and ISR().
#define BUS_SYNC_TIMEOUT_LIMIT 3200
This limit is used to detect if it was too long ago since we receieved a SYNC message from the master. If so it will stop with all outgoing communication.
Definition at line 167 of file bus.h.
Referenced by ISR().
#define BUS_TIME_FRAME_LIMIT 520
The time frame size of the bus time slots, in us
Definition at line 205 of file bus.h.
Referenced by bus_init().
#define BUS_TIME_INTERRUPT_INTERVAL 130
The interval of the timer interrupts, in us
Definition at line 203 of file bus.h.
Referenced by bus_init().
#define BUS_TIME_MULTIPLIER 4
This is the multiplier for the send window BUS_TIME_INTERRUPT_INTERVAL * BUS_TIME_MULTIPLIER = BUS_TIME_FRAME_LIMIT
Definition at line 201 of file bus.h.
Referenced by bus_set_device_count(), bus_set_is_master(), and ISR().
#define BUS_TIMEOUT_LIMIT 5
Timeout limit for how long it can take without receiving a message before the buffer is cleared, this is counted as time, 5 would mean 5 * 130 us
Definition at line 175 of file bus.h.
Referenced by ISR().
#define DEF_NR_DEVICES 25
Define the proper interrupt routines depending on hardware.
The default number of devices
Definition at line 121 of file bus.h.
Referenced by bus_ping_get_failed_count(), bus_ping_get_failed_ping(), bus_ping_init(), bus_ping_tick(), and main().
Function Documentation
void bus_add_rx_message (unsigned char from_addr, unsigned char to_addr, unsigned char flags, unsigned char cmd, unsigned char length, unsigned char data[])
Adds a message to the RX queue which will be sent as soon as possible.
Parameters:
from_addr The address of the sender
to_addr The address to the receiever
flags Different flags, see defines
cmd The command performed
length The length of the data received
data The data receieved
Definition at line 324 of file bus.c.
References BUS_MESSAGE::cmd, BUS_MESSAGE::data, BUS_MESSAGE::flags, BUS_MESSAGE::from_addr, BUS_MESSAGE::length, rx_queue_add(), and BUS_MESSAGE::to_addr.
void bus_add_tx_message (unsigned char from_addr, unsigned char to_addr, unsigned char flags, unsigned char cmd, unsigned char length, unsigned char data[])
Adds a message to the TX queue which will be sent as soon as possible.
Parameters:
from_addr The address of the sender
to_addr The address to the receiever
flags Different flags, see defines
cmd The command wanted to be performed
length The length of the data wanting to be sent
data The data wanted to be transmitted to the receiever
Definition at line 291 of file bus.c.
References bus_allowed_to_send(), BUS_CMD_SYNC, BUS_MESSAGE::checksum, BUS_MESSAGE::cmd, BUS_MESSAGE::data, BUS_MESSAGE::flags, BUS_MESSAGE::from_addr, BUS_MESSAGE::length, BUS_MESSAGE::to_addr, and tx_queue_add().
Referenced by antenna_ctrl_deactivate_outputs(), antenna_ctrl_send_ant_data_to_bus(), antenna_ctrl_send_rx_ant_band_data_to_bus(), antenna_ctrl_send_rx_ant_data_to_bus(), band_ctrl_send_band_data_to_bus(), bus_parse_message(), bus_send_ack(), bus_send_nack(), ISR(), main(), send_ping(), and sub_menu_send_data_to_bus().
unsigned char bus_allowed_to_send (void)
Returns if you are allowed to transmit data to the bus or not.
Returns: 1 if it's allowed to transmit and 0 if not
Definition at line 114 of file bus.c.
References BUS_STATUS_MASTER_SENT_SYNC_BIT, and bus_status_struct::flags.
Referenced by bus_add_tx_message(), ISR(), and main().
unsigned char bus_get_address (void)
Returns the address of this device.
Returns: The address of this device
Definition at line 123 of file bus.c.
References bus_status_struct::ext_addr.
Referenced by antenna_ctrl_deactivate_outputs(), antenna_ctrl_send_ant_data_to_bus(), antenna_ctrl_send_rx_ant_band_data_to_bus(), antenna_ctrl_send_rx_ant_data_to_bus(), band_ctrl_send_band_data_to_bus(), bus_parse_message(), ISR(), main(), send_ping(), and sub_menu_send_data_to_bus().
unsigned char bus_get_device_count (void)
Receive the device count on the bus.
Returns: The number of devices on the bus
Definition at line 235 of file bus.c.
References bus_status_struct::device_count.
Referenced by main().
unsigned char bus_is_master (void)
Returns if the bus is set to be master.
Returns: 1 if it is configured to be master, 0 otherwise
Definition at line 196 of file bus.c.
References BUS_STATUS_DEVICE_IS_MASTER_BIT, and bus_status_struct::flags.
Referenced by ISR(), and main().
void bus_message_nacked (unsigned char addr, unsigned char error_type)
The message last sent was NACKED from the receiver.
Parameters:
addr The address of the device that sent the NACK
error_type Contains information why the message was NACKED
Definition at line 348 of file bus.c.
References bus_resend_message(), BUS_STATUS_MESSAGE_ACK_TIMEOUT, bus_status_struct::flags, BUS_MESSAGE::to_addr, and tx_queue_get().
Referenced by bus_parse_message(), and event_bus_parse_message().
void bus_send_nack (unsigned char to_addr, unsigned char error_type)
Send an NOT acknowledge.
Parameters:
to_addr Which address we wish to send the ping to
error_type Why was the message nacked, see bus.h for more information about BUS errors
Definition at line 223 of file bus.c.
References bus_add_tx_message(), BUS_BROADCAST_ADDR, BUS_CMD_NACK, and bus_status_struct::ext_addr.
Referenced by ISR().
void bus_set_address (unsigned char addr)
Set the address of this device on the bus.
Parameters:
addr The address of this device
Definition at line 108 of file bus.c.
References bus_status_struct::ext_addr.
Referenced by main().
void bus_set_device_count (unsigned char device_count)
Set the number of devices that are on the bus.
Parameters:
device_count The number of devices on the bus, ie the number of time slots
Definition at line 241 of file bus.c.
References BUS_TIME_MULTIPLIER, bus_status_struct::device_count, and bus_status_struct::device_count_mult.
void bus_set_is_master (unsigned char state, unsigned char count)
Set the status if the device should be master or not.
Parameters:
state 1 if you wish the device to be master, 0 if you wish that it should be slave
count The nr of devices
Definition at line 206 of file bus.c.
References BUS_STATUS_ALLOWED_TO_SEND_BIT, BUS_STATUS_DEVICE_IS_MASTER_BIT, BUS_STATUS_FORCE_SYNC, BUS_TIME_MULTIPLIER, bus_status_struct::device_count, bus_status_struct::device_count_mult, and bus_status_struct::flags.
Referenced by main().