front_panel/display.h File Reference
The serial interface to configure the device and control it.
#include `glcd.h`
#include `main.h`
Defines
#define CLEAR_ANT_AREA() glcd_clear_area(0,90,0,56)
Macro that clears the antenna area of the LCD.
#define CLEAR_ROTATOR_AREA() glcd_clear_area(90,128,0,56)
Macro that clears the rotator area of the LCD.
#define CLEAR_RADIO_FREQ_AREA() glcd_clear_area(90,128,58,64)
Macro that clears the radio frequency area of the LCD.
#define CLEAR_RX_ANTENNA_AREA() glcd_clear_area(0,90,58,64)
Macro that clears the RX antenna area.
#define CLEAR_SET_ROTATOR_AREA() glcd_clear_area(0,80,58,64)
Macro that clears the rotator area.
#define CLEAR_SET_SUB_MENU_ARRAY_AREA() glcd_clear_area(44,84,35,64)
Macro that clears the sub menu array direction area.
#define DISPLAY_SCREENSAVER_DEF_CONTRAST 20
#define DISPLAY_RADIO_FREQ_X_POS 128
The position of the frequency text X position.
#define DISPLAY_RADIO_FREQ_Y_POS 58
The position of the frequency text Y position.
#define DISPLAY_TEXT_ROTATOR_ANT1_X_POS 128
The position of the antenna1 rotator text X position.
#define DISPLAY_TEXT_ROTATOR_ANT1_Y_POS 1
The position of the antenna1 rotator text Y position.
#define DISPLAY_TEXT_ROTATOR_ANT2_X_POS 128
The position of the antenna2 rotator text X position.
#define DISPLAY_TEXT_ROTATOR_ANT2_Y_POS 16
The position of the antenna2 rotator text Y position.
#define DISPLAY_TEXT_ROTATOR_ANT3_X_POS 128
The position of the antenna3 rotator text X position.
#define DISPLAY_TEXT_ROTATOR_ANT3_Y_POS 29
The position of the antenna3 rotator text Y position.
#define DISPLAY_TEXT_ROTATOR_ANT4_X_POS 128
The position of the antenna4 rotator text X position.
#define DISPLAY_TEXT_ROTATOR_ANT4_Y_POS 43
The position of the antenna4 rotator text Y position.
#define DISPLAY_TEXT_ANT1_X_POS 0
The position of the antenna1 text X position.
#define DISPLAY_TEXT_ANT1_Y_POS 0
The position of the antenna1 text Y position.
#define DISPLAY_TEXT_ANT2_X_POS 0
The position of the antenna2 text X position.
#define DISPLAY_TEXT_ANT2_Y_POS 15
The position of the antenna2 text Y position.
#define DISPLAY_TEXT_ANT3_X_POS 0
The position of the antenna3 text X position.
#define DISPLAY_TEXT_ANT3_Y_POS 28
The position of the antenna3 text Y position.
#define DISPLAY_TEXT_ANT4_X_POS 0
The position of the antenna4 text X position.
#define DISPLAY_TEXT_ANT4_Y_POS 42
The position of the antenna4 text Y position.
#define DISPLAY_TEXT_RX_ANT_X_POS 0
The position of the RX antenna X pos.
#define DISPLAY_TEXT_RX_ANT_Y_POS 58
The position of the RX antenna Y position.
#define DISPLAY_TEXT_ROTATE_ANT_X_POS 0
The position of the SET ROTATE X pos.
#define DISPLAY_TEXT_ROTATE_ANT_Y_POS 58
The position of the SET ROTATE Y position.
#define DISPLAY_TEXT_ANT_HEIGHT 10
The height of the antenna text inverting area.
#define DISPLAY_TEXT_ANTENNA_WIDTH 8
The width of the antenna text.
#define DISPLAY_TEXT_ANTENNA_IN_USE_ADDITION_WIDTH 16
The width addition of the inverted area when an antenna is in use.
Functions
void display_setup_view (void)
Display the setup in progress screen.
void display_shutdown_view (void)
Display the shutdown in progress screen.
void display_antennas (unsigned char band)
Display a set of antennas on the display.
void display_rotator_directions (unsigned char band)
Display the current rotator directions If the rotator option has been enabled for a certain antenna it will be shown it's current direction on the LCD.
void display_radio_freq (unsigned char length, char *freq)
Displays the radios frequency Will display the radios frequency in the bottom right corner of the display.
void display_view (unsigned char mode)
Displays a specified view This is to display lines, icons etc depending on what kind of of `view` you wish to display.
void display_invert_antenna (unsigned char ant_index)
Displays an antenna but inverted.
void display_update_screensaver (void)
Updates the screensaver which consist of a clock.
unsigned char display_screensaver_mode (void)
Get the mode of the screensaver.
void display_set_backlight (unsigned char value)
Set the backlight level of the LCD.
void display_update (unsigned char band, unsigned char antenna)
Updates the display.
void display_show_rx_ant (unsigned char ant_index)
Show the current selected RX ant.
unsigned char display_calculate_width (char *str, unsigned char font, unsigned char length)
Retrieve the width of a string in pixels.
void display_show_set_heading (unsigned int rotator_heading, unsigned char view_360_deg)
Show SET rotator heading.
void display_text_center_adjust (unsigned char y, char *str, unsigned char length, unsigned char font)
Displays a piece of text center adjusted on the display.
void display_update_radio_freq (void)
Update the radio frequency area of the display.
void display_show_sub_menu (unsigned char ant_index, unsigned char sub_menu_type)
Will show the sub menu of a certain antenna.
void display_show_powermeter_bargraph (unsigned int fwd_power, unsigned int ref_power)
Show the power meter bargraphs.
void display_show_powermeter_text (unsigned int fwd_power, unsigned int ref_power, unsigned int vswr)
This function will print out the power meter text which shows FWD, REF power and VSWR.
void display_show_powermeter (void)
This function will show the power meter display.
Detailed Description
The serial interface to configure the device and control it.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/display.h" 
Definition in file display.h.
Function Documentation
void display_antennas (unsigned char band)
Display a set of antennas on the display.
Parameters:
band The band you wish to show the antennas from
Definition at line 149 of file display.c.
References antenna_ctrl_get_antenna_text(), antenna_ctrl_get_antenna_text_length(), antenna_ctrl_get_flags(), ANTENNA_IN_USE_FLAG, CLEAR_ANT_AREA, DISPLAY_TEXT_ANT1_X_POS, DISPLAY_TEXT_ANT1_Y_POS, DISPLAY_TEXT_ANT2_X_POS, DISPLAY_TEXT_ANT2_Y_POS, DISPLAY_TEXT_ANT3_X_POS, DISPLAY_TEXT_ANT3_Y_POS, DISPLAY_TEXT_ANT4_X_POS, and DISPLAY_TEXT_ANT4_Y_POS.
Referenced by display_update().
unsigned char display_calculate_width (char * str, unsigned char font, unsigned char length)
Retrieve the width of a string in pixels.
Parameters:
str The text string you wish to find out the length of
font Which font type the string is
length The length of the string (strlen)
Returns: The actual graphical width of the text string sent in, in pixels
Definition at line 111 of file display.c.
Referenced by display_text_center_adjust(), display_text_right_adjust(), and menu_show_text().
void display_invert_antenna (unsigned char ant_index)
Displays an antenna but inverted.
Parameters:
ant_index Which antenna you wish to invert
Definition at line 241 of file display.c.
References antenna_ctrl_get_antenna_text_length(), antenna_ctrl_get_flags(), ANTENNA_IN_USE_FLAG, DISPLAY_TEXT_ANT1_Y_POS, DISPLAY_TEXT_ANT2_Y_POS, DISPLAY_TEXT_ANT3_Y_POS, DISPLAY_TEXT_ANT4_Y_POS, DISPLAY_TEXT_ANT_HEIGHT, DISPLAY_TEXT_ANTENNA_IN_USE_ADDITION_WIDTH, and DISPLAY_TEXT_ANTENNA_WIDTH.
Referenced by display_update().
void display_radio_freq (unsigned char length, char * freq)
Displays the radios frequency Will display the radios frequency in the bottom right corner of the display.
Parameters:
freq the frequency you want to display
Definition at line 286 of file display.c.
References CLEAR_RADIO_FREQ_AREA, DISPLAY_RADIO_FREQ_X_POS, DISPLAY_RADIO_FREQ_Y_POS, and display_text_right_adjust().
Referenced by display_update_radio_freq().
void display_rotator_directions (unsigned char band)
Display the current rotator directions If the rotator option has been enabled for a certain antenna it will be shown it's current direction on the LCD.
Parameters:
band The band you wish to show the rotators direction
Definition at line 192 of file display.c.
References antenna_ctrl_get_direction(), antenna_ctrl_get_flags(), antenna_ctrl_get_sub_menu_type(), ANTENNA_ROTATOR_FLAG, CLEAR_ROTATOR_AREA, display_text_right_adjust(), DISPLAY_TEXT_ROTATOR_ANT1_X_POS, DISPLAY_TEXT_ROTATOR_ANT1_Y_POS, DISPLAY_TEXT_ROTATOR_ANT2_X_POS, DISPLAY_TEXT_ROTATOR_ANT2_Y_POS, DISPLAY_TEXT_ROTATOR_ANT3_X_POS, DISPLAY_TEXT_ROTATOR_ANT3_Y_POS, DISPLAY_TEXT_ROTATOR_ANT4_X_POS, DISPLAY_TEXT_ROTATOR_ANT4_Y_POS, sub_menu_get_current_pos(), sub_menu_get_text(), and SUBMENU_VERT_ARRAY.
Referenced by display_update().
unsigned char display_screensaver_mode (void)
Get the mode of the screensaver.
Returns: 0 if the screensaver is disabled, 1 otherwise
Definition at line 69 of file display.c.
References screensaver_mode.
void display_set_backlight (unsigned char value)
Set the backlight level of the LCD.
Parameters:
value What we wish to set the backlight level to to, 0-100%
Definition at line 97 of file display.c.
Referenced by main(), and menu_action().
void display_show_powermeter_bargraph (unsigned int fwd_power, unsigned int ref_power)
Show the power meter bargraphs.
Parameters:
fwd_power The forward power in percent
ref_power The reflected power in percent
Definition at line 524 of file display.c.
References display_show_bargraph_fwd(), and display_show_bargraph_ref().
void display_show_powermeter_text (unsigned int fwd_power, unsigned int ref_power, unsigned int vswr)
This function will print out the power meter text which shows FWD, REF power and VSWR.
Parameters:
fwd_power Forward power in watts
ref_power Reflected power in watts
vswr The current VSWR, for example 151 means 1.51:1
Definition at line 533 of file display.c.
References display_text_right_adjust().
void display_show_rx_ant (unsigned char ant_index)
Show the current selected RX ant.
Parameters:
ant_index The antenna index of which antenna that is selected and should be shown
Definition at line 304 of file display.c.
References antenna_ctrl_get_rx_antenna_count(), antenna_ctrl_get_rx_antenna_name(), CLEAR_RX_ANTENNA_AREA, struct_status::current_display_level, DISPLAY_LEVEL_BAND, DISPLAY_TEXT_RX_ANT_X_POS, DISPLAY_TEXT_RX_ANT_Y_POS, display_view(), status, and VIEW_ANTENNAS.
Referenced by event_update_display().
void display_show_set_heading (unsigned int rotator_heading, unsigned char view_360_deg)
Show SET rotator heading.
Parameters:
rotator_heading The current set rotator heading
view_360_deg The status of the view_360_deg option
Definition at line 326 of file display.c.
References struct_status::current_display_level, DISPLAY_LEVEL_BAND, display_text_center_adjust(), and status.
Referenced by event_pulse_sensor_down(), event_pulse_sensor_up(), event_rotate_button_pressed(), event_tx_button1_pressed(), event_tx_button2_pressed(), event_tx_button3_pressed(), and event_tx_button4_pressed().
void display_show_sub_menu (unsigned char ant_index, unsigned char sub_menu_type)
Will show the sub menu of a certain antenna.
Parameters:
ant_index The antenna index (0-3)
sub_menu_type Which type of sub menu it is
Definition at line 438 of file display.c.
References antenna_ctrl_get_antenna_text(), CLEAR_SET_SUB_MENU_ARRAY_AREA, struct_status::current_display_level, DISPLAY_LEVEL_SUBMENU, display_text_center_adjust(), status, sub_menu_get_current_pos(), sub_menu_get_text(), and SUBMENU_VERT_ARRAY.
Referenced by event_pulse_sensor_down(), event_pulse_sensor_up(), and event_sub_button_pressed().
void display_text_center_adjust (unsigned char y, char * str, unsigned char length, unsigned char font)
Displays a piece of text center adjusted on the display.
Parameters:
y Where the text should be located in y-axis (pixels)
str The string we wish to center adjust to the display
length The length of the string (strlen)
font Which font you wish to show the string with
Definition at line 132 of file display.c.
References display_calculate_width().
Referenced by display_setup_view(), display_show_set_heading(), display_show_sub_menu(), and display_shutdown_view().
void display_update (unsigned char band, unsigned char antenna)
Updates the display.
Parameters:
band Which band to show the antenna information from
antenna The antenna combination that is currently selected
Definition at line 358 of file display.c.
References struct_status::current_display_level, display_antennas(), display_invert_antenna(), DISPLAY_LEVEL_BAND, display_rotator_directions(), display_update_radio_freq(), display_view(), status, and VIEW_ANTENNAS.
Referenced by event_tx_button1_pressed(), event_tx_button2_pressed(), event_tx_button3_pressed(), event_tx_button4_pressed(), and event_update_display().
void display_view (unsigned char mode)
Displays a specified view This is to display lines, icons etc depending on what kind of of `view` you wish to display.
Parameters:
mode Which view mode you wish to display
Definition at line 296 of file display.c.
References glcd_line(), and VIEW_ANTENNAS.
Referenced by display_show_rx_ant(), display_update(), and display_update_radio_freq().