driver_unit_v2/main.c File Reference
Main file of the driver unit.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include `main.h`
#include `board.h`
#include `init.h`
#include `../i2c.h`
#include `../delay.h`
#include `../wmv_bus/bus.h`
#include `../wmv_bus/bus_ping.h`
#include `../wmv_bus/bus_rx_queue.h`
#include `../wmv_bus/bus_tx_queue.h`
#include `../wmv_bus/bus_commands.h`
Defines
#define LM76_ADDR 0x90
The address of the LM76 temperature sensor connected to the I2C bus.
Functions
void activate_output (unsigned char from_addr, unsigned char index, unsigned char type)
Activate a driver output This function is used to activate an output on the driver unit. It will remember which device that sent the request for an activation so that the driver_unit will remember it when that device goes offline so it can shut the outputs off.
void deactivate_output (unsigned char from_addr, unsigned char index)
Deactivate a driver output This function is used to deactivate an output on the driver unit. It will remember which device that sent the request for an deactivation so that the driver_unit will remember it when that device goes offline so it can shut the outputs off.
unsigned int lm76_get_temp (void)
Retrieve the temperature from the LM76 sensor This function is used to retrieve the temperature from the LM76 sensor that does exist on the driver_unit.
void bus_parse_message (void)
Parse a message and exectute the proper commands This function is used to parse a message that was receieved on the bus that is located in the RX queue.
unsigned char read_ext_addr (void)
Read the external DIP-switch. This function is used to read the external offset address on the driver_unit.
void set_ptt_led_status (unsigned char state)
Set the PTT led status.
unsigned char get_ptt_status (void)
Check the status of the external PTT lines.
int main (void)
ISR (SIG_OUTPUT_COMPARE0)
Output compare 0 interrupt - `called` with 1ms intervals.
Variables
unsigned char device_id
Contains info if the module is a positive or negative driver.
driver_status_struct driver_status
A status structure of the driver unit outputs.
unsigned int counter_compare0 = 0
Counter to keep track of the numbers of ticks from timer0.
unsigned int counter_sync = 0
Counter to keep track of the time elapsed since the last sync message was sent.
unsigned int counter_ping_interval = 0
Counter to keep track of when to send a ping out on the bus.
unsigned char check_ptt_status = 0
Flag which is set when we wish to poll the PTT status.
Detailed Description
Main file of the driver unit.
Author: Mikael Larsmark, SM2WMV
Date: 2009-03-16
 #include "driver_unit_v2/main.c" 
Definition in file main.c.
Function Documentation
void activate_output (unsigned char from_addr, unsigned char index, unsigned char type)
Activate a driver output This function is used to activate an output on the driver unit. It will remember which device that sent the request for an activation so that the driver_unit will remember it when that device goes offline so it can shut the outputs off.
Parameters:
from_addr The device that sent the request of activating an output
index The index of which output to activate
type The type of output this is, usually is the bus command
Definition at line 67 of file main.c.
References driver_status_struct::driver_output_owner, driver_status_struct::driver_output_state, and driver_status_struct::driver_output_type.
void deactivate_output (unsigned char from_addr, unsigned char index)
Deactivate a driver output This function is used to deactivate an output on the driver unit. It will remember which device that sent the request for an deactivation so that the driver_unit will remember it when that device goes offline so it can shut the outputs off.
Parameters:
from_addr The device that sent the request of deactivating the output
index The index of which output to deactivate
Definition at line 125 of file main.c.
References driver_status_struct::driver_output_owner, driver_status_struct::driver_output_state, and driver_status_struct::driver_output_type.
unsigned char get_ptt_status (void)
Check the status of the external PTT lines.
Returns: A byte which contains info of the state of the PTT lines. 0 = R1, 1 = R2 etc
Definition at line 364 of file main.c.
References status.
Referenced by main().
unsigned int lm76_get_temp (void)
Retrieve the temperature from the LM76 sensor This function is used to retrieve the temperature from the LM76 sensor that does exist on the driver_unit.
Returns: The temperature but not in float format
Definition at line 180 of file main.c.
References i2cMasterReceiveNI(), and LM76_ADDR.
int main (void)
Main function of the driver unit
Definition at line 380 of file main.c.
References bus_add_tx_message(), bus_allowed_to_send(), BUS_BROADCAST_ADDR, bus_check_tx_status(), BUS_CMD_PING, BUS_CMD_SYNC, BUS_DEVICE_STATUS_MESSAGE_INTERVAL, bus_get_address(), bus_get_device_count(), bus_init(), bus_is_master(), BUS_MASTER_SYNC_INTERVAL, bus_parse_message(), bus_set_address(), bus_set_is_master(), check_ptt_status, counter_ping_interval, counter_sync, deactivate_output(), DEF_NR_DEVICES, device_count, device_id, DEVICE_ID_DRIVER_NEG, DEVICE_ID_DRIVER_POS, driver_status_struct::driver_output_state, get_ptt_status(), init_ports(), init_timer_0(), init_timer_2(), read_ext_addr(), rx_queue_is_empty(), set_ptt_led_status(), and tx_queue_is_empty().
unsigned char read_ext_addr (void)
Read the external DIP-switch. This function is used to read the external offset address on the driver_unit.
Returns: The address of the external DIP-switch
Definition at line 352 of file main.c.