driver_unit/init.c File Reference
Initialization routines for the driver unit.
#include <stdio.h>
#include <avr/io.h>
#include <avr/interrupt.h>
Defines
#define OCR0_1MS 14
Used for timer compare to match 1 ms.
Functions
void init_timer_0 (void)
void init_timer_2 (void)
void init_ports (void)
Detailed Description
Initialization routines for the driver unit.
Author: Mikael Larsmark, SM2WMV
Date: 2009-03-16
 #include "driver_unit/init.c" 
Definition in file init.c.
Function Documentation
void init_ports (void)
Set the direction of the ports
Definition at line 56 of file init.c.
Referenced by main().
void init_timer_0 (void)
Initialize timer0 to use the main crystal clock and the output compare interrupt feature to generate an interrupt approximately once per millisecond to use as a general purpose time base.
Definition at line 35 of file init.c.
Referenced by main().
void init_timer_2 (void)
Initializes timer 2, used for the communication bus and the interrupt is caught in bus.c
Definition at line 45 of file init.c.
Referenced by main().