front_panel/ds1307.h File Reference
Realtime clock.
Defines
#define DS1307_ADDR 0x68
The external I2C address of the DS1307 realtime clock.
Functions
void ds1307_init (void)
Initialize the realtime clock on the front panel.
void ds1307_read (void)
Read the current time/date from the realtime clock. Stores the data and can be retrieved with the get functions in this file.
unsigned char ds1307_get_seconds (void)
Retrieve the seconds part of the time from the realtime clock.
unsigned char ds1307_get_minutes (void)
Retrieve the minute part of the time from the realtime clock.
unsigned char ds1307_get_hours (void)
Retrieve the hour part of the time from the realtime clock.
void ds1307_set_time (char *data)
Set the current time of the realtime clock.
Detailed Description
Realtime clock.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/ds1307.h" 
Definition in file ds1307.h.
Function Documentation
unsigned char ds1307_get_hours (void)
Retrieve the hour part of the time from the realtime clock.
Returns: The current hour
Definition at line 85 of file ds1307.c.
Referenced by display_update_screensaver().
unsigned char ds1307_get_minutes (void)
Retrieve the minute part of the time from the realtime clock.
Returns: The current minute
Definition at line 93 of file ds1307.c.
Referenced by display_update_screensaver().
unsigned char ds1307_get_seconds (void)
Retrieve the seconds part of the time from the realtime clock.
Returns: The current seconds
Definition at line 101 of file ds1307.c.
Referenced by display_update_screensaver().
void ds1307_set_time (char * data)
Set the current time of the realtime clock.
Parameters:
data data[0] = seconds, data[1] = minutes, data[2] = hours, data[3] = Day, data[4] = Date, data[5] = month, data[6] = year
Definition at line 62 of file ds1307.c.
Referenced by computer_interface_parse_data().