front_panel/ds1307.c File Reference
Main file of the front panel.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include `ds1307.h`
#include `../i2c.h`
#include `../delay.h`
Functions
void ds1307_init (void)
Initialize the realtime clock on the front panel.
void ds1307_set_time (char *data)
Set the current time of the realtime clock.
unsigned char ds1307_get_hours (void)
Retrieve the hour part of the time from the realtime clock.
unsigned char ds1307_get_minutes (void)
Retrieve the minute part of the time from the realtime clock.
unsigned char ds1307_get_seconds (void)
Retrieve the seconds part of the time from the realtime clock.
void ds1307_read (void)
Read the current time/date from the realtime clock. Stores the data and can be retrieved with the get functions in this file.
Variables
unsigned char allowed_to_read = 0
Flag which is set to 1 if a read request is allowed to the ds1307.
unsigned char * time_data
Variable which contains information of the current time/date.
Detailed Description
Main file of the front panel.
Realtime clock.
Author: Mikael Larsmark, SM2WMV
Date: 2008-04-30 /*!
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/ds1307.c" 
Definition in file ds1307.c.
Function Documentation
unsigned char ds1307_get_hours (void)
Retrieve the hour part of the time from the realtime clock.
Returns: The current hour
Definition at line 85 of file ds1307.c.
Referenced by display_update_screensaver().
unsigned char ds1307_get_minutes (void)
Retrieve the minute part of the time from the realtime clock.
Returns: The current minute
Definition at line 93 of file ds1307.c.
Referenced by display_update_screensaver().
unsigned char ds1307_get_seconds (void)
Retrieve the seconds part of the time from the realtime clock.
Returns: The current seconds
Definition at line 101 of file ds1307.c.
Referenced by display_update_screensaver().
void ds1307_set_time (char * data)
Set the current time of the realtime clock.
Parameters:
data data[0] = seconds, data[1] = minutes, data[2] = hours, data[3] = Day, data[4] = Date, data[5] = month, data[6] = year
Definition at line 62 of file ds1307.c.
Referenced by computer_interface_parse_data().