front_panel/eeprom_m24.c File Reference
EEPROM hardware functions.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <string.h>
#include <avr/interrupt.h>
#include `eeprom_m24.h`
#include `../i2c.h`
#include `../i2cconf.h`
Functions
void __inline__ eeprom_tiny_delay (void)
unsigned char eeprom_m24_write_byte (unsigned int eeprom_address, unsigned char value)
Write a byte of data to the EEPROM.
unsigned char eeprom_m24_read_byte (unsigned int eeprom_address)
Read a byte of data from the EEPROM.
unsigned char eeprom_m24_write_block (unsigned int start_address, unsigned int length, unsigned char *data)
Write a block of data to the EEPROM.
unsigned char eeprom_m24_read_block (unsigned int start_address, unsigned int length, unsigned char *data)
Read a block of data from the EEPROM - NOT FINISHED!!
Detailed Description
EEPROM hardware functions.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/eeprom_m24.c" 
Definition in file eeprom_m24.c.
Function Documentation
unsigned char eeprom_m24_read_block (unsigned int start_address, unsigned int length, unsigned char * data)
Read a block of data from the EEPROM - NOT FINISHED!!
Parameters:
start_address The start address of where we wish to read the data from
length The length of the data we wish read
data The memory area we wish to store the data to
Definition at line 215 of file eeprom_m24.c.
References EEPROM_M24_ADDR, i2cGetReceivedByte(), i2cReceiveByte(), i2cSendByte(), i2cSendStart(), i2cSendStop(), and i2cWaitForComplete().
unsigned char eeprom_m24_read_byte (unsigned int eeprom_address)
Read a byte of data from the EEPROM.
Parameters:
eeprom_address The address where we wish to read the byte from
Returns: The value at eeprom_address
Definition at line 96 of file eeprom_m24.c.
References EEPROM_M24_ADDR, i2cGetReceivedByte(), i2cReceiveByte(), i2cSendByte(), i2cSendStart(), i2cSendStop(), and i2cWaitForComplete().
Referenced by eeprom_get_ant_sub_menu_array_structure(), eeprom_get_antenna_data(), eeprom_get_band_data(), eeprom_get_ptt_data(), eeprom_get_radio_settings_structure(), eeprom_get_runtime_settings(), eeprom_get_rx_antenna_data(), eeprom_get_settings_structure(), and eeprom_read_table().
unsigned char eeprom_m24_write_block (unsigned int start_address, unsigned int length, unsigned char * data)
Write a block of data to the EEPROM.
Parameters:
start_address The start address of where we wish to store the data
length The length of the data we wish to store
data The content we wish to write to the EEPROM
Definition at line 146 of file eeprom_m24.c.
References EEPROM_M24_ADDR, eeprom_tiny_delay(), i2cSendByte(), i2cSendStart(), i2cSendStop(), and i2cWaitForComplete().
Referenced by eeprom_create_table(), eeprom_save_ant_structure(), eeprom_save_ant_sub_menu_array_structure(), eeprom_save_band_data(), eeprom_save_ptt_data(), eeprom_save_radio_settings_structure(), eeprom_save_runtime_settings(), eeprom_save_rx_ant_structure(), and eeprom_save_settings_structure().
unsigned char eeprom_m24_write_byte (unsigned int eeprom_address, unsigned char value)
Write a byte of data to the EEPROM.
Parameters:
eeprom_address The address where we wish to store the byte
value The value we wish to store at eeprom_address
Definition at line 43 of file eeprom_m24.c.
References EEPROM_M24_ADDR, i2cSendByte(), i2cSendStart(), i2cSendStop(), and i2cWaitForComplete().
void __inline__ eeprom_tiny_delay (void)
Just a tiny delay
Definition at line 35 of file eeprom_m24.c.
Referenced by eeprom_m24_write_block().