front_panel/eeprom.c File Reference
EEPROM functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <avr/io.h>
#include <avr/eeprom.h>
#include `eeprom_m24.h`
#include `eeprom.h`
#include `../global.h`
#include `antenna_ctrl.h`
#include `band_ctrl.h`
#include `main.h`
#include `radio_interface.h`
Functions
unsigned char eeprom_read_startup_byte (void)
void eeprom_write_startup_byte (unsigned char val)
This function will write a byte in the EEPROM so we can keep track of if the unit has ever been started.
void eeprom_print (void)
Temporary crap for debug */.
void eeprom_read_table (void)
Read the map of the EEPROM.
void eeprom_get_antenna_data (struct_antenna *data, unsigned char band)
Returns the antenna struct for a specific band.
void eeprom_get_rx_antenna_data (struct_rx_antennas *data)
Returns the rx antenna data.
void eeprom_get_band_data (unsigned char band, struct_band *data)
Returns the band data.
void eeprom_get_radio_settings_structure (struct_radio_settings *data)
get the radio settings from the eeprom
void eeprom_get_settings_structure (struct_setting *data)
get the settings from the eeprom
void eeprom_create_table (void)
Creates the eeprom table which is a map over the eeprom data.
void eeprom_save_runtime_settings (struct_runtime_settings *content)
Save the runtime_settings structure to the eeprom.
void eeprom_get_ptt_data (struct_ptt *data)
Get the ptt structure from the EEPROM.
void eeprom_get_runtime_settings (struct_runtime_settings *data)
Get the runtime_settings structure from the EEPROM.
void eeprom_get_ant_sub_menu_array_structure (unsigned char band_index, unsigned char ant_index, struct_sub_menu_array *data)
Get the struct_sub_menu_array structure from the EEPROM.
void eeprom_save_ant_structure (unsigned char band_index, struct_antenna *content)
Save the antenna structure to the eeprom.
void eeprom_save_rx_ant_structure (struct_rx_antennas *data)
Save the rx antenna structure to the eeprom.
void eeprom_save_settings_structure (struct_setting *data)
Save the device settings to the eeprom.
void eeprom_save_radio_settings_structure (struct_radio_settings *data)
Save the radio settings to the eeprom.
void eeprom_save_band_data (unsigned char band, struct_band *data)
Save the band data to the eeprom.
void eeprom_save_ptt_data (struct_ptt *data)
Save the band data to the eeprom.
void eeprom_save_ant_sub_menu_array_structure (unsigned char band_index, unsigned char ant_index, struct_sub_menu_array *data)
Save the sub menu array data to the EEPROM.
Variables
struct_eeprom_table eeprom_table
EEPROM table which is a description of the location of different structures in the eeprom.
Detailed Description
EEPROM functions.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/eeprom.c" 
Definition in file eeprom.c.
Function Documentation
void eeprom_get_ant_sub_menu_array_structure (unsigned char band_index, unsigned char ant_index, struct_sub_menu_array * data)
Get the struct_sub_menu_array structure from the EEPROM.
Parameters:
band_index Which band we wish to retrieve the sub menu from
ant_index Which antenna we wish to get the sub menu from
data Pointer to where we wish to store the data
Definition at line 205 of file eeprom.c.
References struct_eeprom_table::antenna1_sub_menu, struct_eeprom_table::antenna2_sub_menu, struct_eeprom_table::antenna3_sub_menu, struct_eeprom_table::antenna4_sub_menu, and eeprom_m24_read_byte().
Referenced by sub_menu_load().
void eeprom_get_antenna_data (struct_antenna * data, unsigned char band)
Returns the antenna struct for a specific band.
Parameters:
data Where the data should be saved
band Which band you wish to get the pointer
Definition at line 77 of file eeprom.c.
References struct_eeprom_table::antenna, and eeprom_m24_read_byte().
Referenced by antenna_ctrl_ant_read_eeprom().
void eeprom_get_band_data (unsigned char band, struct_band * data)
Returns the band data.
Parameters:
band Which band we wish to retrieve the data from
data Where the data should be saved
Definition at line 98 of file eeprom.c.
References struct_eeprom_table::band, and eeprom_m24_read_byte().
Referenced by band_ctrl_load_band(), and band_ctrl_load_band_limits().
void eeprom_get_ptt_data (struct_ptt * data)
Get the ptt structure from the EEPROM.
Parameters:
data A pointer where to store the data
Definition at line 183 of file eeprom.c.
References eeprom_m24_read_byte(), and struct_eeprom_table::struct_ptt.
Referenced by sequencer_load_eeprom().
void eeprom_get_radio_settings_structure (struct_radio_settings * data)
get the radio settings from the eeprom
Parameters:
data Where the data should be saved
Definition at line 108 of file eeprom.c.
References eeprom_m24_read_byte(), and struct_eeprom_table::radio_settings.
Referenced by radio_interface_load_eeprom().
void eeprom_get_runtime_settings (struct_runtime_settings * data)
Get the runtime_settings structure from the EEPROM.
Parameters:
data A pointer where to store the data
Definition at line 193 of file eeprom.c.
References eeprom_m24_read_byte(), and struct_eeprom_table::runtime_settings.
Referenced by load_settings().
void eeprom_get_rx_antenna_data (struct_rx_antennas * data)
Returns the rx antenna data.
Parameters:
data Where the data should be saved
Definition at line 87 of file eeprom.c.
References eeprom_m24_read_byte(), and struct_eeprom_table::rx_antennas.
Referenced by antenna_ctrl_rx_ant_read_eeprom().
void eeprom_get_settings_structure (struct_setting * data)
get the settings from the eeprom
Parameters:
data Where the data should be saved
Definition at line 118 of file eeprom.c.
References eeprom_m24_read_byte(), and struct_eeprom_table::settings.
Referenced by load_settings().
unsigned char eeprom_read_startup_byte (void)
Will read the startup byte from the EEPROM, which does indicate if the unit has been started before or not
Returns: The status of the startup byte
Definition at line 45 of file eeprom.c.
References EEPROM_STARTUP_BYTE_ADDR.
Referenced by main().
void eeprom_save_ant_structure (unsigned char band_index, struct_antenna * content)
Save the antenna structure to the eeprom.
Parameters:
band_index Which band it is
content The data to be saved
Definition at line 230 of file eeprom.c.
References struct_eeprom_table::antenna, and eeprom_m24_write_block().
Referenced by computer_interface_parse_data().
void eeprom_save_ant_sub_menu_array_structure (unsigned char band_index, unsigned char ant_index, struct_sub_menu_array * data)
Save the sub menu array data to the EEPROM.
Parameters:
band_index The band we wish to save the settings for
ant_index The antenna index of the data
data The data to save to the EEPROM
Definition at line 269 of file eeprom.c.
References struct_eeprom_table::antenna1_sub_menu, struct_eeprom_table::antenna2_sub_menu, struct_eeprom_table::antenna3_sub_menu, struct_eeprom_table::antenna4_sub_menu, and eeprom_m24_write_block().
Referenced by computer_interface_parse_data().
void eeprom_save_band_data (unsigned char band, struct_band * data)
Save the band data to the eeprom.
Parameters:
band Which band we wish to save the data to
data The data to save to the EEPROM
Definition at line 255 of file eeprom.c.
References struct_eeprom_table::band, and eeprom_m24_write_block().
Referenced by computer_interface_parse_data().
void eeprom_save_ptt_data (struct_ptt * data)
Save the band data to the eeprom.
Parameters:
data The data to save to the EEPROM
Definition at line 261 of file eeprom.c.
References eeprom_m24_write_block(), and struct_eeprom_table::struct_ptt.
Referenced by computer_interface_parse_data().
void eeprom_save_radio_settings_structure (struct_radio_settings * data)
Save the radio settings to the eeprom.
Parameters:
data The data to save to the EEPROM
Definition at line 248 of file eeprom.c.
References eeprom_m24_write_block(), and struct_eeprom_table::radio_settings.
Referenced by computer_interface_parse_data().
void eeprom_save_runtime_settings (struct_runtime_settings * content)
Save the runtime_settings structure to the eeprom.
Parameters:
content The data to be saved
Definition at line 177 of file eeprom.c.
References eeprom_m24_write_block(), and struct_eeprom_table::runtime_settings.
Referenced by main(), and main_save_settings().
void eeprom_save_rx_ant_structure (struct_rx_antennas * data)
Save the rx antenna structure to the eeprom.
Parameters:
data The data to save to the EEPROM
Definition at line 236 of file eeprom.c.
References eeprom_m24_write_block(), and struct_eeprom_table::rx_antennas.
Referenced by computer_interface_parse_data().
void eeprom_save_settings_structure (struct_setting * data)
Save the device settings to the eeprom.
Parameters:
data The data to save to the EEPROM
Definition at line 242 of file eeprom.c.
References eeprom_m24_write_block(), and struct_eeprom_table::settings.
Referenced by computer_interface_parse_data().
void eeprom_write_startup_byte (unsigned char val)
This function will write a byte in the EEPROM so we can keep track of if the unit has ever been started.
Parameters:
val What value we wish to write to the EEPROM
Definition at line 51 of file eeprom.c.
References EEPROM_STARTUP_BYTE_ADDR.
Referenced by main().