front_panel/event_handler.c File Reference
Event handler of various things.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <string.h>
#include `event_handler.h`
#include `main.h`
#include `board.h`
#include `display.h`
#include `glcd.h`
#include `led_control.h`
#include `../delay.h`
#include `../i2c.h`
#include `../global.h`
#include `band_ctrl.h`
#include `antenna_ctrl.h`
#include `remote_control.h`
#include `eeprom_m24.h`
#include `rotary_encoder.h`
#include `menu.h`
#include `radio_interface.h`
#include `sequencer.h`
#include `interrupt_handler.h`
#include `../internal_comm.h`
#include `errors.h`
#include `sub_menu.h`
Functions
void event_set_error (unsigned char error_type, unsigned char state)
Set that an error has occured.
unsigned char event_get_errors (void)
Retrieve the state error flags.
unsigned char event_get_error_state (unsigned char error_type)
Retrieve the state of a specific error type.
void event_internal_comm_parse_message (UC_MESSAGE message)
Function which will parse the internal communication message.
void __inline__ event_set_rx_antenna (unsigned char ant_index)
Set an RX antenna. Will set the proper flags and call the antenna_ctrl_change_rx_ant function.
void event_handler_process_ps2 (unsigned char key_code)
Process an PS2 event.
void event_pulse_sensor_up (void)
The pulse sensor was turned up.
void event_pulse_sensor_down (void)
The pulse sensor was turned down.
void event_update_display (void)
Function to be called if we wish to update the display.
void event_poll_buttons (void)
Function which will poll all buttons and perform the proper action depending on their state.
void event_poll_ext_device (void)
Function which will poll the external devices and perform the proper actions depending on their state.
void event_tx_button1_pressed (void)
Perform the action of TX antenna button 1 if it was pressed.
void event_tx_button2_pressed (void)
Perform the action of TX antenna button 2 if it was pressed.
void event_tx_button3_pressed (void)
Perform the action of TX antenna button 3 if it was pressed.
void event_tx_button4_pressed (void)
Perform the action of TX antenna button 4 if it was pressed.
void event_aux2_button_pressed (void)
Perform the actions that should be done when AUX 2 button is pressed.
void event_sub_button_pressed (void)
Perform the actions that should be done when the SUB menu button is pressed.
void event_rxant_button_pressed (void)
Perform the action of RX antenna button if it was pressed.
void event_rotate_button_pressed (void)
Perform the action of Rotate button if it was pressed.
void event_bus_parse_message (void)
Parse a message from the communication bus.
void event_parse_ext_event (unsigned int ext_event_status)
Parse an external event and perform the proper action.
Variables
x unsigned int main_flags
Different flags, description is found in main.h.
unsigned int flag_errors = 0
Contains the errors which are set.
Detailed Description
Event handler of various things.
'
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/event_handler.c" 
Definition in file event_handler.c.
Function Documentation
unsigned char event_get_error_state (unsigned char error_type)
Retrieve the state of a specific error type.
Parameters:
error_type Which kind of error we wish to check the state for
Returns: The current state of this error
Definition at line 82 of file event_handler.c.
References flag_errors.
void event_handler_process_ps2 (unsigned char key_code)
Process an PS2 event.
Parameters:
key_code The key that was pressed
Definition at line 149 of file event_handler.c.
References event_rxant_button_pressed(), event_set_rx_antenna(), event_tx_button1_pressed(), event_tx_button2_pressed(), event_tx_button3_pressed(), event_tx_button4_pressed(), EXT_CTRL_SEL_NONE, EXT_CTRL_SEL_RX_ANT1, EXT_CTRL_SEL_RX_ANT10, EXT_CTRL_TOGGLE_RX_ANT_MODE, EXT_CTRL_TOGGLE_TX_ANT1, EXT_CTRL_TOGGLE_TX_ANT2, EXT_CTRL_TOGGLE_TX_ANT3, EXT_CTRL_TOGGLE_TX_ANT4, ext_key_get_assignment(), KEYPAD_BTN_0, KEYPAD_BTN_1, KEYPAD_BTN_2, KEYPAD_BTN_3, KEYPAD_BTN_4, KEYPAD_BTN_5, KEYPAD_BTN_6, KEYPAD_BTN_7, KEYPAD_BTN_8, KEYPAD_BTN_9, KEYPAD_BTN_A, KEYPAD_BTN_B, KEYPAD_BTN_C, KEYPAD_BTN_D, KEYPAD_BTN_E, KEYPAD_BTN_F, and KEYPAD_BTN_G.
Referenced by event_internal_comm_parse_message().
void event_internal_comm_parse_message (UC_MESSAGE message)
Function which will parse the internal communication message.
Parameters:
message The message that we wish to parse
Definition at line 91 of file event_handler.c.
References band_ctrl_change_band(), UC_MESSAGE::cmd, computer_interface_is_active(), struct_status::current_display, CURRENT_DISPLAY_SHUTDOWN_VIEW, UC_MESSAGE::data, display_shutdown_view(), event_add_message(), event_handler_process_ps2(), INT_COMM_GET_BAND_BCD_STATUS, INT_COMM_PC_CTRL, INT_COMM_PS2_KEYPRESSED, INT_COMM_TURN_DEVICE_OFF, main_save_settings(), radio_get_current_band(), radio_set_current_band(), remote_control_parse_command(), send_ping(), shutdown_device(), and status.
Referenced by main().
void event_parse_ext_event (unsigned int ext_event_status)
Parse an external event and perform the proper action.
Parameters:
ext_event_status The status of the external `hardware` event flags
Definition at line 900 of file event_handler.c.
References struct_status::ext_devices_current_state, sequencer_computer_rts_activated(), sequencer_computer_rts_deactivated(), sequencer_footsw_pressed(), sequencer_footsw_released(), sequencer_get_radio_sense(), sequencer_get_rts_polarity(), sequencer_get_sense_polarity(), sequencer_radio_sense_activated(), sequencer_radio_sense_deactivated(), status, STATUS_FOOTSWITCH_BIT, STATUS_RADIO_SENSE1_BIT, STATUS_RADIO_SENSE2_BIT, and STATUS_USB2_RTS_BIT.
Referenced by event_poll_ext_device().
void event_set_error (unsigned char error_type, unsigned char state)
Set that an error has occured.
Parameters:
error_type The type of error that has occured, defines can be found in errors.h
state State of the error
Definition at line 65 of file event_handler.c.
References flag_errors, and main_update_ptt_status().
Referenced by bus_resend_message(), internal_comm_resend(), ISR(), menu_action(), rx_queue_add(), and tx_queue_add().
void __inline__ event_set_rx_antenna (unsigned char ant_index)
Set an RX antenna. Will set the proper flags and call the antenna_ctrl_change_rx_ant function.
Parameters:
ant_index The index of the RX antenna we wish to chose
Definition at line 140 of file event_handler.c.
References antenna_ctrl_change_rx_ant(), FLAG_UPDATE_DISPLAY, main_flags, struct_status::selected_rx_antenna, and status.
Referenced by event_handler_process_ps2().