front_panel/computer_interface.h File Reference
Interface towards the computer.
Functions
void computer_interface_init (void)
Initialize the communication interface towards the computer. Will initialize buffers etc.
void computer_interface_send_data (void)
Function which will send data from the tx_buffer to the uart.
void computer_interface_parse_data (void)
Function which will parse the data in the rx_buffer and process the command.
void computer_interface_activate_setup (void)
Activate the setup mode of the device. Will mainly just create various buffers needed to store settings.
void computer_interface_deactivate_setup (void)
Function which will deactivate the computer setup mode, this will clear up memory space of the allocated buffers in the computer_interface_activate_setup() function.
unsigned char computer_interface_is_active (void)
Retrieve the status if the computer interface is active.
Detailed Description
Interface towards the computer.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/computer_interface.h" 
Definition in file computer_interface.h.
Function Documentation
unsigned char computer_interface_is_active (void)
Retrieve the status if the computer interface is active.
Returns: 1 if it is active, 0 otherwise
Definition at line 686 of file computer_interface.c.
References COMPUTER_COMM_FLAG_SETUP_MODE, and computer_comm_struct::flags.
Referenced by event_internal_comm_parse_message(), ISR(), and main().
void computer_interface_parse_data (void)
Function which will parse the data in the rx_buffer and process the command.
Bit 0 = Footswitch Bit 1 = Radio sense lower floor Bit 2 = Radio sense upper floor Bit 3 = Computer RTS Bit 4 = Inverted radio sense Bit 5 = Inverted Computer RTS Bit 6 = Inhibit polarity (0=active low, 1=active high)
unsigned char ptt_input;
Definition at line 304 of file computer_interface.c.