front_panel/init.h File Reference
Initialization routines for the front panel.
Functions
void init_timer_0 (void)
void init_timer_2 (void)
void init_ports (void)
Set the direction of the ports.
void init_usart_computer (void)
void init_usart (void)
Initializes the USART for the communication bus.
void init_backlight (void)
Detailed Description
Initialization routines for the front panel.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/init.h" 
Definition in file init.h.
Function Documentation
void init_backlight (void)
Initialize the backlight (Which is pulse width modulated so we can set the contrast)
Definition at line 105 of file init.c.
Referenced by main().
void init_ports (void)
Set the direction of the ports.
Set the direction of the ports
Set the direction of the ports
Set the direction of the ports
Set the direction of the ports
Definition at line 56 of file init.c.
void init_timer_0 (void)
Initialize timer0 to use the main crystal clock and the output compare interrupt feature to generate an interrupt approximately once per millisecond to use as a general purpose time base.
Initialize timer0 to use the main crystal clock and the output compare interrupt feature to generate an interrupt approximately once per millisecond to use as a general purpose time base.
Initialize timer0 to use the main crystal clock and the output compare interrupt feature to generate an interrupt approximately once per millisecond to use as a general purpose time base.
Initialize timer0 to use the main crystal clock and the output compare interrupt feature to generate an interrupt approximately once per millisecond to use as a general purpose time base.
Definition at line 35 of file init.c.
void init_timer_2 (void)
Initializes timer 2, used for the communication bus and the interrupt is caught in bus.c
Initializes timer 2
Initializes timer 2, used for the communication bus and the interrupt is caught in bus.c
Definition at line 45 of file init.c.
void init_usart (void)
Initializes the USART for the communication bus.
Initializes the USART for the communication bus
Definition at line 41 of file init.c.
void init_usart_computer (void)
Init the UART for the computer communication
Definition at line 33 of file init.c.
References usart1_init(), usart1_receive_loopback(), and usart1_transmit().
Referenced by main().