front_panel/usart.h File Reference
USART routines.
#include `../global.h`
Functions
unsigned char poll_usart0_receive (void)
Retrieve one character from the USART0 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
void usart0_init (unsigned int baudrate)
Initiliaze the USART0 for the communication bus This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA2560 baudrate setting.
void usart0_transmit (char data)
Send a character to the USART0 Send a single character to the USART used for the communication bus.
unsigned char usart0_receive (void)
Retrieve one character from the USART0 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
unsigned char usart0_receive_loopback (void)
The USART0 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
unsigned char usart0_sendstring (char *data, unsigned char length)
Send a string of characters to the USART0 Send a string of characters to the USART used for the communication bus.
unsigned char poll_usart1_receive (void)
Retrieve one character from the USART1 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
void usart1_init (unsigned int baudrate, unsigned char stopbits)
Initiliaze the USART1 for the interface towards the computer This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA2560 baudrate setting.
unsigned char usart1_transmit (unsigned char data)
unsigned char usart1_receive (void)
Retrieve one character from the USART1 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
unsigned char usart1_receive_loopback (void)
The USART1 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
unsigned char usart1_sendstring (char *data, unsigned char length)
Send a string of characters to the USART1 Send a string of characters to the USART used for the communication bus.
unsigned char poll_usart3_receive (void)
Retrieve one character from the USART3 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
void usart3_init (unsigned int baudrate, unsigned char stopbits)
Initiliaze the USART3 for the radio interface This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA2560 baudrate setting.
unsigned char usart3_transmit (unsigned char data)
unsigned char usart3_receive (void)
Retrieve one character from the USART3 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
unsigned char usart3_receive_loopback (void)
The USART3 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
unsigned char usart3_sendstring (char *data, unsigned char length)
Send a string of characters to the USART3 Send a string of characters to the USART used for the communication bus.
Detailed Description
USART routines.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/usart.h" 
Definition in file usart.h.
Function Documentation
unsigned char poll_usart0_receive (void)
Retrieve one character from the USART0 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Returns: The character from the RX USART buffer
Retrieve one character from the USART0 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Returns: The character from the RX USART buffer
Definition at line 100 of file usart.c.
unsigned char poll_usart1_receive (void)
Retrieve one character from the USART1 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Returns: The character from the RX USART buffer
Retrieve one character from the USART1 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Returns: The character from the RX USART buffer
Definition at line 185 of file usart.c.
unsigned char poll_usart3_receive (void)
Retrieve one character from the USART3 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Returns: The character from the RX USART buffer
Definition at line 270 of file usart.c.
void usart0_init (unsigned int baudrate)
Initiliaze the USART0 for the communication bus This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA2560 baudrate setting.
Parameters:
baudrate The baudrate param from the ATMEGA2560 datasheet.
Initiliaze the USART0 for the communication bus This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA2560 baudrate setting.
Parameters:
baud The baudrate param from the ATMEGA32 datasheet.
Definition at line 34 of file usart.c.
unsigned char usart0_receive (void)
Retrieve one character from the USART0 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
Returns: The character from the RX USART buffer
Retrieve one character from the USART0 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
Returns: The character from the RX USART buffer
Definition at line 73 of file usart.c.
unsigned char usart0_receive_loopback (void)
The USART0 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
Returns: The character from the RX USART buffer
The USART0 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
Returns: The character from the RX USART buffer
Definition at line 85 of file usart.c.
unsigned char usart0_sendstring (char * data, unsigned char length)
Send a string of characters to the USART0 Send a string of characters to the USART used for the communication bus.
Parameters:
data The string of characters you wish to send
length The length of the string you wish to send
Send a string of characters to the USART0 Send a string of characters to the USART used for the communication bus.
Parameters:
data The string of characters you wish to send
length The length of the string you wish to send
Definition at line 60 of file usart.c.
void usart0_transmit (char data)
Send a character to the USART0 Send a single character to the USART used for the communication bus.
Parameters:
data The character you want to send
Send a character to the USART0 Send a single character to the USART used for the communication bus.
Parameters:
data The character you want to send
Definition at line 48 of file usart.c.
Referenced by init_usart(), main(), usart0_receive_loopback(), usart0_sendstring(), usart1_receive_loopback(), and usart3_receive_loopback().
void usart1_init (unsigned int baudrate, unsigned char stopbits)
Initiliaze the USART1 for the interface towards the computer This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA2560 baudrate setting.
Parameters:
baudrate The baudrate param from the ATMEGA2560 datasheet.
stopbits The number of stopbits.
Definition at line 112 of file usart.c.
Referenced by init_usart_computer(), main(), and radio_interface_init().
unsigned char usart1_receive (void)
Retrieve one character from the USART1 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
Returns: The character from the RX USART buffer
Retrieve one character from the USART1 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
Returns: The character from the RX USART buffer
Definition at line 158 of file usart.c.
unsigned char usart1_receive_loopback (void)
The USART1 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
Returns: The character from the RX USART buffer
The USART1 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
Returns: The character from the RX USART buffer
Definition at line 170 of file usart.c.
unsigned char usart1_sendstring (char * data, unsigned char length)
Send a string of characters to the USART1 Send a string of characters to the USART used for the communication bus.
Parameters:
data The string of characters you wish to send
length The length of the string you wish to send
Send a string of characters to the USART1 Send a string of characters to the USART used for the communication bus.
Parameters:
data The string of characters you wish to send
length The length of the string you wish to send
Definition at line 145 of file usart.c.
void usart3_init (unsigned int baudrate, unsigned char stopbits)
Initiliaze the USART3 for the radio interface This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA2560 baudrate setting.
Parameters:
baudrate The baudrate param from the ATMEGA2560 datasheet.
stopbits The number of stopbits.
Definition at line 197 of file usart.c.
Referenced by radio_interface_init().
unsigned char usart3_receive (void)
Retrieve one character from the USART3 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
Returns: The character from the RX USART buffer
Definition at line 243 of file usart.c.
unsigned char usart3_receive_loopback (void)
The USART3 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
Returns: The character from the RX USART buffer
Definition at line 255 of file usart.c.
References usart0_transmit().
unsigned char usart3_sendstring (char * data, unsigned char length)
Send a string of characters to the USART3 Send a string of characters to the USART used for the communication bus.
Parameters:
data The string of characters you wish to send
length The length of the string you wish to send
Definition at line 230 of file usart.c.
References usart3_transmit().