front_panel/computer_interface.c File Reference
Interface towards the computer.
#include <avr/wdt.h>
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/eeprom.h>
#include <string.h>
#include `computer_interface.h`
#include `radio_interface.h`
#include `usart.h`
#include `ds1307.h`
#include `antenna_ctrl.h`
#include `eeprom.h`
#include `led_control.h`
#include `sequencer.h`
Classes
struct computer_comm_struct
Computer interface communication struct.
Defines
#define COMPUTER_RX_BUFFER_LENGTH 128
The length of the computer RX BUFFER.
#define COMPUTER_TX_BUFFER_LENGTH 20
The length of the computer RX BUFFER.
#define COMPUTER_INTERFACE_FIXED_SIZE 5
The fixed size of the computer interface structure (PREAMBLE, POSTAMBLE etc).
#define COMPUTER_COMM_PREAMBLE 0xFE
The preamble of the computer communication protocol.
#define COMPUTER_COMM_POSTAMBLE 0xFD
The postamble of the computer communication protocol.
#define COMPUTER_COMM_ACK 0xFA
The serial acknowledge of the computer communication protocol.
#define COMPUTER_COMM_NACK 0xFB
The serial NOT acknowledge of the computer communication protocol.
#define COMPUTER_COMM_FLAG_SETUP_MODE 0
Flag to see if the setup mode is activated.
#define COMPUTER_COMM_FLAG_FOUND_PREAMBLE 1
Flag to see if the preamble was found.
#define COMPUTER_COMM_FLAG_DATA_IN_RX_BUF 2
Flag to see that there is data in the rx buffer.
#define COMPUTER_COMM_ENTER_BOOTLOADER 0x01
Command to force the openASC box into bootloader mode.
#define CTRL_REBOOT 0x02
CTRL command: Reboot the device.
#define CTRL_GET_FIRMWARE_REV 0x03
CTRL command: Retrieve the firmware revision.
#define CTRL_DONE 0x04
This function just replies with the same command, this is so we can see when something has been finished.
#define CTRL_SET_TIME 0x10
CTRL section: Set the time of the realtime clock.
#define CTRL_SET_ANT_DATA 0x11
CTRL section: Set the TX antenna settings.
#define CTRL_CREATE_EEPROM_TABLE 0x12
CTRL section: Create an EEPROM table.
#define CTRL_SET_RX_ANT_DATA 0x13
CTRL section: Set the RX antenna settings.
#define CTRL_SET_RADIO_SETTINGS 0x14
CTRL section: Set the radio settings.
#define CTRL_SET_DEVICE_SETTINGS 0x15
CTRL section: Set the device settings.
#define CTRL_SET_BAND_DATA 0x16
CTRL section: Set the band data settings.
#define CTRL_SET_EXT_INPUT 0x17
CTRL section: Set the external input settings.
#define CTRL_SET_SEQUENCER_SETTINGS 0x18
CTRL section: Set the sequencer settings.
#define CTRL_SET_RADIO_SETTINGS_SAVE 0x01
CTRL command: Save the radio settings.
#define CTRL_SET_RADIO_SETTINGS_ALL 0x02
CTRL command: Set all antenna settings.
#define CTRL_SET_ANT_DATA_SAVE 0x01
CTRL command: Save the antenna information data to the EEPROM.
#define CTRL_SET_ANT_DATA_TEXT 0x02
CTRL command: Set the antenna text.
#define CTRL_SET_ANT_DATA_SUB_MENU_TYPE 0x03
CTRL command: Set the antenna sub menu type.
#define CTRL_SET_ANT_DATA_ANT_FLAGS 0x04
CTRL command: Set the antenna flags.
#define CTRL_SET_ANT_DATA_COMB_ALLOWED 0x05
CTRL command: Set the output combination allowed.
#define CTRL_SET_ANT_DATA_ANT_OUT_STR 0x06
CTRL command: Set the antenna output str.
#define CTRL_SET_ANT_ROTATOR_DATA 0x07
CTRL command: Set the rotator information.
#define CTRL_SET_ANT_DEFAULT_INDEX 0x08
CTRL command: Set the default antenna index.
#define CTRL_SET_ANT_SUB_MENU_DATA 0x09
CTRL command: Set the sub menu data.
#define CTRL_SET_ANT_SUB_MENU_TEXT 0x0A
CTRL command: Set the sub menu data, text.
#define CTRL_SET_ANT_SUB_MENU_OUTPUT_STR 0x0B
CTRL command: Set the sub menu data, output str.
#define CTRL_SET_BAND_DATA_LIMITS 0x01
CTRL command: Set the band data limits.
#define CTRL_SET_BAND_DATA_LOW_OUT_STR 0x02
CTRL command: Set the band low portion output str.
#define CTRL_SET_BAND_DATA_HIGH_OUT_STR 0x03
CTRL command: Set the band high portion output str.
#define CTRL_SET_BAND_DATA_SAVE 0x07
CTRL command: Save the band data settings.
#define CTRL_SET_RX_ANT_DATA_TEXT 0x01
CTRL command: Set the RX antenna text.
#define CTRL_SET_RX_ANT_DATA_ANT_OUT_STR 0x02
CTRL command: Set the RX antenna output str.
#define CTRL_SET_RX_ANT_DATA_BAND_OUT_STR 0x03
CTRL command: Set the RX antenna band output str.
#define CTRL_SET_RX_ANT_DATA_SAVE 0x07
CTRL command: Save the RX antenna settings.
#define CTRL_SET_DEVICE_SETTINGS_NETWORK 0x01
CTRL command: Network settings.
#define CTRL_SET_POWERMETER_SETTINGS 0x02
CTRL command: Powermeter settings.
#define CTRL_SET_DEVICE_SETTINGS_OTHER 0x03
CTRL command: Various settings.
#define CTRL_SET_DEVICE_SETTINGS_EXT_INPUTS 0x04
CTRL command: External input settings.
#define CTRL_SET_DEVICE_SETTINGS_SAVE 0x07
CTRL command: Save data to eeprom.
#define CTRL_SET_SEQUENCER_SAVE 0x01
CTRL command: Save the sequencer settings.
#define CTRL_SET_SEQUENCER_FOOTSWITCH 0x02
CTRL command: Set the sequencer footswitch input values.
#define CTRL_SET_SEQUENCER_COMPUTER 0x03
CTRL command: Set the sequencer computer input values.
#define CTRL_SET_SEQUENCER_RADIO_SENSE 0x04
CTRL command: Set the sequencer radio sense input values.
#define CTRL_SET_DEVICE_SETTINGS_EXT_INPUTS 0x05
CTRL command: External input settings.
#define CTRL_SET_DEVICE_SETTINGS_SAVE 0x07
CTRL command: Save data to eeprom.
#define CTRL_SET_EXT_KEYPAD_FUNCTIONS 0x01
Functions
void computer_interface_init (void)
Initialize the communication interface towards the computer. Will initialize buffers etc.
void computer_interface_send_data (void)
Function which will send data from the tx_buffer to the uart.
void computer_interface_send (unsigned char command, unsigned int length, char *data)
Function which will add data to the tx_buffer. Function also sets the flag indicating that the data should be sent.
void computer_interface_send_ack (void)
Function which will add an ACK message to the tx_buffer. Also sets a flag that indicates data ready to be sent.
void computer_interface_send_nack (void)
Function which will add an NACK message to the tx_buffer. Also sets a flag that indicates data ready to be sent.
void computer_interface_parse_data (void)
Function which will parse the data in the rx_buffer and process the command.
unsigned char computer_interface_is_active (void)
Retrieve the status if the computer interface is active.
void computer_interface_activate_setup (void)
Activate the setup mode of the device. Will mainly just create various buffers needed to store settings.
void computer_interface_deactivate_setup (void)
Function which will deactivate the computer setup mode, this will clear up memory space of the allocated buffers in the computer_interface_activate_setup() function.
ISR (SIG_USART1_DATA)
ISR (SIG_USART1_RECV)
Interrupt when a character is received over the UART. If computer setup mode is active it will parse the incoming data, otherwise it is used for CAT control.
Variables
computer_comm_struct computer_comm
Computer communication structure.
struct_antenna * antenna_ptr
Pointer to an area which we create space when configuring the antenna data.
struct_rx_antennas * rx_antenna_ptr
Pointer to an area which we create space when configuring the rx antenna data.
struct_band * band_ptr
Pointer to an area which we create space when configuring the band data.
struct_setting * settings_ptr
Pointer to an area which we create space when configuring the settings.
struct_ptt * ptt_sequencer_ptr
Pointer to an area which we create space when configuring the ptt_sequencer.
struct_radio_settings * radio_settings_ptr
Pointer to an area which we crate space when configuring the radio settings.
struct_sub_menu_array * sub_menu_array_ptr [4]
Pointer to an area which we crate space when configuring the sub menu (array).
void(* bootloader_start)(void) = (void *)0x1FE00
Address which we call when we wish to reboot the device (jumps to the bootloader area).
Detailed Description
Interface towards the computer.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/computer_interface.c" 
Definition in file computer_interface.c.
Define Documentation
#define CTRL_SET_DEVICE_SETTINGS_EXT_INPUTS 0x05
CTRL command: External input settings.
CTRL command: Set the external inputs.
Definition at line 176 of file computer_interface.c.
#define CTRL_SET_DEVICE_SETTINGS_EXT_INPUTS 0x04
CTRL command: External input settings.
CTRL command: Set the external inputs.
Definition at line 176 of file computer_interface.c.
Referenced by computer_interface_parse_data().
#define CTRL_SET_DEVICE_SETTINGS_SAVE 0x07
CTRL command: Save data to eeprom.
CTRL command: Save the external input settings.
Definition at line 178 of file computer_interface.c.
#define CTRL_SET_DEVICE_SETTINGS_SAVE 0x07
CTRL command: Save data to eeprom.
CTRL command: Save the external input settings.
Definition at line 178 of file computer_interface.c.
Referenced by computer_interface_parse_data().
#define CTRL_SET_EXT_KEYPAD_FUNCTIONS 0x01
CTRL command: Set the external keypad function
Definition at line 181 of file computer_interface.c.
Function Documentation
unsigned char computer_interface_is_active (void)
Retrieve the status if the computer interface is active.
Returns: 1 if it is active, 0 otherwise
Definition at line 686 of file computer_interface.c.
References COMPUTER_COMM_FLAG_SETUP_MODE, and computer_comm_struct::flags.
Referenced by event_internal_comm_parse_message(), ISR(), and main().
void computer_interface_parse_data (void)
Function which will parse the data in the rx_buffer and process the command.
Bit 0 = Footswitch Bit 1 = Radio sense lower floor Bit 2 = Radio sense upper floor Bit 3 = Computer RTS Bit 4 = Inverted radio sense Bit 5 = Inverted Computer RTS Bit 6 = Inhibit polarity (0=active low, 1=active high)
unsigned char ptt_input;
Definition at line 304 of file computer_interface.c.
Referenced by main().
void computer_interface_send (unsigned char command, unsigned int length, char * data)
Function which will add data to the tx_buffer. Function also sets the flag indicating that the data should be sent.
Parameters:
command The command we wish to sendchar(
length Number of bytes of data to be sent (only size of the data variable)
data The data we wish to send
Definition at line 263 of file computer_interface.c.
References COMPUTER_COMM_POSTAMBLE, COMPUTER_COMM_PREAMBLE, COMPUTER_INTERFACE_FIXED_SIZE, computer_comm_struct::data_in_tx_buffer, computer_comm_struct::tx_buffer, and computer_comm_struct::tx_buffer_length.
Referenced by computer_interface_parse_data(), and parse_internal_comm_message().