front_panel/interrupt_handler.c File Reference
Handles different external interrupts.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include `main.h`
#include `board.h`
Functions
int ih_poll_buttons (void)
unsigned char ih_poll_ext_devices (void)
Detailed Description
Handles different external interrupts.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/interrupt_handler.c" 
Definition in file interrupt_handler.c.
Function Documentation
int ih_poll_buttons (void)
Polls the status of all buttons on the front panel and returns it as an integer. The bit mask pattern is defined in board.h
Returns: Which buttons that are currently pressed, see mask pattern in board.h
The following is done because of a hardware bug! The pullups on the uC are too small to actually charge the debounce capacitor in time. The way we solve it is that by making the pin to an output we can charge the capacitor and then go over to using the pin as input and reactivate the pullups again.
Definition at line 37 of file interrupt_handler.c.
References BUTTON1_RX_BIT, BUTTON1_TX_BIT, BUTTON2_RX_BIT, BUTTON2_TX_BIT, BUTTON3_RX_BIT, BUTTON3_TX_BIT, BUTTON4_RX_BIT, BUTTON4_TX_BIT, BUTTON_AUX1_BIT, BUTTON_AUX2_BIT, BUTTON_MENU_BIT, BUTTON_PULSE_BIT, BUTTON_ROTATE_BIT, BUTTON_RXANT_BIT, BUTTON_SUBMENU_BIT, BUTTON_TXRX_BIT, FLAG_BUTTON1_RX_BIT, FLAG_BUTTON1_TX_BIT, FLAG_BUTTON2_RX_BIT, FLAG_BUTTON2_TX_BIT, FLAG_BUTTON3_RX_BIT, FLAG_BUTTON3_TX_BIT, FLAG_BUTTON4_RX_BIT, FLAG_BUTTON4_TX_BIT, FLAG_BUTTON_AUX1_BIT, FLAG_BUTTON_AUX2_BIT, FLAG_BUTTON_MENU_BIT, FLAG_BUTTON_PULSE_BIT, FLAG_BUTTON_ROTATE_BIT, FLAG_BUTTON_RXANT_BIT, FLAG_BUTTON_SUBMENU_BIT, and FLAG_BUTTON_TXRX_BIT.
Referenced by event_poll_buttons().
unsigned char ih_poll_ext_devices (void)
Polls the status of all the external inputs. This function does not care if the device is active low or active high. It will just return the current state so the handeling of leveling needs to be done elsewhere. The bit mask pattern is defined in board.h
Returns: The status of the external devices
Definition at line 108 of file interrupt_handler.c.
References EXT_FOOTSWITCH_BIT, EXT_RADIO_SENSE1_BIT, EXT_RADIO_SENSE2_BIT, EXT_USB1_DTR_BIT, EXT_USB2_DTR_BIT, EXT_USB2_RTS_BIT, STATUS_FOOTSWITCH_BIT, STATUS_RADIO_SENSE1_BIT, STATUS_RADIO_SENSE2_BIT, STATUS_USB1_DTR_BIT, STATUS_USB2_DTR_BIT, and STATUS_USB2_RTS_BIT.
Referenced by event_poll_ext_device(), and main().