internal_comm.h File Reference
The internal communication routines.
Classes
struct UC_MESSAGE
struct struct_uc_com
Defines
#define UC_PREAMBLE_FOUND 0
if the device is a motherboard we need to set the proper USARTs used
#define UC_MESSAGE_IN_BUFFER 1
Flag that a message is in the buffer.
#define UC_SIZE_FIXED 5
Size of UC MESSAGE fixed part.
#define UC_COMM_MSG_PREAMBLE 0xFE
#define UC_COMM_MSG_POSTAMBLE 0xFD
#define UC_COMM_MSG_ACK 0xFB
#define UC_COMM_MSG_NACK 0xFA
#define UC_SERIAL_RX_BUFFER_LENGTH 20
The length of the serial rx buffer used for communication between the uCs.
#define UC_MESSAGE_DATA_SIZE 15
The size the data sent between the two devices can be maximum.
#define UC_COMM_RX_TIMEOUT 3
After this many ms it will reset the rx flags (in ms).
#define UC_COMM_TX_TIMEOUT 10
After this many ms a resend will occur if a message has not been acked (in ms).
#define UC_COMM_RESEND_COUNT 5
Number of resends that is allowed.
Functions
void internal_comm_init (void(*func_ptr_rx)(UC_MESSAGE), void(*func_ptr_tx)(char))
Initialize the internal communication.
unsigned char internal_comm_poll_rx_queue (void)
Polls the RX queue in the internal communication and calls the function defined in internal_comm_init.
unsigned char internal_comm_poll_tx_queue (void)
Polls the TX queue in the internal communication and sends the data if there is a message in the queue.
void internal_comm_add_tx_message (unsigned char command, unsigned char length, char *data)
Add a message to the transmit queue.
void internal_comm_send_ack (void)
Send an ACK message to the internal communication uart.
void internal_comm_send_nack (void)
Send a NACK message to the internal communication uart.
void internal_comm_send_message (UC_MESSAGE tx_message)
Send a message to the internal communication uart.
void internal_comm_reset_rx (void)
Will reset the RX variables.
void internal_comm_1ms_timer (void)
Function which should be called each ms.
void internal_comm_resend (void)
Will trigger a resend of the last message.
Detailed Description
The internal communication routines.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "internal_comm.h" 
Definition in file internal_comm.h.
Define Documentation
#define UC_COMM_MSG_ACK 0xFB
The acknowledge command of the bus
Definition at line 73 of file internal_comm.h.
Referenced by internal_comm_send_ack(), and ISR().
#define UC_COMM_MSG_NACK 0xFA
The NOT acknowledge command of the bus
Definition at line 75 of file internal_comm.h.
Referenced by internal_comm_send_nack(), and ISR().
#define UC_COMM_MSG_POSTAMBLE 0xFD
The postamble of the BUS message
Definition at line 71 of file internal_comm.h.
Referenced by internal_comm_send_ack(), internal_comm_send_message(), internal_comm_send_nack(), and ISR().
#define UC_COMM_MSG_PREAMBLE 0xFE
The preamble of the BUS message
Definition at line 69 of file internal_comm.h.
Referenced by internal_comm_send_ack(), internal_comm_send_message(), internal_comm_send_nack(), and ISR().
#define UC_PREAMBLE_FOUND 0
if the device is a motherboard we need to set the proper USARTs used
if the device is a frontpanel we need to set the proper USARTs used Preamble found for the communication between the uCs
Definition at line 61 of file internal_comm.h.
Referenced by ISR().
Function Documentation
void internal_comm_add_tx_message (unsigned char command, unsigned char length, char * data)
Add a message to the transmit queue.
Parameters:
command The command we wish to perform
length The length of the data field
data The data we wish to send
Definition at line 166 of file internal_comm.c.
References UC_MESSAGE::checksum, UC_MESSAGE::cmd, UC_MESSAGE::data, int_comm_tx_queue_add(), and UC_MESSAGE::length.
Referenced by antenna_ctrl_deactivate_outputs(), antenna_ctrl_send_ant_data_to_bus(), antenna_ctrl_send_rx_ant_band_data_to_bus(), antenna_ctrl_send_rx_ant_data_to_bus(), band_ctrl_send_band_data_to_bus(), computer_interface_parse_data(), main(), parse_internal_comm_message(), ps2_process_key(), radio_poll_status(), shutdown_device(), and sub_menu_send_data_to_bus().
void internal_comm_init (void(*)(UC_MESSAGE) func_ptr_rx, void(*)(char) func_ptr_tx)
Initialize the internal communication.
Parameters:
func_ptr_rx The function you wish to call when a new message has been recieved and should be parsed
func_ptr_tx The function used to send data to the hardware handeling the data transmission
Definition at line 68 of file internal_comm.c.
References struct_uc_com::char_count, struct_uc_com::checksum, f_ptr_rx, f_ptr_tx, struct_uc_com::flags, int_comm_rx_queue_dropall(), and int_comm_tx_queue_dropall().
Referenced by main().
unsigned char internal_comm_poll_rx_queue (void)
Polls the RX queue in the internal communication and calls the function defined in internal_comm_init.
Returns: 1 if a message was in the buffer and got parsed, 0 if not
Definition at line 91 of file internal_comm.c.
References f_ptr_rx, int_comm_rx_queue_drop(), int_comm_rx_queue_get(), and int_comm_rx_queue_is_empty().
Referenced by main().
unsigned char internal_comm_poll_tx_queue (void)
Polls the TX queue in the internal communication and sends the data if there is a message in the queue.
Returns: 1 if a message was in the buffer and got sent, 0 if not
Definition at line 105 of file internal_comm.c.
References int_comm_tx_queue_get(), int_comm_tx_queue_is_empty(), internal_comm_send_message(), and msg_not_acked.
Referenced by main().
void internal_comm_send_message (UC_MESSAGE tx_message)
Send a message to the internal communication uart.
Parameters:
tx_message The message we wish to send
Definition at line 147 of file internal_comm.c.
References UC_MESSAGE::checksum, UC_MESSAGE::cmd, counter_tx_timeout, UC_MESSAGE::data, f_ptr_tx, UC_MESSAGE::length, UC_COMM_MSG_POSTAMBLE, and UC_COMM_MSG_PREAMBLE.
Referenced by internal_comm_poll_tx_queue(), and internal_comm_resend().