internal_comm.c File Reference
The internal communication routines.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <string.h>
#include `internal_comm.h`
#include `internal_comm_rx_queue.h`
#include `internal_comm_tx_queue.h`
Functions
void internal_comm_init (void(*func_ptr_rx)(UC_MESSAGE), void(*func_ptr_tx)(char))
Initialize the internal communication.
void internal_comm_reset_rx (void)
Will reset the RX variables.
unsigned char internal_comm_poll_rx_queue (void)
Polls the RX queue in the internal communication and calls the function defined in internal_comm_init.
unsigned char internal_comm_poll_tx_queue (void)
Polls the TX queue in the internal communication and sends the data if there is a message in the queue.
void internal_comm_send_ack (void)
Send an ACK message to the internal communication uart.
void internal_comm_send_nack (void)
Send a NACK message to the internal communication uart.
void internal_comm_send_message (UC_MESSAGE tx_message)
Send a message to the internal communication uart.
void internal_comm_add_tx_message (unsigned char command, unsigned char length, char *data)
Add a message to the transmit queue.
void internal_comm_resend (void)
Will trigger a resend of the last message.
ISR (ISR_INTERNAL_COMM_USART_RECV)
Interrupt when a byte has been received from the UART.
ISR (ISR_INTERNAL_COMM_USART_DATA)
Interrupt when data has been received from the UART.
void internal_comm_1ms_timer (void)
Function which should be called each ms.
Variables
struct_uc_com uc_com
The uc_com struct.
UC_MESSAGE uc_new_message
Where we save any new uc_comm message.
unsigned char prev_data = 0
The previous data.
unsigned char counter_tx_timeout = 0
Counter which keep track of when we last did a transmission.
unsigned char counter_rx_timeout = 0
Counter which keeps track of when we last did receive a character.
unsigned char resend_count = 0
The number of times the last message has been resent.
unsigned char msg_not_acked = 0
Flag that the message has yet not been acked.
void(* f_ptr_rx)(UC_MESSAGE)
Function to be called when a message is recieved and should be parsed/executed.
void(* f_ptr_tx)(char)
Function to be called when we wish to send a message.
Detailed Description
The internal communication routines.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "internal_comm.c" 
Definition in file internal_comm.c.
Function Documentation
void internal_comm_add_tx_message (unsigned char command, unsigned char length, char * data)
Add a message to the transmit queue.
Parameters:
command The command we wish to perform
length The length of the data field
data The data we wish to send
Definition at line 166 of file internal_comm.c.
References UC_MESSAGE::checksum, UC_MESSAGE::cmd, UC_MESSAGE::data, int_comm_tx_queue_add(), and UC_MESSAGE::length.
Referenced by antenna_ctrl_deactivate_outputs(), antenna_ctrl_send_ant_data_to_bus(), antenna_ctrl_send_rx_ant_band_data_to_bus(), antenna_ctrl_send_rx_ant_data_to_bus(), band_ctrl_send_band_data_to_bus(), computer_interface_parse_data(), main(), parse_internal_comm_message(), ps2_process_key(), radio_poll_status(), shutdown_device(), and sub_menu_send_data_to_bus().
void internal_comm_init (void(*)(UC_MESSAGE) func_ptr_rx, void(*)(char) func_ptr_tx)
Initialize the internal communication.
Parameters:
func_ptr_rx The function you wish to call when a new message has been recieved and should be parsed
func_ptr_tx The function used to send data to the hardware handeling the data transmission
Definition at line 68 of file internal_comm.c.
References struct_uc_com::char_count, struct_uc_com::checksum, f_ptr_rx, f_ptr_tx, struct_uc_com::flags, int_comm_rx_queue_dropall(), and int_comm_tx_queue_dropall().
Referenced by main().
unsigned char internal_comm_poll_rx_queue (void)
Polls the RX queue in the internal communication and calls the function defined in internal_comm_init.
Returns: 1 if a message was in the buffer and got parsed, 0 if not
Definition at line 91 of file internal_comm.c.
References f_ptr_rx, int_comm_rx_queue_drop(), int_comm_rx_queue_get(), and int_comm_rx_queue_is_empty().
Referenced by main().
unsigned char internal_comm_poll_tx_queue (void)
Polls the TX queue in the internal communication and sends the data if there is a message in the queue.
Returns: 1 if a message was in the buffer and got sent, 0 if not
Definition at line 105 of file internal_comm.c.
References int_comm_tx_queue_get(), int_comm_tx_queue_is_empty(), internal_comm_send_message(), and msg_not_acked.
Referenced by main().
void internal_comm_send_message (UC_MESSAGE tx_message)
Send a message to the internal communication uart.
Parameters:
tx_message The message we wish to send
Definition at line 147 of file internal_comm.c.
References UC_MESSAGE::checksum, UC_MESSAGE::cmd, counter_tx_timeout, UC_MESSAGE::data, f_ptr_tx, UC_MESSAGE::length, UC_COMM_MSG_POSTAMBLE, and UC_COMM_MSG_PREAMBLE.
Referenced by internal_comm_poll_tx_queue(), and internal_comm_resend().