internal_comm_tx_queue.c File Reference
The internal communication TX QUEUE.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `internal_comm_tx_queue.h`
Functions
void int_comm_int_comm_tx_queue_init (void)
void int_comm_tx_queue_add (UC_MESSAGE message)
Insert a message into the TX queue (FIFO).
UC_MESSAGE int_comm_tx_queue_get (void)
Retrieve the first message from the FIFO TX queue.
void int_comm_tx_queue_drop (void)
void int_comm_tx_queue_dropall (void)
Erase all content in the TX queue.
unsigned char int_comm_tx_queue_is_empty (void)
Check if the queue is empty.
Variables
int_comm_tx_queue_struct int_comm_tx_queue
The TX queue.
Detailed Description
The internal communication TX QUEUE.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "internal_comm_tx_queue.c" 
Definition in file internal_comm_tx_queue.c.
Function Documentation
void int_comm_int_comm_tx_queue_init (void)
Initialize the internal communication TX queue
Definition at line 35 of file internal_comm_tx_queue.c.
References tx_linked_list::first, and tx_linked_list::last.
void int_comm_tx_queue_add (UC_MESSAGE message)
Insert a message into the TX queue (FIFO).
Parameters:
message - The message that should be inserted to the queue
Definition at line 43 of file internal_comm_tx_queue.c.
References tx_linked_list::first, tx_linked_list::last, and tx_linked_list::message.
Referenced by internal_comm_add_tx_message().
void int_comm_tx_queue_drop (void)
Drops the first message in the queue Frees up the memory space aswell.
Definition at line 66 of file internal_comm_tx_queue.c.
References tx_linked_list::first.
Referenced by ISR().
void int_comm_tx_queue_dropall (void)
Erase all content in the TX queue.
Returns: The number of items that were cleared
Definition at line 76 of file internal_comm_tx_queue.c.
References tx_linked_list::first, and tx_linked_list::last.
Referenced by internal_comm_init().
UC_MESSAGE int_comm_tx_queue_get (void)
Retrieve the first message from the FIFO TX queue.
Returns: The first message in the queue
Definition at line 59 of file internal_comm_tx_queue.c.
References tx_linked_list::first, and tx_linked_list::message.
Referenced by internal_comm_poll_tx_queue(), and internal_comm_resend().
unsigned char int_comm_tx_queue_is_empty (void)
Check if the queue is empty.
Returns: 1 if the queue is empty and 0 otherwise
Definition at line 84 of file internal_comm_tx_queue.c.
References tx_linked_list::first, and tx_linked_list::last.
Referenced by internal_comm_poll_tx_queue().