front_panel/menu.c File Reference
Menu system.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <string.h>
#include `menu.h`
#include `board.h`
#include `glcd.h`
#include `fonts.h`
#include `display.h`
#include `radio_interface.h`
#include `errors.h`
#include `event_handler.h`
#include `led_control.h`
Defines
#define MENU_OPTION_LEFT_POS 13
Sets the intend from the left.
#define MENU_OPTIONS 7
Number of options in the menu system.
Functions
void menu_show_text (struct_menu_text menu_text)
Show the text of a menu on the display.
void menu_init (void)
Initialize the menu system.
void menu_reset (void)
Function will reset to init values, like menu level etc.
void menu_show (void)
Shows the menu.
void menu_action (unsigned char menu_action_type)
Variables
const struct_menu_option menu_errors [] = {{`Bus resend`},{`No bus sync`}, {`Bus TX queue full`}, {`Bus RX queue full`}, {`Int. comm resend`}}
Menu options - Errors.
const struct_menu_option menu_misc [] = {{`Reboot`}}
unsigned char current_menu_option_selected [MENU_OPTIONS]
The current selected menu option.
unsigned char current_menu_level = 0
Flag to indicate which menu level we are on.
unsigned char current_menu_pos = 0
Flag to indicate the current menu position.
const struct_menu_option menu_option_band_selection_mode [] = {{`Manual`},{`Auto`}}
Menu system option - band selection mode.
const struct_menu_option menu_option_amp_ptt_output [] = {{`ON`},{`OFF`}}
Menu system option - amp ptt output.
const struct_menu_option menu_option_radio_ptt_output [] = {{`ON`},{`OFF`}}
Menu system option - radio ptt output.
const struct_menu_text menu_system_text []
Menu system.
Detailed Description
Menu system.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/menu.c " 
Definition in file menu.c.
Function Documentation
void menu_action (unsigned char menu_action_type)
This function will handle an menu action `event`
Parameters:
menu_action_type Which action did occur?
Definition at line 173 of file menu.c.
References struct_runtime_settings::amplifier_ptt_output, struct_runtime_settings::band_change_mode, BAND_CHANGE_MODE_AUTO, BAND_CHANGE_MODE_MANUAL, bootloader_start, current_menu_level, current_menu_option_selected, current_menu_pos, display_set_backlight(), event_get_errors(), event_set_error(), KNOB_FUNCTION_AUTO, struct_runtime_settings::lcd_backlight_value, led_set_error(), LED_STATE_OFF, MENU_BUTTON_PRESSED, MENU_OPTION_TYPE_NORMAL, MENU_OPTION_TYPE_SCROLL_NUMBERS, MENU_OPTIONS, MENU_POS_AMP_PTT, MENU_POS_BACKLIGHT_LEVEL, MENU_POS_BAND_MODE, MENU_POS_MISC, MENU_POS_RADIO_PTT, MENU_POS_SHOW_ERRORS, MENU_SCROLL_DOWN, MENU_SCROLL_UP, menu_show(), NR_OF_ERRORS, struct_runtime_settings::radio_ptt_output, runtime_settings, and set_knob_function().
Referenced by event_poll_buttons(), event_pulse_sensor_down(), and event_pulse_sensor_up().
void menu_show_text (struct_menu_text menu_text)
Show the text of a menu on the display.
Parameters:
menu_text The menu which we wish to show
Definition at line 79 of file menu.c.
References current_menu_level, current_menu_option_selected, current_menu_pos, display_calculate_width(), event_get_errors(), glcd_line(), struct_menu_text::header, struct_runtime_settings::lcd_backlight_value, MENU_OPTION_LEFT_POS, MENU_OPTION_TYPE_NORMAL, MENU_OPTION_TYPE_SCROLL_NUMBERS, MENU_POS_BACKLIGHT_LEVEL, MENU_POS_SHOW_ACTIVITY, MENU_POS_SHOW_ERRORS, NR_OF_ERRORS, struct_menu_text::option_count, struct_menu_text::option_type, struct_menu_text::options, struct_menu_text::pos, runtime_settings, and struct_menu_option::text.
Referenced by menu_show().
Variable Documentation
const struct_menu_text menu_system_text[]
Initial value:
 {
{MENU_POS_BAND_MODE, "Band change", (struct_menu_option *)menu_option_band_selection_mode, 2,MENU_OPTION_TYPE_NORMAL},
{MENU_POS_RADIO_PTT, "Radio PTT", (struct_menu_option *)menu_option_radio_ptt_output, 2,MENU_OPTION_TYPE_NORMAL},
{MENU_POS_AMP_PTT, "Amplifier PTT", (struct_menu_option *)menu_option_amp_ptt_output, 2,MENU_OPTION_TYPE_NORMAL},
{MENU_POS_BACKLIGHT_LEVEL, "Backlight", NULL, 0,MENU_OPTION_TYPE_SCROLL_NUMBERS},
{MENU_POS_SHOW_ACTIVITY, "Network activity", NULL, 0,MENU_OPTION_TYPE_NONE},
{MENU_POS_MISC, "Miscellaneous", (struct_menu_option *)menu_misc, 1,MENU_OPTION_TYPE_NORMAL},
{MENU_POS_SHOW_ERRORS, "Errors", (struct_menu_option *)menu_errors, 0,MENU_OPTION_TYPE_NORMAL},
}
Menu system.
Definition at line 67 of file menu.c.