motherboard/init.h File Reference
Initialization routines for the motherboard.
Functions
void init_timer_0 (void)
void init_ports (void)
Set the direction of the ports.
void init_usart (void)
Initializes the USART for the communication bus.
Detailed Description
Initialization routines for the motherboard.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "init.h" 
Definition in file init.h.
Function Documentation
void init_ports (void)
Set the direction of the ports.
Set the direction of the ports
Set the direction of the ports
Set the direction of the ports
Set the direction of the ports
Definition at line 56 of file init.c.
void init_timer_0 (void)
Initialize timer0 to use the main crystal clock and the output compare interrupt feature to generate an interrupt approximately once per millisecond to use as a general purpose time base.
Initialize timer0 to use the main crystal clock and the output compare interrupt feature to generate an interrupt approximately once per millisecond to use as a general purpose time base.
Initialize timer0 to use the main crystal clock and the output compare interrupt feature to generate an interrupt approximately once per millisecond to use as a general purpose time base.
Initialize timer0 to use the main crystal clock and the output compare interrupt feature to generate an interrupt approximately once per millisecond to use as a general purpose time base.
Definition at line 35 of file init.c.
References OCR0_1MS.
void init_usart (void)
Initializes the USART for the communication bus.
Initializes the USART for the communication bus
Definition at line 41 of file init.c.
References usart0_init(), usart0_receive_loopback(), and usart0_transmit().
Referenced by main().