front_panel/radio_interface.c File Reference
Radio interface, such as PTT AMP, PTT Radio, CAT etc.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include `radio_interface.h`
#include `led_control.h`
#include `band_ctrl.h`
#include `main.h`
#include `usart.h`
#include `board.h`
#include `eeprom.h`
#include `display.h`
#include `../internal_comm.h`
#include `../internal_comm_commands.h`
#include `../global.h`
Functions
void radio_interface_init (void)
Initialize the radio interface.
void radio_process_tasks (void)
This function is called each lap in the main loop and we can use this to process certain tasks.
unsigned int radio_get_current_freq (void)
unsigned char radio_get_current_band (void)
Retrieve the current band from the radio.
void radio_ptt_active (void)
Activate the radio PTT.
void radio_ptt_deactive (void)
Deactivate the radio PTT.
void radio_tx_active (void)
Set the TX ACTIVE output to high.
void radio_tx_deactive (void)
Set the TX ACTIVE output to high.
void radio_inhibit_high (void)
Set the inhibit signal to high.
void radio_inhibit_low (void)
Set the inhibit signal to low.
unsigned char radio_get_ptt_status (void)
Retrieve the ptt status, defines can be found in radio_interface.h.
unsigned char radio_get_band_portion (void)
void radio_set_current_band (unsigned char band)
unsigned char radio_poll_ptt (void)
Polls the status of the PTT input.
unsigned char radio_poll_status (void)
Polls the status of the radio and saves it into the radio_status structure.
unsigned int radio_parse_freq (unsigned char *freq_data, unsigned char length, unsigned char radio_model)
Parse the radios frequency.
void radio_amp_ptt_active (void)
Activate PTT amp.
void radio_amp_ptt_deactive (void)
Deactivate PTT amp.
unsigned char radio_freq_to_band (unsigned int freq)
Convert a radio frequency (integer) to band data.
void radio_interface_set_model (unsigned char model)
Set which radio model is used, saves it in the radio_settings struct.
void radio_interface_set_interface (unsigned char interface_type)
Set which radio interface is used, saves it in the radio_settings struct.
void radio_interface_set_baudrate (unsigned char baudrate)
Set which baudrate setting is used, saves it in the radio_settings struct.
void radio_interface_set_stopbits (unsigned char stopbits)
Set which number of stopbits should be used, saves it in the radio_settings struct.
void radio_interface_set_civ_addr (unsigned char civ)
Set which CI-V address the radio has got, saves it in the radio_settings struct.
void radio_interface_set_ptt_input (unsigned char ptt_input)
Set which PTT input that is used, saves it in the radio_settings struct.
void radio_interface_set_poll_interval (unsigned char poll_interval)
Set the poll intervall for the radio band decoding, saves it in the radio_settings struct.
unsigned char radio_interface_get_model (void)
Get which radio model is used.
unsigned char radio_interface_get_interface (void)
Get which radio interface is used.
unsigned char radio_interface_get_baudrate (void)
Get which baudrate setting is used.
unsigned char radio_interface_get_stopbits (void)
Get which number of stopbits should be used.
unsigned char radio_interface_get_civ_addr (void)
Get which CI-V address the radio has got.
unsigned char radio_interface_get_ptt_input (void)
Get which PTT input that is used.
unsigned char radio_interface_get_poll_interval (void)
Get the poll intervall for the radio band decoding.
void radio_interface_load_eeprom (void)
This function will load data from the eeprom to the radio_settings struct.
void radio_communicaton_timeout (void)
unsigned char radio_get_cat_status (void)
ISR (SIG_USART3_DATA)
ISR (SIG_USART3_RECV)
Interrupt which is called when a byte is received on the UART.
Variables
unsigned char * radio_serial_rx_buffer
Serial receive buffer.
unsigned char * radio_serial_rx_buffer_start
Start address of the serial receive buffer.
struct_radio_status radio_status
Radio status struct.
struct_radio_settings radio_settings
Radio settings struct.
unsigned char radio_flags
Flags to indicate various things which has happened to the radio.
unsigned char ptt_status = 0
Flag which does indicate if the radio is transmitting, amp is active etc.
unsigned char radio_rx_data_counter
External variable of the radio rx data counter used for a timeout.
Detailed Description
Radio interface, such as PTT AMP, PTT Radio, CAT etc.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/radio_interface.c " 
Definition in file radio_interface.c.
Function Documentation
void radio_communicaton_timeout (void)
This function should be called if an timeout has occured on the serial communication. This function will then reset the pointers used for the CAT decoding
Definition at line 415 of file radio_interface.c.
References struct_radio_status::box_sent_request, radio_serial_rx_buffer, and radio_serial_rx_buffer_start.
Referenced by ISR().
unsigned char radio_freq_to_band (unsigned int freq)
Convert a radio frequency (integer) to band data.
Parameters:
freq The frequency as integer
Returns: The band of the frequency sent in as parameter. If band not found then it returns BAND_UNDEFINED
Definition at line 315 of file radio_interface.c.
References band_ctrl_get_high_portion_high(), and band_ctrl_get_low_portion_low().
Referenced by radio_process_tasks().
unsigned char radio_get_band_portion (void)
Get the portion of the band the radio is on.
Returns: Return BAND_HIGH if it's in the higher portion of the band, BAND_LOW if it's the lower portion. If neither then it returns BAND_UNDEFINED
Definition at line 180 of file radio_interface.c.
References band_ctrl_get_high_portion_high(), band_ctrl_get_high_portion_low(), band_ctrl_get_low_portion_high(), band_ctrl_get_low_portion_low(), struct_radio_status::current_band, and struct_radio_status::current_freq.
Referenced by band_ctrl_get_portion(), display_update_radio_freq(), and main().
unsigned char radio_get_cat_status (void)
This function will tell us if the openASC box has sent any request to the radio
Returns: 1 if a request has been sent, 0 otherwise
Definition at line 423 of file radio_interface.c.
References struct_radio_status::box_sent_request.
Referenced by ISR().
unsigned char radio_get_current_band (void)
Retrieve the current band from the radio.
Returns: The radios band
Definition at line 120 of file radio_interface.c.
References struct_radio_status::current_band.
Referenced by event_internal_comm_parse_message(), and main().
unsigned int radio_get_current_freq (void)
Retrieve the frequency from the radio. If it's configured for BCD it just retrieves the freq band The frequency is returned as an integer so for example 21350 means 21 MHz and 350 kHz.
Returns: The frequency as an integer, max freq 65536
Definition at line 113 of file radio_interface.c.
References struct_radio_status::current_freq.
Referenced by display_update_radio_freq().
unsigned char radio_interface_get_baudrate (void)
Get which baudrate setting is used.
Returns: Which baudrate setting is used
Definition at line 380 of file radio_interface.c.
References struct_radio_settings::baudrate.
unsigned char radio_interface_get_civ_addr (void)
Get which CI-V address the radio has got.
Returns: The CI-V address
Definition at line 392 of file radio_interface.c.
References struct_radio_settings::civ_addr.
unsigned char radio_interface_get_interface (void)
Get which radio interface is used.
Returns: The interface type
Definition at line 374 of file radio_interface.c.
References struct_radio_settings::interface_type.
Referenced by band_ctrl_get_portion(), display_update_radio_freq(), event_aux2_button_pressed(), and main().
unsigned char radio_interface_get_model (void)
Get which radio model is used.
Returns: The radio model
Definition at line 368 of file radio_interface.c.
References struct_radio_settings::radio_model.
unsigned char radio_interface_get_poll_interval (void)
Get the poll intervall for the radio band decoding.
Returns: The poll interval in ms/10
Definition at line 404 of file radio_interface.c.
References struct_radio_settings::poll_interval.
Referenced by ISR().
unsigned char radio_interface_get_ptt_input (void)
Get which PTT input that is used.
Returns: Which PTT input that is used
Definition at line 398 of file radio_interface.c.
References struct_radio_settings::ptt_input.
unsigned char radio_interface_get_stopbits (void)
Get which number of stopbits should be used.
Returns: The number of stopbits that are used to interface the radio
Definition at line 386 of file radio_interface.c.
References struct_radio_settings::stopbits.
void radio_interface_set_baudrate (unsigned char baudrate)
Set which baudrate setting is used, saves it in the radio_settings struct.
Parameters:
baudrate Which baudrate setting to use
Definition at line 338 of file radio_interface.c.
References struct_radio_settings::baudrate.
void radio_interface_set_civ_addr (unsigned char civ)
Set which CI-V address the radio has got, saves it in the radio_settings struct.
Parameters:
civ The CI-V address
Definition at line 350 of file radio_interface.c.
References struct_radio_settings::civ_addr.
void radio_interface_set_interface (unsigned char interface_type)
Set which radio interface is used, saves it in the radio_settings struct.
Parameters:
interface_type The interface type
Definition at line 332 of file radio_interface.c.
References struct_radio_settings::interface_type.
void radio_interface_set_model (unsigned char model)
Set which radio model is used, saves it in the radio_settings struct.
Parameters:
model The radio model
Definition at line 326 of file radio_interface.c.
References struct_radio_settings::radio_model.
void radio_interface_set_poll_interval (unsigned char poll_interval)
Set the poll intervall for the radio band decoding, saves it in the radio_settings struct.
Parameters:
poll_interval The poll interval in ms/10
Definition at line 362 of file radio_interface.c.
References struct_radio_settings::poll_interval.
void radio_interface_set_ptt_input (unsigned char ptt_input)
Set which PTT input that is used, saves it in the radio_settings struct.
Parameters:
ptt_input Which PTT input that is used
Definition at line 356 of file radio_interface.c.
References struct_radio_settings::ptt_input.
void radio_interface_set_stopbits (unsigned char stopbits)
Set which number of stopbits should be used, saves it in the radio_settings struct.
Parameters:
stopbits The number of stopbits that are used to interface the radio
Definition at line 344 of file radio_interface.c.
References struct_radio_settings::stopbits.
unsigned int radio_parse_freq (unsigned char * freq_data, unsigned char length, unsigned char radio_model)
Parse the radios frequency.
Parameters:
freq_data The frequency data sent in as an array of characters
length The length of the frequency data
radio_model The type of radio that the freq should be parsed for
Returns: The radios frequency in integer format. So for example 21305 is 21 MHz and 305 kHz.
Definition at line 243 of file radio_interface.c.
References RADIO_MODEL_FT1000, RADIO_MODEL_FT1000MKV, RADIO_MODEL_ICOM, and RADIO_MODEL_KENWOOD.
unsigned char radio_poll_ptt (void)
Polls the status of the PTT input.
Returns: Return RADIO_PTT_ACTIVATE if the radio is PTT and RADIO_PTT_DEACTIVATE if it doesn't
Definition at line 197 of file radio_interface.c.
References RADIO_PTT_DEACTIVE.
unsigned char radio_poll_status (void)
Polls the status of the radio and saves it into the radio_status structure.
Returns: 0 if the poll went OK and 1 if it didn't
Definition at line 205 of file radio_interface.c.
References struct_radio_settings::civ_addr, display_update_radio_freq(), INHIBIT_NOT_OK_TO_SEND_RADIO_TX, INT_COMM_GET_BAND_BCD_STATUS, struct_radio_settings::interface_type, internal_comm_add_tx_message(), main_get_inhibit_state(), RADIO_INTERFACE_BCD, RADIO_INTERFACE_CAT_MON, RADIO_INTERFACE_CAT_POLL, struct_radio_settings::radio_model, RADIO_MODEL_ICOM, and usart3_transmit().
Referenced by main().
void radio_set_current_band (unsigned char band)
Set the current band
Parameters:
band The band we wish to set
Definition at line 191 of file radio_interface.c.
References struct_radio_status::current_band.
Referenced by event_internal_comm_parse_message().