front_panel/sequencer.c File Reference
Sequencer.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include `radio_interface.h`
#include `sequencer.h`
#include `main.h`
#include `led_control.h`
#include `usart.h`
#include `../global.h`
#include `../event_queue.h`
#include `antenna_ctrl.h`
#include `eeprom.h`
Defines
#define PTT_ACTIVE_FOOTSWITCH 0
The footswitch PTT input is active.
#define PTT_ACTIVE_RADIO_SENSE 1
The radio sense PTT input is active.
#define PTT_ACTIVE_COMPUTER_RTS 2
The computer PTT input is active.
Functions
unsigned char sequencer_get_ptt_active (void)
Retrieve which PTT inputs that are currently active, defines above.
void sequencer_load_eeprom (void)
This function will load data from the eeprom to the ptt_sequencer struct.
void sequencer_footsw_pressed (void)
Function to be called if the footswitch is pressed.
void sequencer_footsw_released (void)
Function to be called if the footswitch is released.
void sequencer_computer_rts_activated (void)
Function to be called if the computer rts is activated.
void sequencer_computer_rts_deactivated (void)
Function to be called if the computer rts is deactivated.
void sequencer_radio_sense_activated (void)
Function to be called if the radio sense input is activated.
void sequencer_radio_sense_deactivated (void)
Function to be called if the radio sense input is deactivated.
unsigned char sequencer_get_rts_polarity ()
Retrieve the polarity of the Computer RTS signal.
unsigned char sequencer_get_sense_polarity ()
Retrieve the polarity of the radio sense signal.
unsigned char sequencer_ptt_active (void)
Will return if the PTT is active or not.
unsigned char sequencer_get_radio_sense (void)
Retrieve if the radio sense should be sensed from upper floor or bottom.
Variables
unsigned char ptt_active = 0
The status of the PTT, see defines above.
struct_ptt ptt_sequencer
PTT sequencer data.
Detailed Description
Sequencer.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/sequencer.c" 
Definition in file sequencer.c.
Function Documentation
unsigned char sequencer_get_radio_sense (void)
Retrieve if the radio sense should be sensed from upper floor or bottom.
Returns: 0 if lower floor, 1 if upper floor
Definition at line 231 of file sequencer.c.
References struct_ptt::ptt_input, and PTT_INPUT_RADIO_SENSE_UP.
Referenced by event_parse_ext_event().
unsigned char sequencer_get_rts_polarity (void)
Retrieve the polarity of the Computer RTS signal.
Returns: 1 if the polarity is active low (inverted), 0 otherwise
Definition at line 210 of file sequencer.c.
References struct_ptt::ptt_input, and PTT_INPUT_INVERTED_COMPUTER_RTS.
Referenced by event_parse_ext_event().
unsigned char sequencer_get_sense_polarity (void)
Retrieve the polarity of the radio sense signal.
Returns: 1 if the polarity is active low (inverted), 0 otherwise
Definition at line 219 of file sequencer.c.
References struct_ptt::ptt_input, and PTT_INPUT_INVERTED_RADIO_SENSE.
Referenced by event_parse_ext_event().
unsigned char sequencer_ptt_active (void)
Will return if the PTT is active or not.
Returns: The state of the ptt_active variable, 0 if nothing is PTTing the radio
Definition at line 225 of file sequencer.c.
References ptt_active.