front_panel/sub_menu.c File Reference
Antenna sub menu functions.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <string.h>
#include `sub_menu.h`
#include `antenna_ctrl.h`
#include `main.h`
#include `eeprom.h`
#include `band_ctrl.h`
#include `../global.h`
#include `../internal_comm.h`
#include `../wmv_bus/bus.h`
#include `../wmv_bus/bus_rx_queue.h`
#include `../wmv_bus/bus_tx_queue.h`
#include `../wmv_bus/bus_commands.h`
Functions
void sub_menu_load (unsigned char band_index)
Load a set of sub menu from the EEPROM for a specific band.
unsigned char * sub_menu_get_text (unsigned char ant_index, unsigned char pos)
Get the text for the sub menu.
unsigned char sub_menu_get_current_pos (unsigned char ant_index)
Get the current position of the sub menu cursor.
void sub_menu_set_current_pos (unsigned char ant_index, unsigned char new_pos)
Set the current sub menu option.
unsigned char sub_menu_get_count (void)
Get the number of antennas which has got a sub menu configured.
unsigned char sub_menu_get_type (unsigned char ant_index)
Get the sub menu type of an antenna.
void sub_menu_pos_down (unsigned char ant_index)
This function should be called when we wish to decrease the selected sub menu option.
void sub_menu_pos_up (unsigned char ant_index)
This function should be called when we wish to increase the selected sub menu option.
void sub_menu_send_data_to_bus (unsigned char ant_index, unsigned char pos)
Send the output string for the sub menu position to the bus.
void sub_menu_deactivate_all (void)
Will deactivate all currently selected outputs which has been sent out on the bus.
void sub_menu_activate_all (void)
This function will go through the sub menus and if there is one configured it will activae its default option which is index 0.
Variables
struct_sub_menu_array current_sub_menu_array [4]
Current sub menu array.
unsigned char curr_option_selected [4] = {0,0,0,0}
Which option is currently selected of the sub menu options.
unsigned char current_activated_sub_outputs [4][SUB_MENU_ARRAY_STR_SIZE]
Array which we store the current devices which we have activated antenna outputs on.
unsigned char current_activated_sub_outputs_length [4] = {0,0,0,0}
How many devices we have activated antenna outputs on.
Detailed Description
Antenna sub menu functions.
Antenna sub menu functions
Author: Mikael Larsmark, SM2WMV
Date: 2010-04-28
 #include "front_panel/sub_menu.c" 
Definition in file sub_menu.c.
Function Documentation
unsigned char sub_menu_get_count (void)
Get the number of antennas which has got a sub menu configured.
Returns: The number of antennas which has got sub menus, (0-4)
Definition at line 101 of file sub_menu.c.
References antenna_ctrl_get_sub_menu_type(), and SUBMENU_NONE.
Referenced by event_sub_button_pressed().
unsigned char sub_menu_get_current_pos (unsigned char ant_index)
Get the current position of the sub menu cursor.
Parameters:
ant_index The antenna index, (0-3)
Returns: The cursor position of the sub menu
Definition at line 88 of file sub_menu.c.
References curr_option_selected.
Referenced by display_rotator_directions(), display_show_sub_menu(), main(), sub_menu_pos_down(), and sub_menu_pos_up().
unsigned char* sub_menu_get_text (unsigned char ant_index, unsigned char pos)
Get the text for the sub menu.
Parameters:
ant_index The antenna index we wish to get the antenna text for
pos Which sub menu position to show
Returns: Returns the text of the sub menu antenna index
Definition at line 77 of file sub_menu.c.
References antenna_ctrl_get_sub_menu_type(), and SUBMENU_VERT_ARRAY.
Referenced by display_rotator_directions(), and display_show_sub_menu().
unsigned char sub_menu_get_type (unsigned char ant_index)
Get the sub menu type of an antenna.
Parameters:
ant_index The antenna we wish to get the sub menu type of, (0-3)
Returns: The sub meny type of the antenna
Definition at line 114 of file sub_menu.c.
References antenna_ctrl_get_sub_menu_type().
Referenced by event_pulse_sensor_down(), event_pulse_sensor_up(), sub_menu_pos_down(), and sub_menu_pos_up().
void sub_menu_load (unsigned char band_index)
Load a set of sub menu from the EEPROM for a specific band.
Parameters:
band_index Which we band
Definition at line 60 of file sub_menu.c.
References antenna_ctrl_get_sub_menu_type(), curr_option_selected, eeprom_get_ant_sub_menu_array_structure(), and SUBMENU_VERT_ARRAY.
Referenced by band_ctrl_load_band().
void sub_menu_pos_down (unsigned char ant_index)
This function should be called when we wish to decrease the selected sub menu option.
Parameters:
ant_index Which antenna we wish to decrease the sub menu position of
Definition at line 120 of file sub_menu.c.
References sub_menu_get_current_pos(), sub_menu_get_type(), sub_menu_set_current_pos(), and SUBMENU_VERT_ARRAY.
Referenced by event_pulse_sensor_down().
void sub_menu_pos_up (unsigned char ant_index)
This function should be called when we wish to increase the selected sub menu option.
Parameters:
ant_index Which antenna we wish to increase the sub menu position of
Definition at line 131 of file sub_menu.c.
References sub_menu_get_current_pos(), sub_menu_get_type(), sub_menu_set_current_pos(), and SUBMENU_VERT_ARRAY.
Referenced by event_pulse_sensor_up().
void sub_menu_send_data_to_bus (unsigned char ant_index, unsigned char pos)
Send the output string for the sub menu position to the bus.
Parameters:
ant_index The index of the antenna you wish to send the string of
pos The sub menu position we wish to send the output str of
Definition at line 144 of file sub_menu.c.
References antenna_ctrl_deactivate_outputs(), bus_add_tx_message(), BUS_CMD_DRIVER_ACTIVATE_SUBMENU_ANT1_OUTPUT, BUS_CMD_DRIVER_ACTIVATE_SUBMENU_ANT2_OUTPUT, BUS_CMD_DRIVER_ACTIVATE_SUBMENU_ANT3_OUTPUT, BUS_CMD_DRIVER_ACTIVATE_SUBMENU_ANT4_OUTPUT, BUS_CMD_DRIVER_DEACTIVATE_ALL_SUBMENU_ANT1_OUTPUTS, BUS_CMD_DRIVER_DEACTIVATE_ALL_SUBMENU_ANT2_OUTPUTS, BUS_CMD_DRIVER_DEACTIVATE_ALL_SUBMENU_ANT3_OUTPUTS, BUS_CMD_DRIVER_DEACTIVATE_ALL_SUBMENU_ANT4_OUTPUTS, BUS_CMD_DRIVER_DEACTIVATE_SUBMENU_ANT1_OUTPUT, BUS_CMD_DRIVER_DEACTIVATE_SUBMENU_ANT2_OUTPUT, BUS_CMD_DRIVER_DEACTIVATE_SUBMENU_ANT3_OUTPUT, BUS_CMD_DRIVER_DEACTIVATE_SUBMENU_ANT4_OUTPUT, bus_get_address(), BUS_MESSAGE_FLAGS_NEED_ACK, current_activated_sub_outputs, current_activated_sub_outputs_length, internal_comm_add_tx_message(), OUTPUT_ADDR_DELIMITER, struct_sub_menu_array::output_str_dir, and struct_sub_menu_array::output_str_dir_length.
Referenced by main(), and sub_menu_activate_all().
void sub_menu_set_current_pos (unsigned char ant_index, unsigned char new_pos)
Set the current sub menu option.
Parameters:
ant_index The antenna index (0-3)
new_pos The position we wish to chose
Definition at line 95 of file sub_menu.c.
References curr_option_selected.
Referenced by sub_menu_pos_down(), and sub_menu_pos_up().