event_queue.h File Reference
Event queue.
Classes
struct EVENT_MESSAGE
Event message used for timing of events.
Defines
#define EVENT_LIST_SIZE 10
The size of the event list.
Functions
void event_queue_init (void)
Initialize the event queue.
char event_queue_add (EVENT_MESSAGE event)
Insert a message into the event queue. It will end up on a position based on it's time_target.
EVENT_MESSAGE event_queue_get (void)
Retrieve the first message from the event queue.
void event_queue_drop (void)
Drops the first message in the queue.
unsigned char event_queue_count (void)
Retrieve the number of items in the event queue.
void event_queue_dropall (void)
Erase all content in the event queue.
unsigned char event_in_queue (void)
Checks if there is any event in the queue.
void event_queue_wrap (unsigned int remove_val)
Removes a certain amount of numbers from the time_target.
int event_queue_drop_id (unsigned char id)
Drops all messages in the queue with a certain ID.
unsigned char event_queue_check_id (unsigned char id)
Check if a specific ID exist in the event queue.
Variables
EVENT_MESSAGE event_list [EVENT_LIST_SIZE]
Event list with size EVENT_LIST_SIZE.
Detailed Description
Event queue.
Definition in file event_queue.h.
Function Documentation
unsigned char event_in_queue (void)
Checks if there is any event in the queue.
Returns: 1 if there is an event in the queue and 0 otherwise
Definition at line 85 of file event_queue.c.
References event_list.
Referenced by event_add_message(), event_run(), and ISR().
char event_queue_add (EVENT_MESSAGE event)
Insert a message into the event queue. It will end up on a position based on it's time_target.
Parameters:
event - The event that should be inserted into the queue
Returns: The position the event was inserted into, -1 means queue was full
Definition at line 43 of file event_queue.c.
References event_list, EVENT_LIST_SIZE, and EVENT_MESSAGE::time_target.
Referenced by event_add_message().
unsigned char event_queue_check_id (unsigned char id)
Check if a specific ID exist in the event queue.
Parameters:
id The id we which to check for
Returns: 1 if it exist, 0 if it doesn't
Definition at line 155 of file event_queue.c.
References event_list, and EVENT_LIST_SIZE.
unsigned char event_queue_count (void)
Retrieve the number of items in the event queue.
Returns: Numbers of items in the queue
Definition at line 104 of file event_queue.c.
References event_list, and EVENT_LIST_SIZE.
int event_queue_drop_id (unsigned char id)
Drops all messages in the queue with a certain ID.
Returns: the number of events that were dropped
Definition at line 126 of file event_queue.c.
References event_list, EVENT_LIST_SIZE, EVENT_MESSAGE::func, EVENT_MESSAGE::id, and EVENT_MESSAGE::time_target.
Referenced by sequencer_computer_rts_deactivated(), and sequencer_footsw_released().
EVENT_MESSAGE event_queue_get (void)
Retrieve the first message from the event queue.
Returns: The first message in the queue
Definition at line 78 of file event_queue.c.
References event_list.
Referenced by event_run(), and ISR().
void event_queue_wrap (unsigned int remove_val)
Removes a certain amount of numbers from the time_target.
Parameters:
remove_val The number we want to remove from all time targets
Definition at line 69 of file event_queue.c.
References event_list, EVENT_LIST_SIZE, and EVENT_MESSAGE::time_target.
Referenced by ISR().