front_panel/event_handler.h File Reference
Event handler of various things.
#include `../wmv_bus/bus.h`
#include `../wmv_bus/bus_rx_queue.h`
#include `../wmv_bus/bus_tx_queue.h`
#include `../wmv_bus/bus_commands.h`
#include `../internal_comm.h`
#include `../internal_comm_commands.h`
Defines
#define KEYPAD_BTN_1 0x69
External keyboard keycode for Button 1.
#define KEYPAD_BTN_2 0x72
External keyboard keycode for Button 2.
#define KEYPAD_BTN_3 0x7A
External keyboard keycode for Button 3.
#define KEYPAD_BTN_4 0x6B
External keyboard keycode for Button 4.
#define KEYPAD_BTN_5 0x73
External keyboard keycode for Button 5.
#define KEYPAD_BTN_6 0x74
External keyboard keycode for Button 6.
#define KEYPAD_BTN_7 0x6C
External keyboard keycode for Button 7.
#define KEYPAD_BTN_8 0x75
External keyboard keycode for Button 8.
#define KEYPAD_BTN_9 0x7D
External keyboard keycode for Button 9.
#define KEYPAD_BTN_0 0x70
External keyboard keycode for Button 0.
#define KEYPAD_BTN_A 0x77
External keyboard keycode for Button A.
#define KEYPAD_BTN_B 0x4A
External keyboard keycode for Button B.
#define KEYPAD_BTN_C 0x7C
External keyboard keycode for Button C.
#define KEYPAD_BTN_D 0x7B
External keyboard keycode for Button D.
#define KEYPAD_BTN_E 0x79
External keyboard keycode for Button E.
#define KEYPAD_BTN_F 0x5A
External keyboard keycode for Button F.
#define KEYPAD_BTN_G 0x71
External keyboard keycode for Button G.
#define EXT_CTRL_SEL_NONE 0
Ext ctrl - No function assigned.
#define EXT_CTRL_SEL_RX_ANT1 1
Ext ctrl - Set RX antenna #1.
#define EXT_CTRL_SEL_RX_ANT2 2
Ext ctrl - Set RX antenna #2.
#define EXT_CTRL_SEL_RX_ANT3 3
Ext ctrl - Set RX antenna #3.
#define EXT_CTRL_SEL_RX_ANT4 4
Ext ctrl - Set RX antenna #4.
#define EXT_CTRL_SEL_RX_ANT5 5
Ext ctrl - Set RX antenna #5.
#define EXT_CTRL_SEL_RX_ANT6 6
Ext ctrl - Set RX antenna #6.
#define EXT_CTRL_SEL_RX_ANT7 7
Ext ctrl - Set RX antenna #7.
#define EXT_CTRL_SEL_RX_ANT8 8
Ext ctrl - Set RX antenna #8.
#define EXT_CTRL_SEL_RX_ANT9 9
Ext ctrl - Set RX antenna #9.
#define EXT_CTRL_SEL_RX_ANT10 10
Ext ctrl - Set RX antenna #10.
#define EXT_CTRL_TOGGLE_TX_ANT1 9
Ext ctrl - Toggle TX antenna combination #1.
#define EXT_CTRL_TOGGLE_TX_ANT2 10
Ext ctrl - Toggle TX antenna combination #2.
#define EXT_CTRL_TOGGLE_TX_ANT3 11
Ext ctrl - Toggle TX antenna combination #3.
#define EXT_CTRL_TOGGLE_TX_ANT4 12
Ext ctrl - Toggle TX antenna combination #4.
#define EXT_CTRL_TOGGLE_RX_ANT1 13
Ext ctrl - Toggle RX antenna combination #1.
#define EXT_CTRL_TOGGLE_RX_ANT2 14
Ext ctrl - Toggle RX antenna combination #2.
#define EXT_CTRL_TOGGLE_RX_ANT3 15
Ext ctrl - Toggle RX antenna combination #3.
#define EXT_CTRL_TOGGLE_RX_ANT4 16
Ext ctrl - Toggle RX antenna combination #4.
#define EXT_CTRL_TOGGLE_RX_ANT_MODE 17
Ext ctrl - Toggle RX antenna enabled.
#define EXT_CTRL_TOGGLE_TXRX_MODE 18
Ext ctrl - Toggle TX/RX mode on/off.
#define EXT_CTRL_SET_ARRAY_DIR1 19
Ext ctrl - Select array direction #1.
#define EXT_CTRL_SET_ARRAY_DIR2 20
Ext ctrl - Select array direction #2.
#define EXT_CTRL_SET_ARRAY_DIR3 21
Ext ctrl - Select array direction #3.
#define EXT_CTRL_SET_ARRAY_DIR4 22
Ext ctrl - Select array direction #4.
#define EXT_CTRL_SET_ARRAY_DIR5 23
Ext ctrl - Select array direction #5.
#define EXT_CTRL_SET_ARRAY_DIR6 24
Ext ctrl - Select array direction #6.
#define EXT_CTRL_SET_ARRAY_DIR7 25
Ext ctrl - Select array direction #7.
#define EXT_CTRL_SET_ARRAY_DIR8 26
Ext ctrl - Select array direction #8.
#define EXT_CTRL_SET_STACK_COMB1 27
Ext ctrl - Select stack combo #1.
#define EXT_CTRL_SET_STACK_COMB2 28
Ext ctrl - Select stack combo #2.
#define EXT_CTRL_SET_STACK_COMB3 29
Ext ctrl - Select stack combo #3.
#define EXT_CTRL_SET_STACK_COMB4 30
Ext ctrl - Select stack combo #4.
#define EXT_CTRL_SET_STACK_COMB5 31
Ext ctrl - Select stack combo #5.
#define EXT_CTRL_SET_STACK_COMB6 32
Ext ctrl - Select stack combo #6.
#define EXT_CTRL_AMPLIFIER_TOGGLE_ON_OFF 33
Ext ctrl - Toggle the amplifier on/off.
#define EXT_CTRL_AMPLIFIER_TOGGLE_STANDBY 34
Ext ctrl - Toggle the amplifier standby.
#define EXT_CTRL_AMPLIFIER_TUNE 35
Ext ctrl - Tune the amplifier to the correct band.
#define EXT_CTRL_AMPLIFIER_RESET 36
Ext ctrl - Reset the amplifier.
Functions
void event_set_error (unsigned char error_type, unsigned char state)
Set that an error has occured.
unsigned char event_get_errors (void)
Retrieve the state error flags.
unsigned char event_get_error_state (unsigned char error_type)
Retrieve the state of a specific error type.
void event_internal_comm_parse_message (UC_MESSAGE message)
Function which will parse the internal communication message.
void event_handler_process_ps2 (unsigned char key_code)
Process an PS2 event.
void event_pulse_sensor_up (void)
The pulse sensor was turned up.
void event_pulse_sensor_down (void)
The pulse sensor was turned down.
void event_update_display (void)
Function to be called if we wish to update the display.
void event_poll_buttons (void)
Function which will poll all buttons and perform the proper action depending on their state.
void event_poll_ext_device (void)
Function which will poll the external devices and perform the proper actions depending on their state.
void event_bus_parse_message (void)
Parse a message from the communication bus.
void event_parse_ext_event (unsigned int ext_event_status)
Parse an external event and perform the proper action.
void event_sub_button_pressed (void)
Perform the actions that should be done when the SUB menu button is pressed.
void event_tx_button1_pressed (void)
Perform the action of TX antenna button 1 if it was pressed.
void event_tx_button2_pressed (void)
Perform the action of TX antenna button 2 if it was pressed.
void event_tx_button3_pressed (void)
Perform the action of TX antenna button 3 if it was pressed.
void event_tx_button4_pressed (void)
Perform the action of TX antenna button 4 if it was pressed.
void event_rotate_button_pressed (void)
Perform the action of Rotate button if it was pressed.
void event_rxant_button_pressed (void)
Perform the action of RX antenna button if it was pressed.
void event_aux2_button_pressed (void)
Perform the actions that should be done when AUX 2 button is pressed.
void __inline__ event_set_rx_antenna (unsigned char ant_index)
Set an RX antenna. Will set the proper flags and call the antenna_ctrl_change_rx_ant function.
Detailed Description
Event handler of various things.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/event_handler.h" 
Definition in file event_handler.h.
Function Documentation
unsigned char event_get_error_state (unsigned char error_type)
Retrieve the state of a specific error type.
Parameters:
error_type Which kind of error we wish to check the state for
Returns: The current state of this error
Definition at line 82 of file event_handler.c.
References flag_errors.
void event_handler_process_ps2 (unsigned char key_code)
Process an PS2 event.
Parameters:
key_code The key that was pressed
Definition at line 149 of file event_handler.c.
References event_rxant_button_pressed(), event_set_rx_antenna(), event_tx_button1_pressed(), event_tx_button2_pressed(), event_tx_button3_pressed(), event_tx_button4_pressed(), EXT_CTRL_SEL_NONE, EXT_CTRL_SEL_RX_ANT1, EXT_CTRL_SEL_RX_ANT10, EXT_CTRL_TOGGLE_RX_ANT_MODE, EXT_CTRL_TOGGLE_TX_ANT1, EXT_CTRL_TOGGLE_TX_ANT2, EXT_CTRL_TOGGLE_TX_ANT3, EXT_CTRL_TOGGLE_TX_ANT4, ext_key_get_assignment(), KEYPAD_BTN_0, KEYPAD_BTN_1, KEYPAD_BTN_2, KEYPAD_BTN_3, KEYPAD_BTN_4, KEYPAD_BTN_5, KEYPAD_BTN_6, KEYPAD_BTN_7, KEYPAD_BTN_8, KEYPAD_BTN_9, KEYPAD_BTN_A, KEYPAD_BTN_B, KEYPAD_BTN_C, KEYPAD_BTN_D, KEYPAD_BTN_E, KEYPAD_BTN_F, and KEYPAD_BTN_G.
Referenced by event_internal_comm_parse_message().
void event_internal_comm_parse_message (UC_MESSAGE message)
Function which will parse the internal communication message.
Parameters:
message The message that we wish to parse
Definition at line 91 of file event_handler.c.
References band_ctrl_change_band(), UC_MESSAGE::cmd, computer_interface_is_active(), struct_status::current_display, CURRENT_DISPLAY_SHUTDOWN_VIEW, UC_MESSAGE::data, display_shutdown_view(), event_add_message(), event_handler_process_ps2(), INT_COMM_GET_BAND_BCD_STATUS, INT_COMM_PC_CTRL, INT_COMM_PS2_KEYPRESSED, INT_COMM_TURN_DEVICE_OFF, main_save_settings(), radio_get_current_band(), radio_set_current_band(), remote_control_parse_command(), send_ping(), shutdown_device(), and status.
Referenced by main().
void event_parse_ext_event (unsigned int ext_event_status)
Parse an external event and perform the proper action.
Parameters:
ext_event_status The status of the external `hardware` event flags
Definition at line 900 of file event_handler.c.
References struct_status::ext_devices_current_state, sequencer_computer_rts_activated(), sequencer_computer_rts_deactivated(), sequencer_footsw_pressed(), sequencer_footsw_released(), sequencer_get_radio_sense(), sequencer_get_rts_polarity(), sequencer_get_sense_polarity(), sequencer_radio_sense_activated(), sequencer_radio_sense_deactivated(), status, STATUS_FOOTSWITCH_BIT, STATUS_RADIO_SENSE1_BIT, STATUS_RADIO_SENSE2_BIT, and STATUS_USB2_RTS_BIT.
Referenced by event_poll_ext_device().
void event_set_error (unsigned char error_type, unsigned char state)
Set that an error has occured.
Parameters:
error_type The type of error that has occured, defines can be found in errors.h
state State of the error
Definition at line 65 of file event_handler.c.
References flag_errors, and main_update_ptt_status().
Referenced by bus_resend_message(), internal_comm_resend(), ISR(), menu_action(), rx_queue_add(), and tx_queue_add().
void __inline__ event_set_rx_antenna (unsigned char ant_index)
Set an RX antenna. Will set the proper flags and call the antenna_ctrl_change_rx_ant function.
Parameters:
ant_index The index of the RX antenna we wish to chose
Definition at line 140 of file event_handler.c.
References antenna_ctrl_change_rx_ant(), FLAG_UPDATE_DISPLAY, main_flags, struct_status::selected_rx_antenna, and status.
Referenced by event_handler_process_ps2().