front_panel/led_control.c File Reference
Front panel LED control functions.
#include <stdio.h>
#include <avr/io.h>
#include `led_control.h`
#include `board.h`
#include `../global.h`
Functions
void led_set_band (unsigned char band)
Set the band LEDs to the proper band.
void led_set_band_none (void)
Turn off all band leds.
void led_set_ptt (enum enum_led_ptt_state state)
Set the PTT LED.
void led_set_error (enum enum_led_state state)
Set the error LED status.
void led_set_rotation_active (enum enum_led_state state)
Set the rotating led to active state, indicates if any antenna on the current band is rotating.
void led_set_tx_ant (unsigned char index, enum enum_led_state state)
Set the TX Antenna LED status.
void led_set_rx_ant (unsigned char index, enum enum_led_state state)
Set the RX Antenna LED status.
void led_set_rotate (enum enum_led_state state)
Set the Rotate LED status.
void led_set_txrx (enum enum_led_state state)
Set the TX/RX mode LED status.
void led_set_rxant (enum enum_led_state state)
Set the RX antenna LED status.
void led_set_aux (enum enum_led_state state)
Set the AUX LED status.
void led_set_menu (enum enum_led_state state)
Set the menu LED status.
void led_set_all (enum enum_led_state state)
Set all the LEDs.
Detailed Description
Front panel LED control functions.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/led_control.c" 
Definition in file led_control.c.
Function Documentation
void led_set_all (enum enum_led_state state)
Set all the LEDs.
Parameters:
state The state of the LED
Definition at line 216 of file led_control.c.
References led_set_aux(), led_set_band(), led_set_error(), led_set_menu(), led_set_ptt(), led_set_rotate(), led_set_rx_ant(), led_set_rxant(), led_set_tx_ant(), led_set_txrx(), LED_STATE_OFF, LED_STATE_ON, LED_STATE_PTT_ACTIVE, and LED_STATE_PTT_OK.
Referenced by main().
void led_set_aux (enum enum_led_state state)
Set the AUX LED status.
Parameters:
state The state of the LED
Definition at line 198 of file led_control.c.
References LED_AUX_BIT, and LED_STATE_ON.
Referenced by led_set_all().
void led_set_band (unsigned char band)
Set the band LEDs to the proper band.
Parameters:
band The band we wish to turn on the LED for
Definition at line 32 of file led_control.c.
Referenced by band_ctrl_change_band(), led_set_all(), and main().
void led_set_error (enum enum_led_state state)
Set the error LED status.
Parameters:
state The state of the LED
Definition at line 67 of file led_control.c.
References LED_ERROR_BIT, and LED_STATE_ON.
Referenced by bus_resend_message(), led_set_all(), and menu_action().
void led_set_menu (enum enum_led_state state)
Set the menu LED status.
Parameters:
state The state of the LED
Definition at line 207 of file led_control.c.
References LED_MENU_BIT, and LED_STATE_ON.
Referenced by event_poll_buttons(), and led_set_all().
void led_set_ptt (enum enum_led_ptt_state state)
Set the PTT LED.
Parameters:
state The state of the LED
Definition at line 47 of file led_control.c.
References LED_PTT_GREEN_BIT, LED_PTT_RED_BIT, LED_STATE_PTT_ACTIVE, LED_STATE_PTT_INHIBIT, and LED_STATE_PTT_OK.
Referenced by led_set_all(), main(), and main_update_ptt_status().
void led_set_rotate (enum enum_led_state state)
Set the Rotate LED status.
Parameters:
state The state of the LED
Definition at line 169 of file led_control.c.
References LED_ROTATE_BIT, and LED_STATE_ON.
Referenced by event_poll_buttons(), event_rxant_button_pressed(), and led_set_all().
void led_set_rotation_active (enum enum_led_state state)
Set the rotating led to active state, indicates if any antenna on the current band is rotating.
Parameters:
state The state of the LED
Definition at line 76 of file led_control.c.
References LED_ROTATION_ACTIVE_BIT, and LED_STATE_ON.
void led_set_rx_ant (unsigned char index, enum enum_led_state state)
Set the RX Antenna LED status.
Parameters:
index Which LED we wish to change the status of
state The state of the LED
Definition at line 128 of file led_control.c.
References LED_RX_BUTTON1_BIT, LED_RX_BUTTON2_BIT, LED_RX_BUTTON3_BIT, LED_RX_BUTTON4_BIT, and LED_STATE_ON.
Referenced by band_ctrl_change_band(), and led_set_all().
void led_set_rxant (enum enum_led_state state)
Set the RX antenna LED status.
Parameters:
state The state of the LED
Definition at line 187 of file led_control.c.
References LED_RXANT_BIT, and LED_STATE_ON.
Referenced by band_ctrl_change_band(), event_rxant_button_pressed(), and led_set_all().
void led_set_tx_ant (unsigned char index, enum enum_led_state state)
Set the TX Antenna LED status.
Parameters:
index Which LED we wish to change the status of
state The state of the LED
Definition at line 86 of file led_control.c.
References LED_STATE_ON, LED_TX_BUTTON1_BIT, LED_TX_BUTTON2_BIT, LED_TX_BUTTON3_BIT, and LED_TX_BUTTON4_BIT.
Referenced by band_ctrl_change_band(), event_tx_button1_pressed(), event_tx_button2_pressed(), event_tx_button3_pressed(), event_tx_button4_pressed(), led_set_all(), and set_tx_ant_leds().
void led_set_txrx (enum enum_led_state state)
Set the TX/RX mode LED status.
Parameters:
state The state of the LED
Definition at line 178 of file led_control.c.
References LED_STATE_ON, and LED_TXRX_BIT.
Referenced by led_set_all().