front_panel/remote_control.h File Reference
Remote control of the openASC box.
Defines
#define REMOTE_CONTROL_ACTIVATE_MODE 0x01
Command to activate the remote control mode.
#define REMOTE_CONTROL_DEACTIVATE_MODE 0x02
Command to deactivate the remote control mode.
#define REMOTE_CONTROL_BUTTON_PRESSED 0x10
A button should be pressed.
#define REMOTE_CONTROL_RX_ANT_TEXT 0x11
Command for sending rx antenna button texts.
Functions
void remote_control_activate_remote_mode (void)
Activate the remote control mode.
void remote_control_deactivate_remote_mode (void)
Deactivate the remote control mode.
unsigned char remote_control_get_remote_mode (void)
Get the current remote control mode.
void remote_control_parse_command (unsigned char command, unsigned char length, char *data)
Parse a remote control command and perform the proper action.
void remote_control_parse_button (unsigned char button)
Parse a button press event, will perform an action depending on which button we wish to press.
Detailed Description
Remote control of the openASC box.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/remote_control.h" 
Definition in file remote_control.h.
Function Documentation
unsigned char remote_control_get_remote_mode (void)
Get the current remote control mode.
Returns: 1 if remote mode is active, 0 if it is not active
Definition at line 50 of file remote_control.c.
References FLAG_REMOTE_CONTROL_MODE_ACTIVE, and remote_control_flags.
void remote_control_parse_button (unsigned char button)
Parse a button press event, will perform an action depending on which button we wish to press.
Parameters:
button The button we wish to press
Definition at line 56 of file remote_control.c.
Referenced by remote_control_parse_command().
void remote_control_parse_command (unsigned char command, unsigned char length, char * data)
Parse a remote control command and perform the proper action.
Parameters:
command The command we wish to parse
length The length of the data
data The data content
Definition at line 67 of file remote_control.c.
References REMOTE_CONTROL_ACTIVATE_MODE, remote_control_activate_remote_mode(), REMOTE_CONTROL_BUTTON_PRESSED, REMOTE_CONTROL_DEACTIVATE_MODE, remote_control_deactivate_remote_mode(), and remote_control_parse_button().
Referenced by event_internal_comm_parse_message().