/*****************************************************************************
* Model: pasm.qm
* File:  ./pasm.h
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
/* @(/1/0) .................................................................*/
typedef struct PaTag {
/* protected: */
    QActive super;

/* private: */
    uint8_t op_status;
    uint8_t band;
    uint8_t ctrlr;
} Pa;

/* protected: */
QState Pa_initial(Pa *me);
QState Pa_PowerOff(Pa *me);
QState Pa_PowerOn(Pa *me);
QState Pa_Warmup(Pa *me);
QState Pa_Operational(Pa *me);
QState Pa_Transmitting(Pa *me);
QState Pa_Unused(Pa *me);
QState Pa_Ready(Pa *me);
QState Pa_Cooldown(Pa *me);

