wmv_bus/bus_tx_queue.c File Reference
FIFO queue for the TXed messages.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include `bus_tx_queue.h`
#include `bus.h`
Functions
void tx_queue_init (void)
Initialize the TX queue.
void tx_queue_add (BUS_MESSAGE message)
Insert a message into the TX queue (FIFO).
BUS_MESSAGE tx_queue_get (void)
Retrieve the first message from the FIFO TX queue.
void tx_queue_drop (void)
void tx_queue_dropall (void)
Erase all content in the TX queue.
unsigned char tx_queue_is_empty (void)
Check if the queue is empty.
unsigned char tx_queue_size (void)
Get how much of the TX queue that is currently being used.
Variables
unsigned char bus_tx_queue_size
Variable that keeps track of how much of the TX queue that is being used.
tx_queue_struct tx_queue
The tx queue.
Detailed Description
FIFO queue for the TXed messages.
FIFO queue for the TXed messages.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "wmv_bus/bus_tx_queue.c" 
Definition in file bus_tx_queue.c.
Function Documentation
void tx_queue_add (BUS_MESSAGE message)
Insert a message into the TX queue (FIFO).
Parameters:
message - The message that should be inserted to the queue
Definition at line 56 of file bus_tx_queue.c.
References BUS_TX_QUEUE_SIZE, bus_tx_queue_size, ERROR_TYPE_BUS_TX_QUEUE_FULL, event_set_error(), tx_linked_list::first, tx_linked_list::last, led_set_error(), LED_STATE_ON, and tx_linked_list::message.
Referenced by bus_add_tx_message().
void tx_queue_drop (void)
Drops the first message in the queue Frees up the memory space aswell.
Definition at line 93 of file bus_tx_queue.c.
References BUS_TX_QUEUE_SIZE, bus_tx_queue_size, and tx_linked_list::first.
Referenced by bus_message_acked(), bus_resend_message(), and bus_send_message().
void tx_queue_dropall (void)
Erase all content in the TX queue.
Returns: The number of items that were cleared
Definition at line 104 of file bus_tx_queue.c.
References bus_tx_queue_size, tx_linked_list::first, and tx_linked_list::last.
Referenced by ISR(), and main().
BUS_MESSAGE tx_queue_get (void)
Retrieve the first message from the FIFO TX queue.
Returns: The first message in the queue
Definition at line 86 of file bus_tx_queue.c.
References tx_linked_list::first, and tx_linked_list::message.
Referenced by bus_message_acked(), bus_message_nacked(), and bus_send_message().
unsigned char tx_queue_is_empty (void)
Check if the queue is empty.
Returns: 1 if the queue is empty and 0 otherwise
Definition at line 112 of file bus_tx_queue.c.
References tx_linked_list::first, and tx_linked_list::last.
Referenced by main().
unsigned char tx_queue_size (void)
Get how much of the TX queue that is currently being used.
Returns: How much of the queue is being used
Definition at line 121 of file bus_tx_queue.c.
References bus_tx_queue_size.