front_panel/main.h File Reference
Main file of the front panel.
Classes
struct struct_setting
Settings struct.
struct struct_status
This struct only contains information that is temporary.
struct struct_runtime_settings
Settings like status but which should be saved into the EEPROM.
Defines
#define FIRMWARE_REV `0.1b\0`
The current firmware revision nr.
#define ENABLE_TIMER0_INT() TIMSK0 |= (1<<OCIE0A);
Macro to enable timer 0 interrupt.
#define DISABLE_TIMER0_INT() TIMSK0 &= ~(1<<OCIE0A);
Macro to disable timer 0 interrupt.
#define BUS_STATUS_ALLOWED_TO_SEND_BIT 0
Flag to indicate that the bus is allowed to transmit.
#define BUS_STATUS_PREAMBLE_FOUND_BIT 1
Flag to indicate that a preamble has been found in the bus.
#define BUS_RX_QUEUE_SIZE 10
The size of the RX queue in buffers.
#define BUS_TX_QUEUE_SIZE 25
The size of the TX queue in buffers.
#define ANTENNA_EXIST_FLAG 0
This flag is to indicate that the antenna exist.
#define ANTENNA_ROTATOR_FLAG 1
Flag if there is a rotator that can be controlled.
#define ANTENNA_IS_MULTIBAND 2
Flag if the antenna is a multiband antenna - Not implemented.
#define ANTENNA_IN_USE_FLAG 3
Flag that shows if an antenna is occupied, used for multiband antennas primary - Not implemented.
#define DISPLAY_SCREENSAVER_TIMEOUT 5000
Screensaver timeout.
#define RADIO_RX_DATA_TIMEOUT 10
#define PTT_RADIO_BIT 0
Indicate that radio is enabled or disabled.
#define PTT_AMP_BIT 1
Indicate that amp is enabled or disabled.
#define INHIBIT_ENABLED_BIT 2
Indicate that inhibit is enabled or disabled.
#define BAND_CHANGE_MODE_MANUAL 0
Band changes are done manually.
#define BAND_CHANGE_MODE_AUTO 1
Band changes are done automatically.
#define FLAG_POLL_BUTTONS 0
POLL BUTTONS, is set when a poll on the front panel buttons should occur.
#define FLAG_POLL_EXT_DEVICES 1
EXT DEVICES flag is set when a poll for external devices should occur.
#define FLAG_RUN_EVENT_QUEUE 2
Run the event first in the event queue.
#define FLAG_UPDATE_DISPLAY 3
FLAG to indicate that the display should be updated.
#define FLAG_POLL_PULSE_SENSOR 4
Poll the pulse sensor.
#define FLAG_LAST_BAND_BLINK 5
This flag indicates the state of the last BAND blink event, used to blink the LED when a new band change is in process.
#define FLAG_LAST_ANTENNA_BLINK 6
This flag is used to blink the antennas which can be rotated.
#define FLAG_CHANGE_RX_ANT 7
This flag is used to trigger an RX antenna change, after a certain amount of time which is set with the flag below.
#define FLAG_PROCESS_RX_ANT_CHANGE 8
Works together with the above flag, but this is set when the actual antenna change should occur.
#define FLAG_BLINK_BAND_LED 9
Blink the band led.
#define FLAG_POLL_RADIO 10
Indicate that we should poll the radio.
#define FLAG_CHANGE_SUBMENU 11
This flag is set to indicate that we have changed the sub menu.
#define FLAG_PROCESS_SUBMENU_CHANGE 12
This flag is to indicate that a sub menu change should occur, ie sent out on the bus.
#define INTERVAL_POLL_BUTTONS 50
The poll interval of the front panel buttons (unit = ms).
#define INTERVAL_POLL_ROTARY_ENCODER 5
The poll interval of the rotary encoder (unit = ms).
#define INTERVAL_POLL_EXT_DEVICES 1
The poll interval of the external devices as shown in board.h (unit = ms).
#define KNOB_FUNCTION_NONE 0
Knob function is to select RX antenna.
#define KNOB_FUNCTION_RX_ANT 1
Knob function is to select RX antenna.
#define KNOB_FUNCTION_SELECT_BAND 2
Knob function is to select band.
#define KNOB_FUNCTION_SET_HEADING 3
Knob function is to set the heading of a rotator.
#define KNOB_FUNCTION_AUTO 4
Auto select, pick the one which is most likely to be used.
#define KNOB_FUNCTION_SET_SUBMENU 5
Knob function set submenu option.
#define RX_ANTENNA_NAME_LENGTH 15
RX antenna name length.
#define RX_ANTENNA_OUTPUT_STR_LENGTH 10
RX antenna output str length.
#define RX_ANTENNA_BAND_OUTPUT_STR_LENGTH 10
RX antenna band output str length.
#define ANTENNA_TEXT_SIZE 10
The max size of the antenna output str length.
#define ANTENNA_OUTPUT_COMB_SIZE 10
The max size of the output combination length.
#define BAND_OUTPUT_STR_SIZE 10
The max size of the band output str.
#define SUB_MENU_ARRAY_STR_SIZE 10
The max size of the sub menu array output str size.
#define SUB_MENU_ARRAY_NAME_SIZE 3
The size of the name of a 4-SQ.
#define OUTPUT_ADDR_DELIMITER 0xFF
The delimiter that seperates the outputs from which address they should be sent to.
#define FUNC_STATUS_RXANT 0
Define for function status.
#define FUNC_STATUS_ROTATE 1
Define for function status, that rotation is active.
#define FUNC_STATUS_SELECT_ANT_ROTATE 2
Define for function status, to select which antenna that should be rotated.
#define FUNC_STATUS_SUBMENU 3
Define for function status, to select sub menu.
#define DISPLAY_LEVEL_LOGO 0
Display level openASC logo.
#define DISPLAY_LEVEL_BAND 1
Display level current band.
#define DISPLAY_LEVEL_SUBMENU 2
Display level sub menu.
#define CURRENT_DISPLAY_LOGO 0
Current display is the openASC logo.
#define CURRENT_DISPLAY_ANTENNA_INFO 1
Current display is the antenna information.
#define CURRENT_DISPLAY_MENU_SYSTEM 2
Current display is the menu system.
#define CURRENT_DISPLAY_SHUTDOWN_VIEW 3
Current display is the shutdown in progress view.
#define CURRENT_DISPLAY_POWERMETER_VIEW 4
Current display power meter view.
#define PULSE_SENSOR_RX_ANT_CHANGE_LIMIT 250
The time from when a pulse sensor change occured to the actual change does happen, in ms.
#define PULSE_SENSOR_SUBMENU_CHANGE_LIMIT 250
The time from when a pulse sensor change occured to the actual change does happen, in ms.
#define SUBMENU_NONE 0
Sub menu type NONE.
#define SUBMENU_VERT_ARRAY 1
Sub menu type 4-SQ.
#define SUBMENU_STACK 2
Sub menu type stack.
#define VIEW_ANTENNAS 0
Flag used if we wish to view antennas.
Enumerations
enum enum_inhibit_state { INHIBIT_OK_TO_SEND,
INHIBIT_NOT_OK_TO_SEND,
INHIBIT_NOT_OK_TO_SEND_RADIO_TX
 }
Different inhibit states.
Functions
void main_update_ptt_status (void)
Function which updates the status of the PTT This function will check various sources if it is for example OK to transmit or not. This function also updates the color of the PTT led. It does also set the main_set_inhibit_state() status which is used at various places to make the sequencing etc safe.
void main_save_settings (void)
Save runtime settings etc to the EEPROM.
void event_add_message (void(*func), unsigned int offset, unsigned char id)
unsigned char ext_key_get_assignment (unsigned char index)
void ext_key_set_assignment (unsigned char index, unsigned char func)
void main_update_display (void)
Sets the flag that the display should be updated.
void check_knob_function (void)
void set_tx_ant_leds (void)
Set the TX antenna leds according to the status of status.selected_ant.
void set_knob_function (unsigned char function)
Set the rotary knob function.
void shutdown_device (void)
Send a message to the motherboard that the openASC box should be shut off. Will deactivate the power supply relay.
enum enum_inhibit_state main_get_inhibit_state (void)
Get the inhibit state This function is used to get the inhibit state, which is used to check at various places if it is safe for example to transmit, change band or change antennas.
void main_set_inhibit_state (enum enum_inhibit_state state)
Set the inhibit state This function is used to set the inhibit state, which is used to check at various places if it is safe for example to transmit, change band or change antennas.
void send_ping (void)
Send a ping message out on the bus.
Variables
struct_status status
Contains different statuses of buttons etc.
struct_runtime_settings runtime_settings
Contains settings which will be saved and restored each time the box is turned on/off.
Detailed Description
Main file of the front panel.
Definition in file main.h.
Define Documentation
#define RADIO_RX_DATA_TIMEOUT 10
The limit (in ms) of the radio communication timeout. If this limit is reached the radio rx buffers will be cleared
Definition at line 58 of file main.h.
Referenced by ISR().
Enumeration Type Documentation
enum enum_inhibit_state
Different inhibit states.
Enumerator:
INHIBIT_OK_TO_SEND
 Inhibit state, OK to start a transmission.
INHIBIT_NOT_OK_TO_SEND
 Inhibit state, NOT OK to start a transmission.
INHIBIT_NOT_OK_TO_SEND_RADIO_TX
 Inhibit state, NOT OK to start a transmission, Radio is in TX.
Definition at line 187 of file main.h.
Function Documentation
void event_add_message (void * func, unsigned int offset, unsigned char id)
Add a message to the event queue which will be run at the correct time
Parameters:
func A function pointer to the function we want to run
offset the time in ms when we want our function to be run
id Which type of event this is
Definition at line 115 of file main.c.
References counter_event_timer, event_in_queue(), and event_queue_add().
Referenced by display_update_screensaver(), event_internal_comm_parse_message(), sequencer_computer_rts_activated(), sequencer_computer_rts_deactivated(), sequencer_footsw_pressed(), and sequencer_footsw_released().
unsigned char ext_key_get_assignment (unsigned char index)
Get the key assignment index
Parameters:
index The index of which task we wish to check
Returns: The current task index, can be found in event_handler.h
Definition at line 131 of file main.c.
References struct_setting::ext_key_assignments.
Referenced by event_handler_process_ps2().
void ext_key_set_assignment (unsigned char index, unsigned char func)
Set the key assignment task
Parameters:
index The index of which task we wish to set
func The function we wish to assign to the assignment index
Definition at line 138 of file main.c.
References struct_setting::ext_key_assignments.
enum enum_inhibit_state main_get_inhibit_state (void)
Get the inhibit state This function is used to get the inhibit state, which is used to check at various places if it is safe for example to transmit, change band or change antennas.
Returns: The current inhibit status
Definition at line 280 of file main.c.
References struct_runtime_settings::inhibit_state, and runtime_settings.
Referenced by band_ctrl_change_band(), event_pulse_sensor_down(), event_pulse_sensor_up(), event_tx_button1_pressed(), event_tx_button2_pressed(), event_tx_button3_pressed(), event_tx_button4_pressed(), radio_poll_status(), sequencer_computer_rts_activated(), and sequencer_footsw_pressed().
void main_set_inhibit_state (enum enum_inhibit_state state)
Set the inhibit state This function is used to set the inhibit state, which is used to check at various places if it is safe for example to transmit, change band or change antennas.
Parameters:
state The state we wish to set the inhibit status to
Definition at line 272 of file main.c.
References struct_runtime_settings::inhibit_state, and runtime_settings.
Referenced by main(), and main_update_ptt_status().
void set_knob_function (unsigned char function)
Set the rotary knob function.
Parameters:
function Which type of action should occur when the knob is turned
Definition at line 178 of file main.c.
References struct_runtime_settings::band_change_mode, BAND_CHANGE_MODE_MANUAL, struct_status::knob_function, KNOB_FUNCTION_AUTO, KNOB_FUNCTION_NONE, KNOB_FUNCTION_SELECT_BAND, runtime_settings, and status.
Referenced by band_ctrl_change_band(), event_poll_buttons(), event_rotate_button_pressed(), event_rxant_button_pressed(), event_sub_button_pressed(), main(), and menu_action().