general_io/main.c File Reference
Main file of the General I/O card.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include `main.h`
#include `board.h`
#include `init.h`
#include `../i2c.h`
#include `../delay.h`
#include `../wmv_bus/bus.h`
#include `../wmv_bus/bus_ping.h`
#include `../wmv_bus/bus_rx_queue.h`
#include `../wmv_bus/bus_tx_queue.h`
#include `../wmv_bus/bus_commands.h`
Functions
void bus_parse_message (void)
Parse a message and exectute the proper commands This function is used to parse a message that was receieved on the bus that is located in the RX queue.
unsigned char read_ext_addr (void)
Read the external DIP-switch. This function is used to read the external offset address on the General I/O card.
int main (void)
ISR (SIG_OUTPUT_COMPARE0)
Output compare 0 interrupt - `called` with 1ms intervals.
Variables
unsigned char device_id
Contains info of the driver type.
unsigned int counter_compare0 = 0
Counter to keep track of the numbers of ticks from timer0.
unsigned int counter_sync = 0
Counter to keep track of the time elapsed since the last sync message was sent.
unsigned int counter_ping_interval = 0
Counter to keep track of when to send a ping out on the bus.
Detailed Description
Main file of the General I/O card.
Author: Mikael Larsmark, SM2WMV
Date: 2010-05-18
 #include "general_io/main.c" 
Definition in file main.c.
Function Documentation
int main (void)
Main function of the General I/O
Definition at line 77 of file main.c.
References bus_add_tx_message(), bus_allowed_to_send(), BUS_BROADCAST_ADDR, bus_check_tx_status(), BUS_CMD_PING, BUS_CMD_SYNC, BUS_DEVICE_STATUS_MESSAGE_INTERVAL, bus_get_address(), bus_get_device_count(), bus_init(), bus_is_master(), BUS_MASTER_SYNC_INTERVAL, bus_parse_message(), bus_set_address(), bus_set_is_master(), counter_ping_interval, counter_sync, DEF_NR_DEVICES, DEFAULT_STARTUP_DELAY, device_count, device_id, DEVICE_ID_GENERAL_IO, init_ports(), init_timer_0(), init_timer_2(), read_ext_addr(), rx_queue_is_empty(), and tx_queue_is_empty().
unsigned char read_ext_addr (void)
Read the external DIP-switch. This function is used to read the external offset address on the General I/O card.
Returns: The address of the external DIP-switch
Definition at line 72 of file main.c.