internal_comm_rx_queue.h File Reference
The internal communication RX QUEUE.
#include `internal_comm.h`
Classes
struct rx_linked_list
The structure of the RX circular buffer.
Defines
#define INTERNAL_COMM_RX_QUEUE_SIZE 5
The size of the RX QUEUE.
Typedefs
typedef struct rx_linked_list int_comm_rx_queue_struct
The structure of the RX circular buffer.
Functions
void int_comm_rx_queue_add (UC_MESSAGE message)
Insert a message into the TX queue (FIFO).
UC_MESSAGE int_comm_rx_queue_get (void)
Retrieve the first message from the FIFO TX queue.
void int_comm_rx_queue_drop (void)
void int_comm_rx_queue_dropall (void)
Erase all content in the TX queue.
void int_comm_rx_queue_init (void)
Initialize the internal comm rx queue.
unsigned char int_comm_rx_queue_is_empty (void)
Check if the queue is empty.
Detailed Description
The internal communication RX QUEUE.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "internal_comm_rx_queue.h" 
Definition in file internal_comm_rx_queue.h.
Function Documentation
void int_comm_rx_queue_add (UC_MESSAGE message)
Insert a message into the TX queue (FIFO).
Parameters:
message - The message that should be inserted to the queue
Definition at line 43 of file internal_comm_rx_queue.c.
References rx_linked_list::first, INTERNAL_COMM_RX_QUEUE_SIZE, rx_linked_list::last, and rx_linked_list::message.
Referenced by ISR().
void int_comm_rx_queue_drop (void)
Drops the first message in the queue Frees up the memory space aswell.
Definition at line 66 of file internal_comm_rx_queue.c.
References rx_linked_list::first, and INTERNAL_COMM_RX_QUEUE_SIZE.
Referenced by internal_comm_poll_rx_queue().
void int_comm_rx_queue_dropall (void)
Erase all content in the TX queue.
Returns: The number of items that were cleared
Definition at line 76 of file internal_comm_rx_queue.c.
References rx_linked_list::first, and rx_linked_list::last.
Referenced by internal_comm_init().
UC_MESSAGE int_comm_rx_queue_get (void)
Retrieve the first message from the FIFO TX queue.
Returns: The first message in the queue
Definition at line 59 of file internal_comm_rx_queue.c.
References rx_linked_list::first, and rx_linked_list::message.
Referenced by internal_comm_poll_rx_queue().
unsigned char int_comm_rx_queue_is_empty (void)
Check if the queue is empty.
Returns: 1 if the queue is empty and 0 otherwise
Definition at line 84 of file internal_comm_rx_queue.c.
References rx_linked_list::first, and rx_linked_list::last.
Referenced by internal_comm_poll_rx_queue().