motherboard/usart.h File Reference
Motherboard USART routines.
#include `../global.h`
Functions
unsigned char poll_usart0_receive (void)
Retrieve one character from the USART0 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
void usart0_init (unsigned int baudrate)
Initiliaze the USART0 for the communication bus This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA2560 baudrate setting.
unsigned char usart0_transmit (unsigned char data)
unsigned char usart0_receive (void)
Retrieve one character from the USART0 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
unsigned char usart0_receive_loopback (void)
The USART0 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
unsigned char usart0_sendstring (char *data, unsigned char length)
Send a string of characters to the USART0 Send a string of characters to the USART used for the communication bus.
unsigned char poll_usart1_receive (void)
Retrieve one character from the USART1 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
void usart1_init (unsigned int baudrate)
Initiliaze the USART for the communication bus This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA128 baudrate setting.
unsigned char usart1_transmit (unsigned char data)
unsigned char usart1_receive (void)
Retrieve one character from the USART1 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
unsigned char usart1_receive_loopback (void)
The USART1 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
unsigned char usart1_sendstring (char *data, unsigned char length)
Send a string of characters to the USART1 Send a string of characters to the USART used for the communication bus.
Detailed Description
Motherboard USART routines.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "motherboard/usart.h" 
Definition in file usart.h.
Function Documentation
unsigned char poll_usart0_receive (void)
Retrieve one character from the USART0 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Returns: The character from the RX USART buffer
Retrieve one character from the USART0 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Returns: The character from the RX USART buffer
Definition at line 100 of file usart.c.
unsigned char poll_usart1_receive (void)
Retrieve one character from the USART1 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Returns: The character from the RX USART buffer
Retrieve one character from the USART1 Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Returns: The character from the RX USART buffer
Definition at line 185 of file usart.c.
void usart0_init (unsigned int baudrate)
Initiliaze the USART0 for the communication bus This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA2560 baudrate setting.
Parameters:
baudrate The baudrate param from the ATMEGA2560 datasheet.
Initiliaze the USART0 for the communication bus This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA2560 baudrate setting.
Parameters:
baud The baudrate param from the ATMEGA32 datasheet.
Definition at line 34 of file usart.c.
Referenced by init_usart(), and main().
unsigned char usart0_receive (void)
Retrieve one character from the USART0 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
Returns: The character from the RX USART buffer
Retrieve one character from the USART0 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
Returns: The character from the RX USART buffer
Definition at line 73 of file usart.c.
unsigned char usart0_receive_loopback (void)
The USART0 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
Returns: The character from the RX USART buffer
The USART0 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
Returns: The character from the RX USART buffer
Definition at line 85 of file usart.c.
References usart0_transmit().
Referenced by init_usart().
unsigned char usart0_sendstring (char * data, unsigned char length)
Send a string of characters to the USART0 Send a string of characters to the USART used for the communication bus.
Parameters:
data The string of characters you wish to send
length The length of the string you wish to send
Send a string of characters to the USART0 Send a string of characters to the USART used for the communication bus.
Parameters:
data The string of characters you wish to send
length The length of the string you wish to send
Definition at line 60 of file usart.c.
References usart0_transmit().
void usart1_init (unsigned int baudrate)
Initiliaze the USART for the communication bus This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the ATMEGA128 baudrate setting.
Parameters:
baudrate The baudrate param from the ATMEGA32 datasheet.
Definition at line 112 of file usart.c.
unsigned char usart1_receive (void)
Retrieve one character from the USART1 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
Returns: The character from the RX USART buffer
Retrieve one character from the USART1 Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
Returns: The character from the RX USART buffer
Definition at line 158 of file usart.c.
unsigned char usart1_receive_loopback (void)
The USART1 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
Returns: The character from the RX USART buffer
The USART1 recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
Returns: The character from the RX USART buffer
Definition at line 170 of file usart.c.
References usart0_transmit(), and usart1_transmit().
Referenced by init_usart_computer(), and main().
unsigned char usart1_sendstring (char * data, unsigned char length)
Send a string of characters to the USART1 Send a string of characters to the USART used for the communication bus.
Parameters:
data The string of characters you wish to send
length The length of the string you wish to send
Send a string of characters to the USART1 Send a string of characters to the USART used for the communication bus.
Parameters:
data The string of characters you wish to send
length The length of the string you wish to send
Definition at line 145 of file usart.c.
References usart1_transmit().