front_panel/rotary_encoder.c File Reference
Rotary encoder functions.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include `board.h`
#include `rotary_encoder.h`
Functions
unsigned char poll_encoder_state (void)
Poll the rotary encoder pin states.
int rotary_encoder_poll (void)
Poll the rotary encoder.
Variables
unsigned char encoder_last_state = 0
The last state of the encoder.
unsigned char encoder_current_state = 0
The current state of the encoder.
Detailed Description
Rotary encoder functions.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/rotary_encoder.c" 
Definition in file rotary_encoder.c.
Function Documentation
unsigned char poll_encoder_state (void)
Poll the rotary encoder pin states.
Returns: The state of the rotary encoder pins
Definition at line 38 of file rotary_encoder.c.
References PULSE_SENSOR_BIT1, and PULSE_SENSOR_BIT2.
Referenced by rotary_encoder_poll().
int rotary_encoder_poll (void)
Poll the rotary encoder.
Returns: Returns 0 if nothing happened, -1 if rotary CCW and 1 if CW
Definition at line 44 of file rotary_encoder.c.
References encoder_current_state, encoder_last_state, and poll_encoder_state().
Referenced by main().