/*****************************************************************************
* Model: pasm.qm
* File:  ./pasm.c
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
/* @(/1/0) .................................................................*/
/* @(/1/0/3) ...............................................................*/
/* @(/1/0/3/0) */
QState Pa_initial(Pa *me) {
    return Q_TRAN(&Pa_powerOff);
}
/* @(/1/0/3/1) .............................................................*/
QState Pa_powerOff(Pa *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/3/1) */
        case Q_ENTRY_SIG: {
            DEBUG_PRINT("Pa_powerOff/ENTRY\r\n");
            Pa_setOpStatus(me, AMP_OP_STATUS_OFF);
            bsp_set_pa_mains(me->band, 0);
            return Q_HANDLED();
        }
        /* @(/1/0/3/1/0) */
        case TOGGLE_MAINS_SIG: {
            DEBUG_PRINT("Pa_powerOff/TOGGLE_MAINS\r\n");
            return Q_TRAN(&Pa_powerOn);
        }
        /* @(/1/0/3/1/1) */
        case BAND_SELECTED_SIG: {
            DEBUG_PRINT("Pa_powerOff/BAND_SELECTED\r\n");
            Pa_setCtrlr(me, Q_PAR(me));
            return Q_HANDLED();
        }
        /* @(/1/0/3/1/2) */
        case BAND_UNSELECTED_SIG: {
            DEBUG_PRINT("Pa_powerOff/BAND_UNSELECTED\r\n");
            Pa_setCtrlr(me, PA_CTRLR_UNUSED);
            return Q_HANDLED();
        }
    }
    return Q_SUPER(&QHsm_top);
}
/* @(/1/0/3/2) .............................................................*/
QState Pa_powerOn(Pa *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/3/2) */
        case Q_ENTRY_SIG: {
            DEBUG_PRINT("Pa_powerOn/ENTRY\r\n");
            bsp_set_pa_mains(me->band, 1);
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/0) */
        case Q_INIT_SIG: {
            DEBUG_PRINT("Pa_powerOn/INIT\r\n");
            return Q_TRAN(&Pa_warmup);
        }
        /* @(/1/0/3/2/1) */
        case BAND_SELECTED_SIG: {
            DEBUG_PRINT("Pa_powerOn/BAND_SELECTED\r\n");
            Pa_setCtrlr(me, Q_PAR(me));
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/2) */
        case BAND_UNSELECTED_SIG: {
            DEBUG_PRINT("Pa_powerOn/BAND_UNSELECTED\r\n");
            Pa_setCtrlr(me, PA_CTRLR_UNUSED);
            return Q_HANDLED();
        }
    }
    return Q_SUPER(&QHsm_top);
}
/* @(/1/0/3/2/3) ...........................................................*/
QState Pa_warmup(Pa *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/3/2/3) */
        case Q_ENTRY_SIG: {
            DEBUG_PRINT("Pa_warmup/ENTRY\r\n");
            Pa_setOpStatus(me, AMP_OP_STATUS_WARMUP);
            QActive_arm((QActive *)me, cfg.warmup_timeout);
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/3) */
        case Q_EXIT_SIG: {
            DEBUG_PRINT("Pa_warmup/EXIT\r\n");
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/3/0) */
        case TOGGLE_MAINS_SIG: {
            DEBUG_PRINT("Pa_warmup/TOGGLE_MAINS\r\n");
            return Q_TRAN(&Pa_powerOff);
        }
        /* @(/1/0/3/2/3/1) */
        case Q_TIMEOUT_SIG: {
            DEBUG_PRINT("Pa_warmup/TIMEOUT\r\n");
            return Q_TRAN(&Pa_operational);
        }
    }
    return Q_SUPER(&Pa_powerOn);
}
/* @(/1/0/3/2/4) ...........................................................*/
QState Pa_operational(Pa *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/3/2/4) */
        case Q_ENTRY_SIG: {
            DEBUG_PRINT("Pa_operational/ENTRY\r\n");
            Pa_setOpStatus(me, AMP_OP_STATUS_READY);
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/4) */
        case Q_EXIT_SIG: {
            DEBUG_PRINT("Pa_operational/EXIT\r\n");
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/4/0) */
        case TOGGLE_MAINS_SIG: {
            DEBUG_PRINT("Pa_powerOn/TOGGLE_MAINS\r\n");
            return Q_TRAN(&Pa_cooldown);
        }
        /* @(/1/0/3/2/4/1) */
        case Q_INIT_SIG: {
            DEBUG_PRINT("Pa_operational/INIT\r\n");
            /* @(/1/0/3/2/4/1/0) */
            if (me->ctrlr != PA_CTRLR_UNUSED) {
                return Q_TRAN(&Pa_ready);
            }
            /* @(/1/0/3/2/4/1/1) */
            else {
                return Q_TRAN(&Pa_unused);
            }
        }
    }
    return Q_SUPER(&Pa_powerOn);
}
/* @(/1/0/3/2/4/2) .........................................................*/
QState Pa_transmitting(Pa *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/3/2/4/2) */
        case Q_ENTRY_SIG: {
            DEBUG_PRINT("Pa_transmitting/ENTRY\r\n");
            bsp_set_pa_ptt(me->band, 1);

            return Q_HANDLED();
        }
        /* @(/1/0/3/2/4/2) */
        case Q_EXIT_SIG: {
            DEBUG_PRINT("Pa_transmitting/EXIT\r\n");
            bsp_set_pa_ptt(me->band, 0);
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/4/2/0) */
        case TX_ACTIVE_OFF_SIG: {
            DEBUG_PRINT("Pa_transmitting/TX_ACTIVE_OFF\r\n");
            return Q_TRAN(&Pa_ready);
        }
        /* @(/1/0/3/2/4/2/1) */
        case TOGGLE_MAINS_SIG: {
            DEBUG_PRINT("Pa_transmitting/TOGGLE_MAINS\r\n");
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/4/2/2) */
        case BAND_UNSELECTED_SIG: {
            DEBUG_PRINT("Pa_transmitting/BAND_UNSELECTED\r\n");
            return Q_TRAN(&Pa_unused);
        }
    }
    return Q_SUPER(&Pa_operational);
}
/* @(/1/0/3/2/4/3) .........................................................*/
QState Pa_unused(Pa *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/3/2/4/3) */
        case Q_ENTRY_SIG: {
            DEBUG_PRINT("Pa_unused/ENTRY\r\n");
            Pa_setCtrlr(me, PA_CTRLR_UNUSED);
            if (cfg.unused_timeout > 0) {
              QActive_arm((QActive *)me, cfg.unused_timeout);
            }
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/4/3) */
        case Q_EXIT_SIG: {
            DEBUG_PRINT("Pa_unused/EXIT\r\n");
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/4/3/0) */
        case BAND_SELECTED_SIG: {
            DEBUG_PRINT("Pa_unused/BAND_SELECTED\r\n");
            Pa_setCtrlr(me, Q_PAR(me));
            return Q_TRAN(&Pa_ready);
        }
        /* @(/1/0/3/2/4/3/1) */
        case Q_TIMEOUT_SIG: {
            DEBUG_PRINT("Pa_unused/TIMEOUT\r\n");
            return Q_TRAN(&Pa_powerOff);
        }
    }
    return Q_SUPER(&Pa_operational);
}
/* @(/1/0/3/2/4/4) .........................................................*/
QState Pa_ready(Pa *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/3/2/4/4) */
        case Q_ENTRY_SIG: {
            DEBUG_PRINT("Pa_ready/ENTRY\r\n");
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/4/4) */
        case Q_EXIT_SIG: {
            DEBUG_PRINT("Pa_ready/EXIT\r\n");
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/4/4/0) */
        case BAND_UNSELECTED_SIG: {
            DEBUG_PRINT("Pa_ready/BAND_UNSELECTED\r\n");
            return Q_TRAN(&Pa_unused);
        }
        /* @(/1/0/3/2/4/4/1) */
        case TX_ACTIVE_ON_SIG: {
            DEBUG_PRINT("Pa_ready/TX_ACTIVE_ON\r\n");
            return Q_TRAN(&Pa_transmitting);
        }
    }
    return Q_SUPER(&Pa_operational);
}
/* @(/1/0/3/2/5) ...........................................................*/
QState Pa_cooldown(Pa *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/3/2/5) */
        case Q_ENTRY_SIG: {
            DEBUG_PRINT("Pa_cooldown/ENTRY\r\n");
            Pa_setOpStatus(me, AMP_OP_STATUS_COOLDOWN);
            QActive_arm((QActive *)me, cfg.cooldown_timeout);
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/5) */
        case Q_EXIT_SIG: {
            DEBUG_PRINT("Pa_cooldown/EXIT\r\n");
            return Q_HANDLED();
        }
        /* @(/1/0/3/2/5/0) */
        case Q_TIMEOUT_SIG: {
            DEBUG_PRINT("Pa_cooldown/TIMEOUT\r\n");
            return Q_TRAN(&Pa_powerOff);
        }
        /* @(/1/0/3/2/5/1) */
        case TOGGLE_MAINS_SIG: {
            DEBUG_PRINT("Pa_cooldown/TOGGLE_MAINS\r\n");
            return Q_TRAN(&Pa_operational);
        }
    }
    return Q_SUPER(&Pa_powerOn);
}

