delay.h File Reference
Delay routine.
Defines
#define F_CPU 14745600
Functions
void delay_ms (unsigned char ms)
Millisecond delay.
void delay_s (unsigned char s)
Seconds delay.
Detailed Description
Delay routine.
Author: Mikael Larsmark, SM2WMV
Date: 2008-04-06
Definition in file delay.h.
Function Documentation
void delay_ms (unsigned char ms)
Millisecond delay.
Parameters:
ms the delay in milliseconds
Definition at line 25 of file delay.c.
Referenced by delay_s(), and main().
void delay_s (unsigned char s)
Seconds delay.
Parameters:
s delay in seconds
Definition at line 55 of file delay.c.
References delay_ms().