driver_unit/main.c File Reference
Main file of the driver unit.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include `main.h`
#include `board.h`
#include `init.h`
#include `../i2c.h`
#include `../delay.h`
#include `../wmv_bus/bus.h`
#include `../wmv_bus/bus_rx_queue.h`
#include `../wmv_bus/bus_tx_queue.h`
#include `../wmv_bus/bus_commands.h`
Defines
#define LM76_ADDR 0x90
The address of the LM76 temperature sensor connected to the I2C bus.
Functions
void activate_output (unsigned char from_addr, unsigned char index, unsigned char type)
Activate a driver output This function is used to activate an output on the driver unit. It will remember which device that sent the request for an activation so that the driver_unit will remember it when that device goes offline so it can shut the outputs off.
void deactivate_output (unsigned char from_addr, unsigned char index)
Deactivate a driver output This function is used to deactivate an output on the driver unit. It will remember which device that sent the request for an deactivation so that the driver_unit will remember it when that device goes offline so it can shut the outputs off.
unsigned int lm76_get_temp (void)
Retrieve the temperature from the LM76 sensor This function is used to retrieve the temperature from the LM76 sensor that does exist on the driver_unit.
void bus_parse_message (void)
Parse a message and exectute the proper commands This function is used to parse a message that was receieved on the bus that is located in the RX queue.
unsigned char read_ext_addr (void)
Read the external DIP-switch. This function is used to read the external offset address on the driver_unit.
int main (void)
ISR (SIG_OUTPUT_COMPARE0)
Variables
driver_status_struct driver_status
A status structure of the driver unit outputs.
unsigned int counter_compare0 = 0
Counter to keep track of the numbers of ticks from timer0.
unsigned int counter_sync = 0
Counter to keep track of the time elapsed since the last sync message was sent.
unsigned int counter_ping_interval = 0
Counter to keep track of when to send a ping out on the bus.
Detailed Description
Main file of the driver unit.
Author: Mikael Larsmark, SM2WMV
Date: 2008-04-06
 #include "driver_unit/main.c" 
Definition in file main.c.
Function Documentation
void activate_output (unsigned char from_addr, unsigned char index, unsigned char type)
Activate a driver output This function is used to activate an output on the driver unit. It will remember which device that sent the request for an activation so that the driver_unit will remember it when that device goes offline so it can shut the outputs off.
Parameters:
from_addr The device that sent the request of activating an output
index The index of which output to activate
type Which type of output this is, usually is the BUS command
Definition at line 60 of file main.c.
References DRIVER_OUTPUT_1, DRIVER_OUTPUT_10, DRIVER_OUTPUT_11, DRIVER_OUTPUT_12, DRIVER_OUTPUT_13, DRIVER_OUTPUT_14, DRIVER_OUTPUT_15, DRIVER_OUTPUT_16, DRIVER_OUTPUT_17, DRIVER_OUTPUT_18, DRIVER_OUTPUT_19, DRIVER_OUTPUT_2, DRIVER_OUTPUT_20, DRIVER_OUTPUT_3, DRIVER_OUTPUT_4, DRIVER_OUTPUT_5, DRIVER_OUTPUT_6, DRIVER_OUTPUT_7, DRIVER_OUTPUT_8, DRIVER_OUTPUT_9, driver_status_struct::driver_output_owner, driver_status_struct::driver_output_state, and driver_status_struct::driver_output_type.
Referenced by bus_parse_message(), and parse_internal_comm_message().
void deactivate_output (unsigned char from_addr, unsigned char index)
Deactivate a driver output This function is used to deactivate an output on the driver unit. It will remember which device that sent the request for an deactivation so that the driver_unit will remember it when that device goes offline so it can shut the outputs off.
Parameters:
from_addr The device that sent the request of deactivating the output
index The index of which output to deactivate
Definition at line 118 of file main.c.
References DRIVER_OUTPUT_1, DRIVER_OUTPUT_10, DRIVER_OUTPUT_11, DRIVER_OUTPUT_12, DRIVER_OUTPUT_13, DRIVER_OUTPUT_14, DRIVER_OUTPUT_15, DRIVER_OUTPUT_16, DRIVER_OUTPUT_17, DRIVER_OUTPUT_18, DRIVER_OUTPUT_19, DRIVER_OUTPUT_2, DRIVER_OUTPUT_20, DRIVER_OUTPUT_3, DRIVER_OUTPUT_4, DRIVER_OUTPUT_5, DRIVER_OUTPUT_6, DRIVER_OUTPUT_7, DRIVER_OUTPUT_8, DRIVER_OUTPUT_9, driver_status_struct::driver_output_owner, driver_status_struct::driver_output_state, and driver_status_struct::driver_output_type.
Referenced by bus_parse_message(), main(), and parse_internal_comm_message().
ISR (SIG_OUTPUT_COMPARE0)
Output compare 0 interrupt - `called` with 1ms intervals
Definition at line 326 of file main.c.
References bus_add_tx_message(), bus_allowed_to_send(), BUS_BROADCAST_ADDR, BUS_CMD_PING, BUS_DEVICE_STATUS_MESSAGE_INTERVAL, bus_get_address(), counter_compare0, counter_ping_interval, and DEVICE_ID_DRIVER_POS.
unsigned int lm76_get_temp (void)
Retrieve the temperature from the LM76 sensor This function is used to retrieve the temperature from the LM76 sensor that does exist on the driver_unit.
Returns: The temperature but not in float format
Definition at line 173 of file main.c.
References i2cMasterReceiveNI(), and LM76_ADDR.
Referenced by bus_parse_message().
int main (void)
Main function of the driver unit
Definition at line 277 of file main.c.
References bus_check_tx_status(), bus_get_address(), bus_init(), bus_parse_message(), bus_set_address(), bus_set_is_master(), deactivate_output(), driver_status_struct::driver_output_state, init_ports(), init_timer_0(), init_timer_2(), read_ext_addr(), rx_queue_is_empty(), and tx_queue_is_empty().
unsigned char read_ext_addr (void)
Read the external DIP-switch. This function is used to read the external offset address on the driver_unit.
Returns: The address of the external DIP-switch
Definition at line 272 of file main.c.
Referenced by main().