motherboard/computer_interface.c File Reference
Interface towards the computer.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/eeprom.h>
#include <string.h>
#include <avr/wdt.h>
#include `computer_interface.h`
#include `usart.h`
#include `main.h`
#include `../internal_comm.h`
#include `../internal_comm_commands.h`
Classes
struct computer_comm_struct
Computer interface communication struct.
Defines
#define COMPUTER_RX_BUFFER_LENGTH 128
The length of the computer RX BUFFER.
#define COMPUTER_TX_BUFFER_LENGTH 20
The length of the computer RX BUFFER.
#define COMPUTER_INTERFACE_FIXED_SIZE 5
The number of bytes the fixed part of the data structure takes up.
#define COMPUTER_COMM_PREAMBLE 0xFE
The preamble of the computer communication protocol.
#define COMPUTER_COMM_POSTAMBLE 0xFD
The postamble of the computer communication protocol.
#define COMPUTER_COMM_ACK 0xFA
The serial acknowledge of the computer communication protocol.
#define COMPUTER_COMM_NACK 0xFB
The serial NOT acknowledge of the computer communication protocol.
#define COMPUTER_COMM_REDIRECT_DATA 0x10
Command which is used just to redirect data from the USB to the front panel.
#define COMPUTER_COMM_FLAG_FOUND_PREAMBLE 1
Flag to see if the preamble was found.
#define COMPUTER_COMM_FLAG_DATA_IN_RX_BUF 2
Flag to see that there is data in the rx buffer.
Functions
void computer_interface_init (void)
Initialize the communication interface towards the computer.
void computer_interface_send_data (void)
Send data to the computer.
void computer_interface_send (unsigned char command, unsigned int length, char *data)
Send data to the computer.
void computer_interface_send_ack (void)
Send an ACK message.
void computer_interface_send_nack (void)
Send a NACK message.
void computer_interface_parse_data (void)
Parse the data in the rx_buffer and execute the proper functions.
ISR (SIG_USART1_DATA)
ISR (SIG_USART1_RECV)
Variables
computer_comm_struct computer_comm
Computer communication data.
void(* bootloader_start)(void) = (void *)0x1FE00
The bootloader start address.
Detailed Description
Interface towards the computer.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "computer_interface.c" 
Definition in file computer_interface.c.
Function Documentation
void computer_interface_init (void)
Initialize the communication interface towards the computer.
Initialize the communication interface towards the computer. Will initialize buffers etc.
Definition at line 106 of file computer_interface.c.
References COMPUTER_RX_BUFFER_LENGTH, COMPUTER_TX_BUFFER_LENGTH, computer_comm_struct::data_in_tx_buffer, computer_comm_struct::rx_buffer, computer_comm_struct::rx_buffer_start, computer_comm_struct::tx_buffer, and computer_comm_struct::tx_buffer_start.
void computer_interface_parse_data (void)
Parse the data in the rx_buffer and execute the proper functions.
Function which will parse the data in the rx_buffer and process the command.
Bit 0 = Footswitch Bit 1 = Radio sense lower floor Bit 2 = Radio sense upper floor Bit 3 = Computer RTS Bit 4 = Inverted radio sense Bit 5 = Inverted Computer RTS Bit 6 = Inhibit polarity (0=active low, 1=active high)
unsigned char ptt_input;
Definition at line 175 of file computer_interface.c.
References struct_ptt_sequencer::active, struct_ptt_sequencer::amp_post_delay, struct_ptt_sequencer::amp_pre_delay, struct_antenna::antenna_comb_allowed, struct_antenna::antenna_comb_output_str, struct_antenna::antenna_flag, struct_antenna::antenna_output_length, struct_antenna::antenna_text, struct_antenna::antenna_text_length, struct_ptt_sequencer::antennas_post_delay, struct_band::band_high_output_str, struct_band::band_high_output_str_length, struct_band::band_low_output_str, struct_band::band_low_output_str_length, struct_rx_antennas::band_output_length, struct_rx_antennas::band_output_str, struct_radio_settings::baudrate, bootloader_start, struct_radio_settings::cat_enabled, struct_radio_settings::civ_addr, computer_comm_struct::command, struct_ptt::computer, COMPUTER_COMM_ENTER_BOOTLOADER, COMPUTER_COMM_FLAG_DATA_IN_RX_BUF, computer_interface_deactivate_setup(), computer_interface_send(), computer_interface_send_ack(), computer_interface_send_nack(), CTRL_CREATE_EEPROM_TABLE, CTRL_DONE, CTRL_GET_FIRMWARE_REV, CTRL_REBOOT, CTRL_SET_ANT_DATA, CTRL_SET_ANT_DATA_ANT_FLAGS, CTRL_SET_ANT_DATA_ANT_OUT_STR, CTRL_SET_ANT_DATA_COMB_ALLOWED, CTRL_SET_ANT_DATA_SAVE, CTRL_SET_ANT_DATA_SUB_MENU_TYPE, CTRL_SET_ANT_DATA_TEXT, CTRL_SET_ANT_DEFAULT_INDEX, CTRL_SET_ANT_ROTATOR_DATA, CTRL_SET_ANT_SUB_MENU_DATA, CTRL_SET_ANT_SUB_MENU_OUTPUT_STR, CTRL_SET_ANT_SUB_MENU_TEXT, CTRL_SET_BAND_DATA, CTRL_SET_BAND_DATA_HIGH_OUT_STR, CTRL_SET_BAND_DATA_LIMITS, CTRL_SET_BAND_DATA_LOW_OUT_STR, CTRL_SET_BAND_DATA_SAVE, CTRL_SET_DEVICE_SETTINGS, CTRL_SET_DEVICE_SETTINGS_EXT_INPUTS, CTRL_SET_DEVICE_SETTINGS_NETWORK, CTRL_SET_DEVICE_SETTINGS_OTHER, CTRL_SET_DEVICE_SETTINGS_SAVE, CTRL_SET_POWERMETER_SETTINGS, CTRL_SET_RADIO_SETTINGS, CTRL_SET_RADIO_SETTINGS_ALL, CTRL_SET_RADIO_SETTINGS_SAVE, CTRL_SET_RX_ANT_DATA, CTRL_SET_RX_ANT_DATA_ANT_OUT_STR, CTRL_SET_RX_ANT_DATA_BAND_OUT_STR, CTRL_SET_RX_ANT_DATA_SAVE, CTRL_SET_RX_ANT_DATA_TEXT, CTRL_SET_SEQUENCER_COMPUTER, CTRL_SET_SEQUENCER_FOOTSWITCH, CTRL_SET_SEQUENCER_RADIO_SENSE, CTRL_SET_SEQUENCER_SAVE, CTRL_SET_SEQUENCER_SETTINGS, CTRL_SET_TIME, struct_antenna::default_antenna, struct_sub_menu_array::direction_count, struct_sub_menu_array::direction_name, ds1307_set_time(), eeprom_create_table(), eeprom_save_ant_structure(), eeprom_save_ant_sub_menu_array_structure(), eeprom_save_band_data(), eeprom_save_ptt_data(), eeprom_save_radio_settings_structure(), eeprom_save_rx_ant_structure(), eeprom_save_settings_structure(), struct_setting::ext_key_assignments, FIRMWARE_REV, computer_comm_struct::flags, struct_ptt::footswitch, struct_band::high_portion_high_limit, struct_band::high_portion_low_limit, struct_ptt_sequencer::inhibit_post_delay, struct_ptt_sequencer::inhibit_pre_delay, INT_COMM_PC_CTRL, INT_COMM_REDIRECT_DATA, struct_radio_settings::interface_type, internal_comm_add_tx_message(), computer_comm_struct::length, struct_band::low_portion_high_limit, struct_band::low_portion_low_limit, struct_rx_antennas::name, struct_rx_antennas::name_length, struct_setting::network_address, struct_setting::network_device_count, struct_setting::network_device_is_master, struct_rx_antennas::output_length, struct_rx_antennas::output_str, struct_sub_menu_array::output_str_dir, struct_sub_menu_array::output_str_dir_length, struct_radio_settings::poll_interval, struct_setting::powermeter_address, struct_setting::powermeter_update_rate_bargraph, struct_setting::powermeter_update_rate_text, struct_setting::powermeter_vswr_limit, struct_ptt::ptt_input, struct_radio_settings::ptt_input, struct_setting::ptt_interlock_input, struct_radio_settings::radio_model, struct_ptt_sequencer::radio_post_delay, struct_ptt_sequencer::radio_pre_delay, struct_ptt::radio_sense, struct_antenna::rotator_addr, struct_antenna::rotator_delay, struct_antenna::rotator_max_rotation, struct_antenna::rotator_min_heading, struct_antenna::rotator_sub_addr, struct_antenna::rotator_view_360_deg, computer_comm_struct::rx_buffer, computer_comm_struct::rx_buffer_start, struct_radio_settings::stopbits, struct_antenna::sub_menu_type, SUBMENU_STACK, and SUBMENU_VERT_ARRAY.
void computer_interface_send (unsigned char command, unsigned int length, char * data)
Send data to the computer.
Parameters:
command The command we wish to send
length The length of the data
data The data we wish to send
Definition at line 134 of file computer_interface.c.
References COMPUTER_COMM_POSTAMBLE, COMPUTER_COMM_PREAMBLE, COMPUTER_INTERFACE_FIXED_SIZE, computer_comm_struct::data_in_tx_buffer, computer_comm_struct::tx_buffer, and computer_comm_struct::tx_buffer_length.
void computer_interface_send_data (void)
Send data to the computer.
Function which will send data from the tx_buffer to the uart.
Definition at line 118 of file computer_interface.c.
References computer_comm_struct::data_in_tx_buffer, computer_comm_struct::tx_buffer, computer_comm_struct::tx_buffer_length, computer_comm_struct::tx_buffer_start, and usart1_transmit().
ISR (SIG_USART1_RECV)
Interrupt which is called when a byte has been received
Definition at line 197 of file computer_interface.c.
References computer_comm_struct::command, COMPUTER_COMM_FLAG_DATA_IN_RX_BUF, COMPUTER_COMM_FLAG_FOUND_PREAMBLE, COMPUTER_COMM_POSTAMBLE, COMPUTER_COMM_PREAMBLE, COMPUTER_RX_BUFFER_LENGTH, computer_comm_struct::count, computer_comm_struct::flags, computer_comm_struct::length, computer_comm_struct::rx_buffer, and computer_comm_struct::rx_buffer_start.