wmv_bus/bus_usart.c File Reference
Driver unit USART routines.
#include <avr/io.h>
#include <avr/interrupt.h>
#include <stdio.h>
#include <string.h>
Functions
void bus_usart_init (unsigned int baudrate)
Initiliaze the USART for the communication bus This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the uCs datasheet.
unsigned char bus_usart_transmit (unsigned char data)
Send a character to the USART Send a single character to the USART used for the communication bus.
unsigned char bus_usart_sendstring (char *data, unsigned char length)
Send a string of characters to the USART Send a string of characters to the USART used for the communication bus.
unsigned char bus_usart_receive (void)
Retrieve one character from the USART Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
unsigned char bus_usart_receive_loopback (void)
The USART recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
unsigned char bus_poll_usart_receive (void)
Retrieve one character from the USART Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Detailed Description
Driver unit USART routines.
These routines are used to communicate over the WMV bus.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "wmv_bus/bus_usart.c" 
Definition in file bus_usart.c.
Function Documentation
unsigned char bus_poll_usart_receive (void)
Retrieve one character from the USART Retrieve one character from the USART. With this function you will need to poll the USART, it does NOT wait until a character is in the buffer.
Returns: The character from the RX USART buffer
Definition at line 301 of file bus_usart.c.
void bus_usart_init (unsigned int baudrate)
Initiliaze the USART for the communication bus This function is used to initialize the USART which a baudrate that needs to be sent in as a parameter Use the baudrate settings specified in the uCs datasheet.
Parameters:
baudrate The baudrate param from the ATMEGA32 datasheet.
Definition at line 34 of file bus_usart.c.
Referenced by bus_init().
unsigned char bus_usart_receive (void)
Retrieve one character from the USART Retrieve one character from the USART. This function will wait until there is a character in the USART RX buffer.
Returns: The character from the RX USART buffer
Definition at line 181 of file bus_usart.c.
unsigned char bus_usart_receive_loopback (void)
The USART recieve loopback This function does wait for a character in the RX buffer and returns it to the transmit buffer.
Returns: The character from the RX USART buffer
Definition at line 232 of file bus_usart.c.
References bus_usart_transmit().
unsigned char bus_usart_sendstring (char * data, unsigned char length)
Send a string of characters to the USART Send a string of characters to the USART used for the communication bus.
Parameters:
data The string of characters you wish to send
length The length of the string you wish to send
Definition at line 168 of file bus_usart.c.
References bus_usart_transmit().
unsigned char bus_usart_transmit (unsigned char data)
Send a character to the USART Send a single character to the USART used for the communication bus.
Parameters:
data The character you want to send
Definition at line 116 of file bus_usart.c.
Referenced by bus_send_message(), bus_usart_receive_loopback(), and bus_usart_sendstring().