front_panel/main.c File Reference
Main file of the front panel.
#include <stdio.h>
#include <stdlib.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <string.h>
#include <avr/wdt.h>
#include `main.h`
#include `board.h`
#include `usart.h`
#include `init.h`
#include `display.h`
#include `glcd.h`
#include `ks0108.h`
#include `led_control.h`
#include `../delay.h`
#include `../i2c.h`
#include `../global.h`
#include `../event_queue.h`
#include `interrupt_handler.h`
#include `eeprom.h`
#include `ds1307.h`
#include `computer_interface.h`
#include `antenna_ctrl.h`
#include `eeprom_m24.h`
#include `radio_interface.h`
#include `menu.h`
#include `rotary_encoder.h`
#include `event_handler.h`
#include `powermeter.h`
#include `../wmv_bus/bus.h`
#include `../wmv_bus/bus_ping.h`
#include `../wmv_bus/bus_rx_queue.h`
#include `../wmv_bus/bus_tx_queue.h`
#include `../wmv_bus/bus_commands.h`
#include `../internal_comm.h`
#include `../internal_comm_commands.h`
Functions
void clear_screensaver_timer (void)
Clear the screensaver timer.
void event_add_message (void(*func), unsigned int offset, unsigned char id)
unsigned char ext_key_get_assignment (unsigned char index)
void ext_key_set_assignment (unsigned char index, unsigned char func)
void event_run (void)
Run the first function in the event queue.
void main_update_display (void)
Sets the flag that the display should be updated.
void shutdown_device (void)
Send a message to the motherboard that the openASC box should be shut off. Will deactivate the power supply relay.
void set_tx_ant_leds (void)
Set the TX antenna leds according to the status of status.selected_ant.
void set_knob_function (unsigned char function)
Set the rotary knob function.
void main_save_settings (void)
Save runtime settings etc to the EEPROM.
void load_settings (void)
Load all settings from the EEPROM.
void main_update_ptt_status (void)
Function which updates the status of the PTT This function will check various sources if it is for example OK to transmit or not. This function also updates the color of the PTT led. It does also set the main_set_inhibit_state() status which is used at various places to make the sequencing etc safe.
void main_set_inhibit_state (enum enum_inhibit_state state)
Set the inhibit state This function is used to set the inhibit state, which is used to check at various places if it is safe for example to transmit, change band or change antennas.
enum enum_inhibit_state main_get_inhibit_state (void)
Get the inhibit state This function is used to get the inhibit state, which is used to check at various places if it is safe for example to transmit, change band or change antennas.
void send_ping (void)
Send a ping message out on the bus.
int main (void)
ISR (SIG_OUTPUT_COMPARE0A)
ISR (SIG_OVERFLOW0)
Variables
struct_setting settings
Settings struct.
unsigned char radio_rx_data_counter = 0
Counter to keep track of when a character for the CAT was last received.
unsigned int counter_compare0 = 0
Counter which counts up each time a compare0 interrupt has occured.
unsigned int counter_sync = 32000
Counter which is used to keep track of when we last received a sync message from the bus.
unsigned char counter_poll_buttons = 0
Counter which keeps track of when we should poll the buttons.
unsigned char counter_poll_ext_devices = 0
Counter which keeps track of when we should poll the external inputs.
unsigned int counter_screensaver_timeout = 0
Counter which keeps track of the screensaver timeout.
unsigned int counter_ping_interval = 0
Counter which keeps track of when we should send out a ping to the communication bus.
unsigned int counter_ms = 0
Counter which counts up each millisecond.
unsigned char counter_poll_rotary_encoder = 0
Counter which keeps track when we should poll the rotary encoder.
unsigned int counter_poll_radio = 0
Counter which keeps track of when we should poll the radio.
unsigned int counter_last_pulse_event = 0
Counter which keeps track of when the last pulse event did occur. This is used to sense if we should change rx antennas.
unsigned int counter_event_timer = 0
After the counter reaches half of it's limit we remove that number from it by calling the function event_queue_wrap().
unsigned char device_count = 0
The number of devices on the bus.
unsigned int main_flags = 0
Different flags, description is found in main.h.
unsigned char ping_message [3]
Ping message of the openASC device.
unsigned char device_started = 0
Variable to check if the device has actually gone through all init steps.
Detailed Description
Main file of the front panel.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/main.c" 
Definition in file main.c.
Function Documentation
void event_add_message (void * func, unsigned int offset, unsigned char id)
Add a message to the event queue which will be run at the correct time
Parameters:
func A function pointer to the function we want to run
offset the time in ms when we want our function to be run
id Which type of event this is
Definition at line 115 of file main.c.
References counter_event_timer, event_in_queue(), and event_queue_add().
Referenced by display_update_screensaver(), event_internal_comm_parse_message(), sequencer_computer_rts_activated(), sequencer_computer_rts_deactivated(), sequencer_footsw_pressed(), and sequencer_footsw_released().
unsigned char ext_key_get_assignment (unsigned char index)
Get the key assignment index
Parameters:
index The index of which task we wish to check
Returns: The current task index, can be found in event_handler.h
Definition at line 131 of file main.c.
References struct_setting::ext_key_assignments.
Referenced by event_handler_process_ps2().
void ext_key_set_assignment (unsigned char index, unsigned char func)
Set the key assignment task
Parameters:
index The index of which task we wish to set
func The function we wish to assign to the assignment index
Definition at line 138 of file main.c.
References struct_setting::ext_key_assignments.
ISR (SIG_OVERFLOW0)
Output overflow 0 interrupt
Definition at line 748 of file main.c.
ISR (SIG_OUTPUT_COMPARE0A)
Output compare 0 interrupt - `called` with 1ms intervals
Definition at line 620 of file main.c.
References antenna_ctrl_get_rotatable(), antenna_ctrl_get_rotator_flags(), struct_runtime_settings::band_change_mode, BAND_CHANGE_MODE_AUTO, bus_is_master(), bus_ping_tick(), counter_event_timer, counter_last_pulse_event, counter_ms, counter_ping_interval, counter_poll_buttons, counter_poll_ext_devices, counter_poll_radio, counter_poll_rotary_encoder, counter_screensaver_timeout, counter_sync, device_started, event_in_queue(), event_queue_get(), event_queue_wrap(), FLAG_BLINK_BAND_LED, FLAG_CHANGE_RX_ANT, FLAG_CHANGE_SUBMENU, FLAG_LAST_ANTENNA_BLINK, FLAG_NO_ROTATION, FLAG_POLL_BUTTONS, FLAG_POLL_EXT_DEVICES, FLAG_POLL_PULSE_SENSOR, FLAG_POLL_RADIO, FLAG_PROCESS_RX_ANT_CHANGE, FLAG_PROCESS_SUBMENU_CHANGE, FLAG_RUN_EVENT_QUEUE, FUNC_STATUS_SELECT_ANT_ROTATE, struct_status::function_status, internal_comm_1ms_timer(), INTERVAL_POLL_BUTTONS, INTERVAL_POLL_EXT_DEVICES, INTERVAL_POLL_ROTARY_ENCODER, led_set_rotation_active(), led_set_tx_ant(), LED_STATE_OFF, LED_STATE_ON, main_flags, powermeter_1ms_tick(), struct_setting::powermeter_address, PULSE_SENSOR_RX_ANT_CHANGE_LIMIT, PULSE_SENSOR_SUBMENU_CHANGE_LIMIT, radio_communicaton_timeout(), radio_interface_get_poll_interval(), radio_rx_data_counter, RADIO_RX_DATA_TIMEOUT, runtime_settings, and status.
int main (void)
Main function of the front panel
Definition at line 293 of file main.c.
References struct_runtime_settings::amplifier_ptt_output, antenna_ctrl_change_rx_ant(), struct_runtime_settings::band_change_mode, BAND_CHANGE_MODE_AUTO, BAND_CHANGE_MODE_MANUAL, band_ctrl_change_band(), band_ctrl_change_band_portion(), band_ctrl_load_band_limits(), bus_add_tx_message(), bus_allowed_to_send(), BUS_BROADCAST_ADDR, bus_check_tx_status(), BUS_CMD_SYNC, BUS_DEVICE_STATUS_MESSAGE_INTERVAL, bus_get_address(), bus_init(), bus_is_master(), BUS_MASTER_SYNC_INTERVAL, bus_set_address(), bus_set_is_master(), struct_status::buttons_current_state, struct_status::buttons_last_state, computer_interface_activate_setup(), computer_interface_deactivate_setup(), computer_interface_init(), computer_interface_is_active(), computer_interface_parse_data(), computer_interface_send_data(), counter_last_pulse_event, counter_ping_interval, counter_sync, struct_status::current_band_portion, device_count, DEVICE_ID_MAINBOX, device_started, display_set_backlight(), display_setup_view(), ds1307_init(), eeprom_create_table(), eeprom_read_startup_byte(), eeprom_read_table(), eeprom_save_runtime_settings(), eeprom_write_startup_byte(), event_bus_parse_message(), event_internal_comm_parse_message(), event_poll_buttons(), event_poll_ext_device(), event_pulse_sensor_down(), event_pulse_sensor_up(), event_run(), event_update_display(), struct_status::ext_devices_current_state, struct_status::ext_devices_last_state, FLAG_BLINK_BAND_LED, FLAG_CHANGE_RX_ANT, FLAG_CHANGE_SUBMENU, FLAG_LAST_BAND_BLINK, FLAG_POLL_BUTTONS, FLAG_POLL_EXT_DEVICES, FLAG_POLL_PULSE_SENSOR, FLAG_POLL_RADIO, FLAG_PROCESS_RX_ANT_CHANGE, FLAG_PROCESS_SUBMENU_CHANGE, FLAG_RUN_EVENT_QUEUE, FLAG_UPDATE_DISPLAY, glcd_init(), i2c_init(), ih_poll_ext_devices(), INHIBIT_NOT_OK_TO_SEND, struct_runtime_settings::inhibit_state, init_backlight(), init_ports(), init_timer_0(), init_timer_2(), init_usart(), init_usart_computer(), internal_comm_init(), internal_comm_poll_rx_queue(), internal_comm_poll_tx_queue(), KNOB_FUNCTION_AUTO, struct_runtime_settings::lcd_backlight_value, led_set_all(), led_set_band(), led_set_band_none(), led_set_ptt(), LED_STATE_OFF, LED_STATE_ON, LED_STATE_PTT_INHIBIT, load_settings(), main_flags, main_set_inhibit_state(), menu_init(), struct_setting::network_address, struct_setting::network_device_count, struct_setting::network_device_is_master, struct_status::new_band, struct_status::new_band_portion, ping_message, struct_setting::powermeter_address, powermeter_init(), powermeter_process_tasks(), struct_setting::powermeter_update_rate_bargraph, struct_setting::powermeter_update_rate_text, struct_setting::powermeter_vswr_limit, radio_get_band_portion(), radio_get_current_band(), RADIO_INTERFACE_BCD, radio_interface_get_interface(), RADIO_INTERFACE_MANUAL, radio_poll_status(), radio_process_tasks(), struct_runtime_settings::radio_ptt_output, rotary_encoder_poll(), struct_status::rotator_step_resolution, runtime_settings, rx_queue_is_empty(), struct_status::selected_band, struct_status::selected_rx_antenna, send_ping(), set_knob_function(), status, struct_status::sub_menu_antenna_index, sub_menu_get_current_pos(), sub_menu_send_data_to_bus(), tx_queue_dropall(), tx_queue_is_empty(), and usart0_transmit().
enum enum_inhibit_state main_get_inhibit_state (void)
Get the inhibit state This function is used to get the inhibit state, which is used to check at various places if it is safe for example to transmit, change band or change antennas.
Returns: The current inhibit status
Definition at line 280 of file main.c.
References struct_runtime_settings::inhibit_state, and runtime_settings.
Referenced by band_ctrl_change_band(), event_pulse_sensor_down(), event_pulse_sensor_up(), event_tx_button1_pressed(), event_tx_button2_pressed(), event_tx_button3_pressed(), event_tx_button4_pressed(), radio_poll_status(), sequencer_computer_rts_activated(), and sequencer_footsw_pressed().
void main_set_inhibit_state (enum enum_inhibit_state state)
Set the inhibit state This function is used to set the inhibit state, which is used to check at various places if it is safe for example to transmit, change band or change antennas.
Parameters:
state The state we wish to set the inhibit status to
Definition at line 272 of file main.c.
References struct_runtime_settings::inhibit_state, and runtime_settings.
Referenced by main(), and main_update_ptt_status().
void set_knob_function (unsigned char function)
Set the rotary knob function.
Parameters:
function Which type of action should occur when the knob is turned
Definition at line 178 of file main.c.
References struct_runtime_settings::band_change_mode, BAND_CHANGE_MODE_MANUAL, struct_status::knob_function, KNOB_FUNCTION_AUTO, KNOB_FUNCTION_NONE, KNOB_FUNCTION_SELECT_BAND, runtime_settings, and status.
Referenced by band_ctrl_change_band(), event_poll_buttons(), event_rotate_button_pressed(), event_rxant_button_pressed(), event_sub_button_pressed(), main(), and menu_action().
Variable Documentation
unsigned char radio_rx_data_counter = 0
Counter to keep track of when a character for the CAT was last received.
External variable of the radio rx data counter used for a timeout.
Definition at line 69 of file main.c.
Referenced by ISR().