front_panel/init.c File Reference
Initialization routines for the front panel.
#include <stdio.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include `usart.h`
#include `board.h`
Defines
#define OCR0_1MS 14
Used for timer compare to match 1 ms.
Functions
void init_usart_computer (void)
void init_usart (void)
void init_timer_0 (void)
void init_timer_2 (void)
void init_ports (void)
void init_backlight (void)
Detailed Description
Initialization routines for the front panel.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/init.c" 
Definition in file init.c.
Function Documentation
void init_backlight (void)
Initialize the backlight (Which is pulse width modulated so we can set the contrast)
Definition at line 105 of file init.c.
Referenced by main().
void init_ports (void)
Set the direction of the ports
Definition at line 72 of file init.c.
References BUTTON1_RX_BIT, BUTTON1_TX_BIT, BUTTON2_RX_BIT, BUTTON2_TX_BIT, BUTTON3_RX_BIT, BUTTON3_TX_BIT, BUTTON4_RX_BIT, BUTTON4_TX_BIT, BUTTON_AUX1_BIT, BUTTON_AUX2_BIT, BUTTON_MENU_BIT, BUTTON_PULSE_BIT, BUTTON_ROTATE_BIT, BUTTON_RXANT_BIT, BUTTON_SUBMENU_BIT, and BUTTON_TXRX_BIT.
void init_timer_0 (void)
Initialize timer0 to use the main crystal clock and the output compare interrupt feature to generate an interrupt approximately once per millisecond to use as a general purpose time base.
Definition at line 51 of file init.c.
References OCR0_1MS.
void init_timer_2 (void)
Initializes timer 2
Definition at line 62 of file init.c.
void init_usart (void)
Initializes the USART for the communication bus
Definition at line 41 of file init.c.
Referenced by main().
void init_usart_computer (void)
Init the UART for the computer communication
Definition at line 33 of file init.c.
References usart1_init(), usart1_receive_loopback(), and usart1_transmit().
Referenced by main().