front_panel/menu.h File Reference
Menu system.
#include <avr/pgmspace.h>
Classes
struct struct_menu_option
Struct of a menu option.
struct struct_menu_text
Menu text structs.
Defines
#define MENU_OPTION_TYPE_NORMAL 0
Menu type option normal, regular choices.
#define MENU_OPTION_TYPE_SCROLL_NUMBERS 1
Menu type scroll numbers, for example increase/decrease a value.
#define MENU_OPTION_TYPE_NONE 99
No menu option.
#define MENU_POS_BAND_MODE 0
Show band change mode, auto or manual.
#define MENU_POS_RADIO_PTT 1
Show the radio output ptt ON/OFF.
#define MENU_POS_AMP_PTT 2
Show the amplifier output ptt ON/OFF.
#define MENU_POS_BACKLIGHT_LEVEL 3
Change the backlight level of the LCD.
#define MENU_POS_SHOW_ACTIVITY 4
Show network actvitity.
#define MENU_POS_MISC 5
Show MISC menu.
#define MENU_POS_SHOW_ERRORS 6
Show the error menu.
#define MENU_SCROLL_UP 0
Menu flag scroll up.
#define MENU_SCROLL_DOWN 1
Menu flag scroll down.
#define MENU_BUTTON_PRESSED 2
Menu flag button pressed.
Functions
void menu_show (void)
Shows the menu.
void menu_action (unsigned char menu_action_type)
void menu_init (void)
Initialize the menu system.
void menu_reset (void)
Function will reset to init values, like menu level etc.
Detailed Description
Menu system.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/menu.h " 
Definition in file menu.h.
Function Documentation
void menu_action (unsigned char menu_action_type)
This function will handle an menu action `event`
Parameters:
menu_action_type Which action did occur?
Definition at line 173 of file menu.c.
References struct_runtime_settings::amplifier_ptt_output, struct_runtime_settings::band_change_mode, BAND_CHANGE_MODE_AUTO, BAND_CHANGE_MODE_MANUAL, bootloader_start, current_menu_level, current_menu_option_selected, current_menu_pos, display_set_backlight(), event_get_errors(), event_set_error(), KNOB_FUNCTION_AUTO, struct_runtime_settings::lcd_backlight_value, led_set_error(), LED_STATE_OFF, MENU_BUTTON_PRESSED, MENU_OPTION_TYPE_NORMAL, MENU_OPTION_TYPE_SCROLL_NUMBERS, MENU_OPTIONS, MENU_POS_AMP_PTT, MENU_POS_BACKLIGHT_LEVEL, MENU_POS_BAND_MODE, MENU_POS_MISC, MENU_POS_RADIO_PTT, MENU_POS_SHOW_ERRORS, MENU_SCROLL_DOWN, MENU_SCROLL_UP, menu_show(), NR_OF_ERRORS, struct_runtime_settings::radio_ptt_output, runtime_settings, and set_knob_function().
Referenced by event_poll_buttons(), event_pulse_sensor_down(), and event_pulse_sensor_up().