motherboard/computer_interface.h File Reference
Interface towards the computer.
Functions
void computer_interface_init (void)
Initialize the communication interface towards the computer. Will initialize buffers etc.
void computer_interface_send_data (void)
Function which will send data from the tx_buffer to the uart.
void computer_interface_parse_data (void)
Function which will parse the data in the rx_buffer and process the command.
Detailed Description
Interface towards the computer.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "computer_interface.h" 
Definition in file computer_interface.h.
Function Documentation
void computer_interface_parse_data (void)
Function which will parse the data in the rx_buffer and process the command.
Bit 0 = Footswitch Bit 1 = Radio sense lower floor Bit 2 = Radio sense upper floor Bit 3 = Computer RTS Bit 4 = Inverted radio sense Bit 5 = Inverted Computer RTS Bit 6 = Inhibit polarity (0=active low, 1=active high)
unsigned char ptt_input;
Bit 0 = Footswitch Bit 1 = Radio sense lower floor Bit 2 = Radio sense upper floor Bit 3 = Computer RTS Bit 4 = Inverted radio sense Bit 5 = Inverted Computer RTS Bit 6 = Inhibit polarity (0=active low, 1=active high)
unsigned char ptt_input;
Definition at line 304 of file computer_interface.c.
References struct_ptt_sequencer::active, struct_ptt_sequencer::amp_post_delay, struct_ptt_sequencer::amp_pre_delay, struct_antenna::antenna_comb_allowed, struct_antenna::antenna_comb_output_str, struct_antenna::antenna_flag, struct_antenna::antenna_output_length, struct_antenna::antenna_text, struct_antenna::antenna_text_length, struct_ptt_sequencer::antennas_post_delay, struct_band::band_high_output_str, struct_band::band_high_output_str_length, struct_band::band_low_output_str, struct_band::band_low_output_str_length, struct_rx_antennas::band_output_length, struct_rx_antennas::band_output_str, struct_radio_settings::baudrate, bootloader_start, struct_radio_settings::cat_enabled, struct_radio_settings::civ_addr, computer_comm_struct::command, struct_ptt::computer, COMPUTER_COMM_ENTER_BOOTLOADER, COMPUTER_COMM_FLAG_DATA_IN_RX_BUF, computer_interface_deactivate_setup(), computer_interface_send(), computer_interface_send_ack(), computer_interface_send_nack(), CTRL_CREATE_EEPROM_TABLE, CTRL_DONE, CTRL_GET_FIRMWARE_REV, CTRL_REBOOT, CTRL_SET_ANT_DATA, CTRL_SET_ANT_DATA_ANT_FLAGS, CTRL_SET_ANT_DATA_ANT_OUT_STR, CTRL_SET_ANT_DATA_COMB_ALLOWED, CTRL_SET_ANT_DATA_SAVE, CTRL_SET_ANT_DATA_SUB_MENU_TYPE, CTRL_SET_ANT_DATA_TEXT, CTRL_SET_ANT_DEFAULT_INDEX, CTRL_SET_ANT_ROTATOR_DATA, CTRL_SET_ANT_SUB_MENU_DATA, CTRL_SET_ANT_SUB_MENU_OUTPUT_STR, CTRL_SET_ANT_SUB_MENU_TEXT, CTRL_SET_BAND_DATA, CTRL_SET_BAND_DATA_HIGH_OUT_STR, CTRL_SET_BAND_DATA_LIMITS, CTRL_SET_BAND_DATA_LOW_OUT_STR, CTRL_SET_BAND_DATA_SAVE, CTRL_SET_DEVICE_SETTINGS, CTRL_SET_DEVICE_SETTINGS_EXT_INPUTS, CTRL_SET_DEVICE_SETTINGS_NETWORK, CTRL_SET_DEVICE_SETTINGS_OTHER, CTRL_SET_DEVICE_SETTINGS_SAVE, CTRL_SET_POWERMETER_SETTINGS, CTRL_SET_RADIO_SETTINGS, CTRL_SET_RADIO_SETTINGS_ALL, CTRL_SET_RADIO_SETTINGS_SAVE, CTRL_SET_RX_ANT_DATA, CTRL_SET_RX_ANT_DATA_ANT_OUT_STR, CTRL_SET_RX_ANT_DATA_BAND_OUT_STR, CTRL_SET_RX_ANT_DATA_SAVE, CTRL_SET_RX_ANT_DATA_TEXT, CTRL_SET_SEQUENCER_COMPUTER, CTRL_SET_SEQUENCER_FOOTSWITCH, CTRL_SET_SEQUENCER_RADIO_SENSE, CTRL_SET_SEQUENCER_SAVE, CTRL_SET_SEQUENCER_SETTINGS, CTRL_SET_TIME, struct_antenna::default_antenna, struct_sub_menu_array::direction_count, struct_sub_menu_array::direction_name, ds1307_set_time(), eeprom_create_table(), eeprom_save_ant_structure(), eeprom_save_ant_sub_menu_array_structure(), eeprom_save_band_data(), eeprom_save_ptt_data(), eeprom_save_radio_settings_structure(), eeprom_save_rx_ant_structure(), eeprom_save_settings_structure(), struct_setting::ext_key_assignments, FIRMWARE_REV, computer_comm_struct::flags, struct_ptt::footswitch, struct_band::high_portion_high_limit, struct_band::high_portion_low_limit, struct_ptt_sequencer::inhibit_post_delay, struct_ptt_sequencer::inhibit_pre_delay, INT_COMM_PC_CTRL, INT_COMM_REDIRECT_DATA, struct_radio_settings::interface_type, internal_comm_add_tx_message(), computer_comm_struct::length, struct_band::low_portion_high_limit, struct_band::low_portion_low_limit, struct_rx_antennas::name, struct_rx_antennas::name_length, struct_setting::network_address, struct_setting::network_device_count, struct_setting::network_device_is_master, struct_rx_antennas::output_length, struct_rx_antennas::output_str, struct_sub_menu_array::output_str_dir, struct_sub_menu_array::output_str_dir_length, struct_radio_settings::poll_interval, struct_setting::powermeter_address, struct_setting::powermeter_update_rate_bargraph, struct_setting::powermeter_update_rate_text, struct_setting::powermeter_vswr_limit, struct_ptt::ptt_input, struct_radio_settings::ptt_input, struct_setting::ptt_interlock_input, struct_radio_settings::radio_model, struct_ptt_sequencer::radio_post_delay, struct_ptt_sequencer::radio_pre_delay, struct_ptt::radio_sense, struct_antenna::rotator_addr, struct_antenna::rotator_delay, struct_antenna::rotator_max_rotation, struct_antenna::rotator_min_heading, struct_antenna::rotator_sub_addr, struct_antenna::rotator_view_360_deg, computer_comm_struct::rx_buffer, computer_comm_struct::rx_buffer_start, struct_radio_settings::stopbits, struct_antenna::sub_menu_type, SUBMENU_STACK, and SUBMENU_VERT_ARRAY.
Referenced by main().