motherboard/main.c File Reference
Main file of the motherboard.
#include <avr/parity.h>
#include `main.h`
#include `board.h`
#include `usart.h`
#include `init.h`
#include `../delay.h`
#include `../internal_comm.h`
#include `../internal_comm_commands.h`
#include `../wmv_bus/bus_commands.h`
#include `computer_interface.h`
Defines
#define PS2_CLK_LOW PORTE &= ~(1<<6)
Macro to put PS2 CLK output LOW.
#define PS2_CLK_HIGH PORTE |= (1<<6)
Macro to put PS2 CLK output HIGH.
#define PS2_DATA_LOW PORTA &= ~(1<<3)
Macro to put PS2 DATA output LOW.
#define PS2_DATA_HIGH PORTA |= (1<<3)
Macro to put PS2 DATA output HIGH.
Functions
void __inline__ tiny_delay (void)
Tiny delay function.
void activate_output (unsigned char index, unsigned char type)
Activate a driver output This function is used to activate an output on the relay driver output in the openASC It controls both the sink and source output at the same time.
void deactivate_output (unsigned char index)
Deactivate a driver output This function is used to deactivate an output on the relay outputs It controls both the sink and source output at the same time.
void parse_internal_comm_message (UC_MESSAGE message)
Parse an internal communication message.
void ps2_keyboard_send (unsigned char cmd)
Send a command to the PS/2 keyboard output/input.
void ps2_process_key (unsigned char key_code)
Process a keystroke.
int main (void)
Main function of the motherboard.
ISR (SIG_OUTPUT_COMPARE0)
Output compare 0 interrupt - `called` with 1ms intervals.
ISR (SIG_OVERFLOW0)
Output overflow 0 interrupt.
ISR (SIG_INTERRUPT6)
Variables
unsigned char temp_count = 0
Counter used for the PS/2 decoding.
unsigned int driver_output_state = 0
The driver output state.
unsigned int driver_output_type [12]
The type of driver output.
unsigned char btn_on_off_last_state = 1
Variable used to keep track of the last state of the ON/OFF button so we can see when it has been pressed and released.
unsigned int counter_time_start = 0
unsigned int counter_ps2 = 0
Counter which keeps track of the PS/2 decoding.
PS2_STRUCT ps2
PS/2 struct.
Detailed Description
Main file of the motherboard.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "motherboard/main.c" 
Definition in file main.c.
Function Documentation
void activate_output (unsigned char index, unsigned char type)
Activate a driver output This function is used to activate an output on the relay driver output in the openASC It controls both the sink and source output at the same time.
Parameters:
index The index of which output to activate (1-12)
type The command that did activate this output
Definition at line 79 of file main.c.
References DRIVER_OUTPUT_1, DRIVER_OUTPUT_10, DRIVER_OUTPUT_11, DRIVER_OUTPUT_12, DRIVER_OUTPUT_2, DRIVER_OUTPUT_3, DRIVER_OUTPUT_4, DRIVER_OUTPUT_5, DRIVER_OUTPUT_6, DRIVER_OUTPUT_7, DRIVER_OUTPUT_8, DRIVER_OUTPUT_9, driver_output_state, and driver_output_type.
void deactivate_output (unsigned char index)
Deactivate a driver output This function is used to deactivate an output on the relay outputs It controls both the sink and source output at the same time.
Parameters:
index The index of which output to activate (1-12)
Definition at line 118 of file main.c.
References DRIVER_OUTPUT_1, DRIVER_OUTPUT_10, DRIVER_OUTPUT_11, DRIVER_OUTPUT_12, DRIVER_OUTPUT_2, DRIVER_OUTPUT_3, DRIVER_OUTPUT_4, DRIVER_OUTPUT_5, DRIVER_OUTPUT_6, DRIVER_OUTPUT_7, DRIVER_OUTPUT_8, DRIVER_OUTPUT_9, driver_output_state, and driver_output_type.
void parse_internal_comm_message (UC_MESSAGE message)
Parse an internal communication message.
Parameters:
message The message that we wish to parse
Definition at line 154 of file main.c.
References activate_output(), AUX_X11_PIN3, AUX_X11_PIN4, AUX_X11_PIN5, AUX_X11_PIN8, AUX_X11_PIN9, BUS_CMD_DRIVER_ACTIVATE_ANT_OUTPUT, BUS_CMD_DRIVER_ACTIVATE_BAND_OUTPUT, BUS_CMD_DRIVER_ACTIVATE_RX_ANT_OUTPUT, BUS_CMD_DRIVER_DEACTIVATE_ALL_ANT_OUTPUTS, BUS_CMD_DRIVER_DEACTIVATE_ALL_BAND_OUTPUTS, BUS_CMD_DRIVER_DEACTIVATE_ALL_OUTPUTS, BUS_CMD_DRIVER_DEACTIVATE_ANT_OUTPUT, BUS_CMD_DRIVER_DEACTIVATE_RX_ANT_OUTPUT, UC_MESSAGE::cmd, computer_interface_send(), UC_MESSAGE::data, deactivate_output(), driver_output_type, INT_COMM_AUX_CHANGE_OUTPUT_PIN, INT_COMM_GET_BAND_BCD_STATUS, INT_COMM_PULL_THE_PLUG, INT_COMM_REDIRECT_DATA, internal_comm_add_tx_message(), and UC_MESSAGE::length.
Referenced by main().
void ps2_keyboard_send (unsigned char cmd)
Send a command to the PS/2 keyboard output/input.
Parameters:
cmd The command we wish to send
Definition at line 279 of file main.c.
References PS2_STRUCT::bit_count, PS2_STRUCT::parity, PS2_CLK_HIGH, PS2_CLK_LOW, PS2_DATA_HIGH, PS2_DATA_LOW, tiny_delay(), PS2_STRUCT::transmit, and PS2_STRUCT::tx_data.
void ps2_process_key (unsigned char key_code)
Process a keystroke.
Parameters:
key_code The key code which was received
Definition at line 301 of file main.c.
References INT_COMM_PS2_KEYPRESSED, and internal_comm_add_tx_message().
Variable Documentation
unsigned int counter_time_start = 0
Counter which keeps track of how long time ago it was since we started the box. This is used at startup so that we ignore button actions on the ON/OFF button for a certain time at startup
Definition at line 58 of file main.c.
Referenced by ISR().