front_panel/radio_interface.h File Reference
Radio interface, such as PTT AMP, PTT Radio, CAT etc.
Classes
struct struct_radio_settings
Radio settings struct.
struct struct_radio_status
The radio status struct.
Defines
#define RADIO_FLAG_FREQ_CHANGED 0
Flag to indicate that the frequency has changed.
#define RADIO_MODEL_KENWOOD 0
Kenwood radio connected to the box.
#define RADIO_MODEL_ICOM 1
ICOM radio connected to the box.
#define RADIO_MODEL_FT1000 2
FT1000D radio connected to the box.
#define RADIO_MODEL_FT1000MP 3
FT1000MP radio connected to the box.
#define RADIO_MODEL_FT1000MKV 4
FT1000MKV radio connected to the box.
#define RADIO_MODEL_FT2000 5
FT2000 radio connected to the box.
#define RADIO_INTERFACE_MANUAL 0
MANUAL mode which means no way to interface the radio.
#define RADIO_INTERFACE_CAT_POLL 1
Serial interface that connects to the radio, POLLING.
#define RADIO_INTERFACE_CAT_MON 2
Serial interface that connects to the radio, MONITORING.
#define RADIO_INTERFACE_BCD 3
BCD interface that connects the radio.
#define RADIO_SENSE_UPPER_FLOOR 1
This bit is set if the radio PTT should be sensed from the upper floor.
#define RADIO_SENSE_LOWER_FLOOR 2
This bit is set if the radio PTT should be sensed from the lower floor.
#define RADIO_SENSE_INVERTED 3
This bit is set if the PTT sense input should be inverted, which means that PTT is active if it's low.
#define RADIO_PTT_ACTIVE 1
PTT Activate.
#define RADIO_PTT_DEACTIVE 2
PTT Deactivate.
#define RADIO_SERIAL_RX_BUFFER_LENGTH 50
Radio serial RX buffer length.
#define RADIO_FLAG_RADIO_PTT 0
Flag to indicate the radio PTT is active.
#define RADIO_FLAG_AMP_PTT 1
Flag to indicate the amp PTT is active.
#define RADIO_FLAG_TX_ACTIVE 2
Flag to indicate the box openASC has enabled a transmission (TX ACTIVE output).
#define RADIO_SERIAL_BAUDRATE_1200 0
Serial baudrate 1200 baud.
#define RADIO_SERIAL_BAUDRATE_2400 1
Serial baudrate 2400 baud.
#define RADIO_SERIAL_BAUDRATE_4800 2
Serial baudrate 4800 baud.
#define RADIO_SERIAL_BAUDRATE_9600 3
Serial baudrate 9600 baud.
#define RADIO_SERIAL_BAUDRATE_14400 4
Serial baudrate 14400 baud.
#define RADIO_SERIAL_BAUDRATE_19200 5
Serial baudrate 19200 baud.
#define RADIO_SERIAL_BAUDRATE_28800 6
Serial baudrate 28800 baud.
#define RADIO_SERIAL_BAUDRATE_38400 7
Serial baudrate 38400 baud.
#define RADIO_SERIAL_BAUDRATE_57600 8
Serial baudrate 57600 baud.
Functions
void radio_process_tasks (void)
This function is called each lap in the main loop and we can use this to process certain tasks.
void radio_interface_init (void)
Initialize the radio interface.
unsigned int radio_get_current_freq (void)
unsigned char radio_get_current_band (void)
Retrieve the current band from the radio.
void radio_set_current_band (unsigned char band)
void radio_ptt (unsigned char status)
unsigned char radio_get_band_portion (void)
unsigned char radio_poll_status (void)
Polls the status of the radio and saves it into the radio_status structure.
void radio_ptt_active (void)
Activate the radio PTT.
void radio_ptt_deactive (void)
Deactivate the radio PTT.
void radio_amp_ptt_active (void)
Activate PTT amp.
void radio_amp_ptt_deactive (void)
Deactivate PTT amp.
void radio_inhibit_low (void)
Set the inhibit signal to low.
void radio_inhibit_high (void)
Set the inhibit signal to high.
unsigned char radio_freq_to_band (unsigned int freq)
Convert a radio frequency (integer) to band data.
void radio_interface_set_model (unsigned char model)
Set which radio model is used, saves it in the radio_settings struct.
void radio_interface_set_interface (unsigned char interface_type)
Set which radio interface is used, saves it in the radio_settings struct.
void radio_interface_set_baudrate (unsigned char baudrate)
Set which baudrate setting is used, saves it in the radio_settings struct.
void radio_interface_set_stopbits (unsigned char stopbits)
Set which number of stopbits should be used, saves it in the radio_settings struct.
void radio_interface_set_civ_addr (unsigned char civ)
Set which CI-V address the radio has got, saves it in the radio_settings struct.
void radio_interface_set_ptt_input (unsigned char ptt_input)
Set which PTT input that is used, saves it in the radio_settings struct.
void radio_interface_set_poll_interval (unsigned char poll_interval)
Set the poll intervall for the radio band decoding, saves it in the radio_settings struct.
unsigned char radio_interface_get_model (void)
Get which radio model is used.
unsigned char radio_interface_get_interface (void)
Get which radio interface is used.
unsigned char radio_interface_get_baudrate (void)
Get which baudrate setting is used.
unsigned char radio_interface_get_stopbits (void)
Get which number of stopbits should be used.
unsigned char radio_interface_get_civ_addr (void)
Get which CI-V address the radio has got.
unsigned char radio_interface_get_ptt_input (void)
Get which PTT input that is used.
unsigned char radio_interface_get_poll_interval (void)
Get the poll intervall for the radio band decoding.
void radio_interface_load_eeprom (void)
This function will load data from the eeprom to the radio_settings struct.
void radio_tx_active (void)
Set the TX ACTIVE output to high.
void radio_tx_deactive (void)
Set the TX ACTIVE output to high.
unsigned char radio_get_ptt_status (void)
Retrieve the ptt status, defines can be found in radio_interface.h.
unsigned char radio_get_cat_status (void)
void radio_communicaton_timeout (void)
Detailed Description
Radio interface, such as PTT AMP, PTT Radio, CAT etc.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/radio_interface.h " 
Definition in file radio_interface.h.
Function Documentation
void radio_communicaton_timeout (void)
This function should be called if an timeout has occured on the serial communication. This function will then reset the pointers used for the CAT decoding
Definition at line 415 of file radio_interface.c.
References struct_radio_status::box_sent_request, radio_serial_rx_buffer, and radio_serial_rx_buffer_start.
Referenced by ISR().
unsigned char radio_freq_to_band (unsigned int freq)
Convert a radio frequency (integer) to band data.
Parameters:
freq The frequency as integer
Returns: The band of the frequency sent in as parameter. If band not found then it returns BAND_UNDEFINED
Definition at line 315 of file radio_interface.c.
References band_ctrl_get_high_portion_high(), and band_ctrl_get_low_portion_low().
Referenced by radio_process_tasks().
unsigned char radio_get_band_portion (void)
Get the portion of the band the radio is on.
Returns: Return BAND_HIGH if it's in the higher portion of the band, BAND_LOW if it's the lower portion. If neither then it returns BAND_UNDEFINED
Definition at line 180 of file radio_interface.c.
References band_ctrl_get_high_portion_high(), band_ctrl_get_high_portion_low(), band_ctrl_get_low_portion_high(), band_ctrl_get_low_portion_low(), struct_radio_status::current_band, and struct_radio_status::current_freq.
Referenced by band_ctrl_get_portion(), display_update_radio_freq(), and main().
unsigned char radio_get_cat_status (void)
This function will tell us if the openASC box has sent any request to the radio
Returns: 1 if a request has been sent, 0 otherwise
Definition at line 423 of file radio_interface.c.
References struct_radio_status::box_sent_request.
Referenced by ISR().
unsigned char radio_get_current_band (void)
Retrieve the current band from the radio.
Returns: The radios band
Definition at line 120 of file radio_interface.c.
References struct_radio_status::current_band.
Referenced by event_internal_comm_parse_message(), and main().
unsigned int radio_get_current_freq (void)
Retrieve the frequency from the radio. If it's configured for BCD it just retrieves the freq band The frequency is returned as an integer so for example 21350 means 21 MHz and 350 kHz.
Returns: The frequency as an integer, max freq 65536
Definition at line 113 of file radio_interface.c.
References struct_radio_status::current_freq.
Referenced by display_update_radio_freq().
unsigned char radio_interface_get_baudrate (void)
Get which baudrate setting is used.
Returns: Which baudrate setting is used
Definition at line 380 of file radio_interface.c.
References struct_radio_settings::baudrate.
unsigned char radio_interface_get_civ_addr (void)
Get which CI-V address the radio has got.
Returns: The CI-V address
Definition at line 392 of file radio_interface.c.
References struct_radio_settings::civ_addr.
unsigned char radio_interface_get_interface (void)
Get which radio interface is used.
Returns: The interface type
Definition at line 374 of file radio_interface.c.
References struct_radio_settings::interface_type.
Referenced by band_ctrl_get_portion(), display_update_radio_freq(), event_aux2_button_pressed(), and main().
unsigned char radio_interface_get_model (void)
Get which radio model is used.
Returns: The radio model
Definition at line 368 of file radio_interface.c.
References struct_radio_settings::radio_model.
unsigned char radio_interface_get_poll_interval (void)
Get the poll intervall for the radio band decoding.
Returns: The poll interval in ms/10
Definition at line 404 of file radio_interface.c.
References struct_radio_settings::poll_interval.
Referenced by ISR().
unsigned char radio_interface_get_ptt_input (void)
Get which PTT input that is used.
Returns: Which PTT input that is used
Definition at line 398 of file radio_interface.c.
References struct_radio_settings::ptt_input.
unsigned char radio_interface_get_stopbits (void)
Get which number of stopbits should be used.
Returns: The number of stopbits that are used to interface the radio
Definition at line 386 of file radio_interface.c.
References struct_radio_settings::stopbits.
void radio_interface_set_baudrate (unsigned char baudrate)
Set which baudrate setting is used, saves it in the radio_settings struct.
Parameters:
baudrate Which baudrate setting to use
Definition at line 338 of file radio_interface.c.
References struct_radio_settings::baudrate.
void radio_interface_set_civ_addr (unsigned char civ)
Set which CI-V address the radio has got, saves it in the radio_settings struct.
Parameters:
civ The CI-V address
Definition at line 350 of file radio_interface.c.
References struct_radio_settings::civ_addr.
void radio_interface_set_interface (unsigned char interface_type)
Set which radio interface is used, saves it in the radio_settings struct.
Parameters:
interface_type The interface type
Definition at line 332 of file radio_interface.c.
References struct_radio_settings::interface_type.
void radio_interface_set_model (unsigned char model)
Set which radio model is used, saves it in the radio_settings struct.
Parameters:
model The radio model
Definition at line 326 of file radio_interface.c.
References struct_radio_settings::radio_model.
void radio_interface_set_poll_interval (unsigned char poll_interval)
Set the poll intervall for the radio band decoding, saves it in the radio_settings struct.
Parameters:
poll_interval The poll interval in ms/10
Definition at line 362 of file radio_interface.c.
References struct_radio_settings::poll_interval.
void radio_interface_set_ptt_input (unsigned char ptt_input)
Set which PTT input that is used, saves it in the radio_settings struct.
Parameters:
ptt_input Which PTT input that is used
Definition at line 356 of file radio_interface.c.
References struct_radio_settings::ptt_input.
void radio_interface_set_stopbits (unsigned char stopbits)
Set which number of stopbits should be used, saves it in the radio_settings struct.
Parameters:
stopbits The number of stopbits that are used to interface the radio
Definition at line 344 of file radio_interface.c.
References struct_radio_settings::stopbits.
unsigned char radio_poll_status (void)
Polls the status of the radio and saves it into the radio_status structure.
Returns: 0 if the poll went OK and 1 if it didn't
Definition at line 205 of file radio_interface.c.
References struct_radio_settings::civ_addr, display_update_radio_freq(), INHIBIT_NOT_OK_TO_SEND_RADIO_TX, INT_COMM_GET_BAND_BCD_STATUS, struct_radio_settings::interface_type, internal_comm_add_tx_message(), main_get_inhibit_state(), RADIO_INTERFACE_BCD, RADIO_INTERFACE_CAT_MON, RADIO_INTERFACE_CAT_POLL, struct_radio_settings::radio_model, RADIO_MODEL_ICOM, and usart3_transmit().
Referenced by main().
void radio_set_current_band (unsigned char band)
Set the current band
Parameters:
band The band we wish to set
Definition at line 191 of file radio_interface.c.
References struct_radio_status::current_band.
Referenced by event_internal_comm_parse_message().