front_panel/sequencer.h File Reference
Sequencer.
Classes
struct struct_ptt_sequencer
All the delays are divided with 10 so 100 is really 1000 ms which makes the maximium delay 2550 ms.
struct struct_ptt
PTT Sequencer struct.
Defines
#define SEQUENCER_EVENT_TYPE_PTT_TX_ACTIVE_ON 1
Event that the radio should be PTT:ed from footswitch.
#define SEQUENCER_EVENT_TYPE_PTT_INHIBIT_ON 2
Event that the inhibit output should be on.
#define SEQUENCER_EVENT_TYPE_PTT_RADIO_ON 3
Event that the radio should be PTT:ed from footswitch.
#define SEQUENCER_EVENT_TYPE_PTT_AMP_ON 4
Event that the amp should be PTT:ed from footswitch.
#define SEQUENCER_EVENT_TYPE_PTT_TX_ACTIVE_OFF 5
Event that the inhibit should be activated from footswitch.
#define SEQUENCER_EVENT_TYPE_PTT_INHIBIT_OFF 6
Event that the TX active output should be off.
#define SEQUENCER_EVENT_TYPE_PTT_RADIO_OFF 7
Event that the radio should be deactivated from footswitch.
#define SEQUENCER_EVENT_TYPE_PTT_AMP_OFF 8
Event that the amp should be deactivated from footswitch.
#define SEQUENCER_EVENT_TYPE_PTT_INHIBIT_OFF 9
Event that the TX active output should be off.
#define PTT_INPUT_FOOTSWITCH 0
Flag bit offset for the footswitch.
#define PTT_INPUT_RADIO_SENSE_UP 1
Flag bit offset for the radio sense on the upper floor.
#define PTT_INPUT_RADIO_SENSE_LO 2
Flag bit offset for the radio sense on the lower floor.
#define PTT_INPUT_COMPUTER_RTS 3
Flag bit offset for the COMPUTER RTS signal.
#define PTT_INPUT_INVERTED_RADIO_SENSE 4
Flag bit offset for an inverted radio sense signal.
#define PTT_INPUT_INVERTED_COMPUTER_RTS 5
Flag bit offset for an inverted computer rts signal.
#define PTT_INPUT_INHIBIT_POLARITY 6
Flag bit offset for the inhibit polarity.
#define SEQUENCER_PTT_RADIO_ENABLED 0
Sequencer enabled for RADIO.
#define SEQUENCER_PTT_AMP_ENABLED 1
Sequencer enabled for AMP.
#define SEQUENCER_PTT_INHIBIT_ENABLED 2
Sequencer enabled for INHIBIT.
Functions
unsigned char sequencer_get_ptt_active (void)
Retrieve which PTT inputs that are currently active, defines above.
void sequencer_load_eeprom (void)
This function will load data from the eeprom to the ptt_sequencer struct.
void sequencer_footsw_pressed (void)
Function to be called if the footswitch is pressed.
void sequencer_footsw_released (void)
Function to be called if the footswitch is released.
void sequencer_computer_rts_activated (void)
Function to be called if the computer rts is activated.
void sequencer_computer_rts_deactivated (void)
Function to be called if the computer rts is deactivated.
void sequencer_radio_sense_activated (void)
Function to be called if the radio sense input is activated.
void sequencer_radio_sense_deactivated (void)
Function to be called if the radio sense input is deactivated.
unsigned char sequencer_get_rts_polarity (void)
Retrieve the polarity of the Computer RTS signal.
unsigned char sequencer_get_sense_polarity (void)
Retrieve the polarity of the radio sense signal.
unsigned char sequencer_ptt_active (void)
Will return if the PTT is active or not.
unsigned char sequencer_get_radio_sense (void)
Retrieve if the radio sense should be sensed from upper floor or bottom.
Detailed Description
Sequencer.
Author: Mikael Larsmark, SM2WMV
Date: 2010-01-25
 #include "front_panel/sequencer.h" 
Definition in file sequencer.h.
Define Documentation
#define SEQUENCER_EVENT_TYPE_PTT_INHIBIT_OFF 9
Event that the TX active output should be off.
Event that the inhibit should be deactiated from footswitch.
Definition at line 47 of file sequencer.h.
#define SEQUENCER_EVENT_TYPE_PTT_INHIBIT_OFF 6
Event that the TX active output should be off.
Event that the inhibit should be deactiated from footswitch.
Definition at line 47 of file sequencer.h.
Referenced by sequencer_computer_rts_deactivated(), and sequencer_footsw_released().
#define SEQUENCER_EVENT_TYPE_PTT_TX_ACTIVE_ON 1
Event that the radio should be PTT:ed from footswitch.
Sequencer message types, this is used to we can keep track of different messages in the event queue. So if an event is aborted we can easily just remove the upcoming events from the queue, that doesn't need to be executed
Definition at line 31 of file sequencer.h.
Referenced by sequencer_computer_rts_activated(), sequencer_computer_rts_deactivated(), sequencer_footsw_pressed(), and sequencer_footsw_released().
Function Documentation
unsigned char sequencer_get_radio_sense (void)
Retrieve if the radio sense should be sensed from upper floor or bottom.
Returns: 0 if lower floor, 1 if upper floor
Definition at line 231 of file sequencer.c.
References struct_ptt::ptt_input, and PTT_INPUT_RADIO_SENSE_UP.
Referenced by event_parse_ext_event().
unsigned char sequencer_get_rts_polarity (void)
Retrieve the polarity of the Computer RTS signal.
Returns: 1 if the polarity is active low (inverted), 0 otherwise
Definition at line 210 of file sequencer.c.
References struct_ptt::ptt_input, and PTT_INPUT_INVERTED_COMPUTER_RTS.
Referenced by event_parse_ext_event().
unsigned char sequencer_get_sense_polarity (void)
Retrieve the polarity of the radio sense signal.
Returns: 1 if the polarity is active low (inverted), 0 otherwise
Definition at line 219 of file sequencer.c.
References struct_ptt::ptt_input, and PTT_INPUT_INVERTED_RADIO_SENSE.
Referenced by event_parse_ext_event().
unsigned char sequencer_ptt_active (void)
Will return if the PTT is active or not.
Returns: The state of the ptt_active variable, 0 if nothing is PTTing the radio
Definition at line 225 of file sequencer.c.
References ptt_active.